WORDS = {
    "aangezien": ("adjective", "since, considering", None),
    "aanvaardbaar": ("adjective", "acceptable", None),
    "aanvang": ("noun", "start, beginning", "de"),
    "aanvoelen": ("verb", "to sense, to feel", None),
    "aanvoeren": ("verb", "to lead; to supply; to argue", None),
    "aanwenden": ("verb", "to use, to apply", None),
    "aanzet": ("noun", "impetus, start", "de"),
    "aanzetten": ("verb", "to turn on; to encourage", None),
    "aap": ("noun", "monkey", "de"),
    "aarzeling": ("noun", "hesitation", "de"),
    "abrupt": ("adjective", "abrupt", None),
    "abstract": ("adjective", "abstract", None),
    "absurd": ("adjective", "absurd", None),
    "academie": ("noun", "academy", "de"),
    "academisch": ("adjective", "academic", None),
    "achteloos": ("adjective", "careless, casual", None),
    "achten": ("verb", "to consider; to esteem", None),
    "achteraan": ("adjective", "at the back", None),
    "achteraf": ("adjective", "afterwards; in hindsight", None),
    "achterblijven": ("verb", "to stay behind; to lag", None),
    "achtergrond": ("noun", "background", "de"),
    "achterhalen": ("verb", "to find out; to catch up", None),
    "achterkant": ("noun", "back side", "de"),
    "achterlaten": ("verb", "to leave behind", None),
    "achtervolgen": ("verb", "to chase, to pursue", None),
    "acteur": ("noun", "actor", "de"),
    "actueel": ("adjective", "current, topical", None),
    "acuut": ("adjective", "acute", None),
    "adel": ("noun", "nobility", "de"),
    "ademhaling": ("noun", "breathing, respiration", "de"),
    "adequaat": ("adjective", "adequate", None),
    "ader": ("noun", "vein", "de"),
    "administratie": ("noun", "administration", "de"),
    "adolescent": ("noun", "adolescent", "de"),
    "advertentie": ("noun", "advertisement", "de"),
    "adviseren": ("verb", "to advise", None),
    "adviseur": ("noun", "advisor", "de"),
    "afbeelden": ("verb", "to depict", None),
    "afbeelding": ("noun", "image, illustration", "de"),
    "afbreken": ("verb", "to demolish; to break off", None),
    "afdoen": ("verb", "to take off; to settle", None),
    "affaire": ("noun", "affair", "de"),
    "afgaan": ("verb", "to go off; to go down", None),
    "afgevaardigde": ("noun", "delegate", "de"),
    "afgrond": ("noun", "abyss", "de"),
    "afhangen": ("verb", "to depend on", None),
    "afkomen": ("verb", "to come from; to come down", None),
    "afkomst": ("noun", "origin, descent", "de"),
    "afmaken": ("verb", "to finish; to kill", None),
    "afmeting": ("noun", "dimension, measurement", "de"),
    "afschaffen": ("verb", "to abolish", None),
    "afsnijden": ("verb", "to cut off", None),
    "afspreken": ("verb", "to agree; to arrange", None),
    "afstemmen": ("verb", "to tune; to coordinate", None),
    "afval": ("noun", "waste, garbage", "het"),
    "afwachten": ("verb", "to wait and see", None),
    "afwezig": ("adjective", "absent", None),
    "afzetten": ("verb", "to take off; to drop off; to depose", None),
    "agressie": ("noun", "aggression", "de"),
    "akelig": ("adjective", "unpleasant, nasty", None),
    "akker": ("noun", "field (agricultural)", "de"),
    "akkoord": ("noun", "agreement", "het"),
    "akte": ("noun", "deed, certificate", "de"),
    "alledaags": ("adjective", "everyday, ordinary", None),
    "altaar": ("noun", "altar", "het"),
    "ambassade": ("noun", "embassy", "de"),
    "ambassadeur": ("noun", "ambassador", "de"),
    "ambitie": ("noun", "ambition", "de"),
    "ambt": ("noun", "office, position", "het"),
    "ambtelijk": ("adjective", "official, bureaucratic", None),
    "amuseren": ("verb", "to amuse", None),
    "ander": ("adjective", "other", None),
    "anderhalf": ("adjective", "one and a half", None),
    "anders": ("adjective", "different; otherwise", None),
    "anderzijds": ("adjective", "on the other hand", None),
    "anoniem": ("adjective", "anonymous", None),
    "antiek": ("adjective", "antique", None),
    "apparatuur": ("noun", "equipment", "de"),
    "appartement": ("noun", "apartment", "het"),
    "arbeidsmarkt": ("noun", "labor market", "de"),
    "architect": ("noun", "architect", "de"),
    "armoede": ("noun", "poverty", "de"),
    "arresteren": ("verb", "to arrest", None),
    "arriveren": ("verb", "to arrive", None),
    "artistiek": ("adjective", "artistic", None),
    "asbak": ("noun", "ashtray", "de"),
    "assistent": ("noun", "assistant", "de"),
    "atelier": ("noun", "studio, workshop", "het"),
    "atmosfeer": ("noun", "atmosphere", "de"),
    "attitude": ("noun", "attitude", "de"),
    "autonomie": ("noun", "autonomy", "de"),
    "autonoom": ("adjective", "autonomous", None),
    "baai": ("noun", "bay", "de"),
    "baard": ("noun", "beard", "de"),
    "baat": ("noun", "benefit", "de"),
    "babbelen": ("verb", "to chat", None),
    "bacterie": ("noun", "bacteria", "de"),
    "baden": ("verb", "to bathe", None),
    "bagage": ("noun", "luggage", "de"),
    "bak": ("noun", "container; tray", "de"),
    "bakken": ("verb", "to bake; to fry", None),
    "bakker": ("noun", "baker", "de"),
    "balans": ("noun", "balance", "de"),
    "balk": ("noun", "beam", "de"),
    "balkon": ("noun", "balcony", "het"),
    "bankier": ("noun", "banker", "de"),
    "baren": ("verb", "to give birth; to cause", None),
    "baron": ("noun", "baron", "de"),
    "bedaren": ("verb", "to calm down", None),
    "bedekt": ("adjective", "covered", None),
    "bederven": ("verb", "to spoil, to ruin", None),
    "bediende": ("noun", "servant, employee", "de"),
    "bedrijfsleven": ("noun", "business world", "het"),
    "bedrog": ("noun", "deception, fraud", "het"),
    "bedwingen": ("verb", "to control, to suppress", None),
    "beek": ("noun", "stream, brook", "de"),
    "beer": ("noun", "bear", "de"),
    "begaafd": ("adjective", "gifted, talented", None),
    "begaan": ("verb", "to commit; to walk on", None),
    "begeerte": ("noun", "desire", "de"),
    "begeleiding": ("noun", "guidance, accompaniment", "de"),
    "begeren": ("verb", "to desire", None),
    "beginselen": ("noun", "principles", "de"),
    "behalen": ("verb", "to achieve, to obtain", None),
    "beheer": ("noun", "management, administration", "het"),
    "beheerst": ("adjective", "controlled, composed", None),
    "behoedzaam": ("adjective", "cautious", None),
    "behoeven": ("verb", "to need", None),
    "behoud": ("noun", "preservation", "het"),
    "bek": ("noun", "mouth (animal); beak", "de"),
    "beker": ("noun", "cup, mug", "de"),
    "beklagen": ("verb", "to pity; to complain", None),
    "bekleden": ("verb", "to occupy (position); to cover", None),
    "beklimmen": ("verb", "to climb", None),
    "bekommeren": ("verb", "to worry about", None),
    "bekwaam": ("adjective", "capable, competent", None),
    "belanden": ("verb", "to end up", None),
    "belasten": ("verb", "to tax; to burden", None),
    "beledigen": ("verb", "to insult, to offend", None),
    "beleefd": ("adjective", "polite", None),
    "belemmeren": ("verb", "to hinder, to obstruct", None),
    "beletten": ("verb", "to prevent", None),
    "belonen": ("verb", "to reward", None),
    "beloning": ("noun", "reward", "de"),
    "bemerken": ("verb", "to notice", None),
    "benadrukken": ("verb", "to emphasize", None),
    "benaming": ("noun", "name, designation", "de"),
    "bende": ("noun", "gang; mess", "de"),
    "benodigd": ("adjective", "required, needed", None),
    "benoeming": ("noun", "appointment", "de"),
    "benutten": ("verb", "to utilize", None),
    "beoefenen": ("verb", "to practice", None),
    "beogen": ("verb", "to aim at, to intend", None),
    "bepleiten": ("verb", "to advocate", None),
    "bereik": ("noun", "reach, range", "het"),
    "berekenen": ("verb", "to calculate", None),
    "berekening": ("noun", "calculation", "de"),
    "bergen": ("verb", "to store; to salvage", None),
    "beroepen": ("verb", "to appeal; to invoke", None),
    "beroven": ("verb", "to rob", None),
    "berucht": ("adjective", "notorious", None),
    "beschuldigen": ("verb", "to accuse", None),
    "beschuldiging": ("noun", "accusation", "de"),
    "beslissend": ("adjective", "decisive", None),
    "besluitvorming": ("noun", "decision-making", "de"),
    "besparen": ("verb", "to save (money/effort)", None),
    "bespeuren": ("verb", "to detect, to notice", None),
    "bestand": ("noun", "file; truce", "het"),
    "bestanddeel": ("noun", "component, ingredient", "het"),
    "bestel": ("noun", "system, order", "het"),
    "bestemming": ("noun", "destination", "de"),
    "besturen": ("verb", "to govern; to drive", None),
    "bestuurder": ("noun", "driver; administrator", "de"),
    "betogen": ("verb", "to argue; to demonstrate", None),
    "betoog": ("noun", "argument, discourse", "het"),
    "betrappen": ("verb", "to catch (in the act)", None),
    "betreden": ("verb", "to enter", None),
    "betreuren": ("verb", "to regret", None),
    "betwijfelen": ("verb", "to doubt", None),
    "bevinding": ("noun", "finding", "de"),
    "bevoegd": ("adjective", "authorized, competent", None),
    "bevriend": ("adjective", "friendly, befriended", None),
    "bevriezen": ("verb", "to freeze", None),
    "bewaken": ("verb", "to guard", None),
    "bewering": ("noun", "claim, assertion", "de"),
    "bewerken": ("verb", "to edit; to work on", None),
    "bewerkstelligen": ("verb", "to bring about", None),
    "bewind": ("noun", "rule, government", "het"),
    "bewonen": ("verb", "to inhabit", None),
    "bezet": ("adjective", "occupied", None),
    "bezetten": ("verb", "to occupy", None),
    "bezetting": ("noun", "occupation", "de"),
    "bezigheid": ("noun", "activity, occupation", "de"),
    "bezitting": ("noun", "possession", "de"),
    "bezweren": ("verb", "to swear; to exorcise", None),
    "beëindigen": ("verb", "to end, to terminate", None),
    "beïnvloeden": ("verb", "to influence", None),
    "bijzonderheid": ("noun", "detail, particular", "de"),
    "bil": ("noun", "buttock", "de"),
    "binnendringen": ("verb", "to penetrate, to intrude", None),
    "binnenkant": ("noun", "inside", "de"),
    "binnenkomen": ("verb", "to enter, to come in", None),
    "binnenlands": ("adjective", "domestic", None),
    "binnenplaats": ("noun", "courtyard", "de"),
    "bioscoop": ("noun", "cinema", "de"),
    "bladeren": ("verb", "to browse, to leaf through", None),
    "blaffen": ("verb", "to bark", None),
    "blijk": ("noun", "sign, token", "het"),
    "blijvend": ("adjective", "lasting, permanent", None),
    "bliksem": ("noun", "lightning", "de"),
    "blinken": ("verb", "to shine", None),
    "bloeden": ("verb", "to bleed", None),
    "bloei": ("noun", "bloom, flourishing", "de"),
    "blozen": ("verb", "to blush", None),
    "boeiend": ("adjective", "fascinating", None),
    "boeken": ("verb", "to book, to reserve", None),
    "boerin": ("noun", "farmer's wife", "de"),
    "bol": ("noun", "sphere; ball", "de"),
    "bom": ("noun", "bomb", "de"),
    "bond": ("noun", "union, league", "de"),
    "bont": ("adjective", "colorful; fur", None),
    "boon": ("noun", "bean", "de"),
    "boren": ("verb", "to drill", None),
    "borrel": ("noun", "drink (alcoholic)", "de"),
    "bot": ("adjective", "blunt; bone", None),
    "boterham": ("noun", "sandwich, slice of bread", "de"),
    "botsen": ("verb", "to collide", None),
    "botsing": ("noun", "collision, crash", "de"),
    "bouw": ("noun", "construction", "de"),
    "bouwwerk": ("noun", "building, structure", "het"),
    "bovengenoemd": ("adjective", "above-mentioned", None),
    "bovenop": ("adjective", "on top of", None),
    "bovenstaand": ("adjective", "above-mentioned", None),
    "breien": ("verb", "to knit", None),
    "brein": ("noun", "brain, mind", "het"),
    "breuk": ("noun", "fracture; fraction", "de"),
    "briljant": ("adjective", "brilliant", None),
    "brok": ("noun", "chunk, piece", "de"),
    "brommen": ("verb", "to hum; to grumble", None),
    "brouwerij": ("noun", "brewery", "de"),
    "bruikbaar": ("adjective", "usable", None),
    "brutaal": ("adjective", "rude, cheeky", None),
    "bui": ("noun", "shower (rain); mood", "de"),
    "buit": ("noun", "loot, booty", "de"),
    "buitengewoon": ("adjective", "extraordinary", None),
    "buitenland": ("noun", "abroad, foreign country", "het"),
    "buitenlander": ("noun", "foreigner", "de"),
    "buitenlands": ("adjective", "foreign", None),
    "buitenstaander": ("noun", "outsider", "de"),
    "buitenwereld": ("noun", "outside world", "de"),
    "bukken": ("verb", "to bend down", None),
    "buurman": ("noun", "neighbor (male)", "de"),
    "cabine": ("noun", "cabin", "de"),
    "cadeau": ("noun", "gift, present", "het"),
    "café": ("noun", "café, pub", "het"),
    "camera": ("noun", "camera", "de"),
    "capaciteit": ("noun", "capacity", "de"),
    "carrière": ("noun", "career", "de"),
    "chaos": ("noun", "chaos", "de"),
    "charmant": ("adjective", "charming", None),
    "charme": ("noun", "charm", "de"),
    "chronisch": ("adjective", "chronic", None),
    "citaat": ("noun", "quote, citation", "het"),
    "citroen": ("noun", "lemon", "de"),
    "cliënt": ("noun", "client", "de"),
    "club": ("noun", "club", "de"),
    "code": ("noun", "code", "de"),
    "cognitief": ("adjective", "cognitive", None),
    "collectie": ("noun", "collection", "de"),
    "collega": ("noun", "colleague", "de"),
    "combineren": ("verb", "to combine", None),
    "comité": ("noun", "committee", "het"),
    "commercieel": ("adjective", "commercial", None),
    "communisme": ("noun", "communism", "het"),
    "communist": ("noun", "communist", "de"),
    "compagnie": ("noun", "company", "de"),
    "complex": ("adjective", "complex", None),
    "compliment": ("noun", "compliment", "het"),
    "component": ("noun", "component", "de"),
    "componist": ("noun", "composer", "de"),
    "compromis": ("noun", "compromise", "het"),
    "concentratie": ("noun", "concentration", "de"),
    "concept": ("noun", "concept; draft", "het"),
    "concert": ("noun", "concert", "het"),
    "concurrentie": ("noun", "competition", "de"),
    "conditie": ("noun", "condition, fitness", "de"),
    "conferentie": ("noun", "conference", "de"),
    "confrontatie": ("noun", "confrontation", "de"),
    "congres": ("noun", "congress", "het"),
    "consequent": ("adjective", "consistent", None),
    "conservatief": ("adjective", "conservative", None),
    "constant": ("adjective", "constant", None),
    "constructie": ("noun", "construction", "de"),
    "construeren": ("verb", "to construct", None),
    "consumptie": ("noun", "consumption", "de"),
    "context": ("noun", "context", "de"),
    "continent": ("noun", "continent", "het"),
    "contract": ("noun", "contract", "het"),
    "contrast": ("noun", "contrast", "het"),
    "correct": ("adjective", "correct", None),
    "corrigeren": ("verb", "to correct", None),
    "coördinatie": ("noun", "coordination", "de"),
    "creatief": ("adjective", "creative", None),
    "creëren": ("verb", "to create", None),
    "cursus": ("noun", "course", "de"),
    "daadwerkelijk": ("adjective", "actual, real", None),
    "dadelijk": ("adjective", "immediately", None),
    "dader": ("noun", "perpetrator", "de"),
    "dagblad": ("noun", "daily newspaper", "het"),
    "daglicht": ("noun", "daylight", "het"),
    "dans": ("noun", "dance", "de"),
    "dapper": ("adjective", "brave", None),
    "darm": ("noun", "intestine", "de"),
    "dateren": ("verb", "to date", None),
    "datum": ("noun", "date", "de"),
    "debat": ("noun", "debate", "het"),
    "decennium": ("noun", "decade", "het"),
    "definiëren": ("verb", "to define", None),
    "deftig": ("adjective", "distinguished, posh", None),
    "dek": ("noun", "deck; blanket", "het"),
    "deksel": ("noun", "lid, cover", "het"),
    "delegatie": ("noun", "delegation", "de"),
    "delven": ("verb", "to dig", None),
    "demonstratie": ("noun", "demonstration", "de"),
    "demonstreren": ("verb", "to demonstrate", None),
    "dempen": ("verb", "to fill in; to dampen", None),
    "denkbeeldig": ("adjective", "imaginary", None),
    "departement": ("noun", "department", "het"),
    "depressie": ("noun", "depression", "de"),
    "deskundig": ("adjective", "expert, skilled", None),
    "deugd": ("noun", "virtue", "de"),
    "deugen": ("verb", "to be good, to be fit", None),
    "deuropening": ("noun", "doorway", "de"),
    "dialoog": ("noun", "dialogue", "de"),
    "dictatuur": ("noun", "dictatorship", "de"),
    "dieet": ("noun", "diet", "het"),
    "dief": ("noun", "thief", "de"),
    "dienstverlening": ("noun", "service delivery", "de"),
    "dierenarts": ("noun", "veterinarian", "de"),
    "dikwijls": ("adjective", "often", None),
    "diner": ("noun", "dinner", "het"),
    "discipline": ("noun", "discipline", "de"),
    "district": ("noun", "district", "het"),
    "docent": ("noun", "teacher, lecturer", "de"),
    "doelen": ("verb", "to aim at", None),
    "doeltreffend": ("adjective", "effective", None),
    "dof": ("adjective", "dull, muffled", None),
    "domein": ("noun", "domain", "het"),
    "dominee": ("noun", "minister, pastor", "de"),
    "domineren": ("verb", "to dominate", None),
    "donder": ("noun", "thunder", "de"),
    "donderen": ("verb", "to thunder", None),
    "doodgaan": ("verb", "to die", None),
    "doodstil": ("adjective", "dead silent", None),
    "doorgeven": ("verb", "to pass on", None),
    "doormaken": ("verb", "to go through, to experience", None),
    "doorstaan": ("verb", "to endure", None),
    "doorzichtig": ("adjective", "transparent", None),
    "dopen": ("verb", "to baptize; to dip", None),
    "dorst": ("noun", "thirst", "de"),
    "dosis": ("noun", "dose", "de"),
    "dossier": ("noun", "file, dossier", "het"),
    "douche": ("noun", "shower", "de"),
    "doven": ("verb", "to extinguish", None),
    "dozijn": ("noun", "dozen", "het"),
    "drama": ("noun", "drama", "het"),
    "dramatisch": ("adjective", "dramatic", None),
    "drang": ("noun", "urge", "de"),
    "dreiging": ("noun", "threat", "de"),
    "drempel": ("noun", "threshold", "de"),
    "dreunen": ("verb", "to rumble, to boom", None),
    "drift": ("noun", "anger; drift", "de"),
    "driftig": ("adjective", "hot-tempered", None),
    "drijven": ("verb", "to float; to drive", None),
    "dringend": ("adjective", "urgent", None),
    "droevig": ("adjective", "sad", None),
    "dromer": ("noun", "dreamer", "de"),
    "drug": ("noun", "drug", "de"),
    "drukte": ("noun", "bustle, busyness", "de"),
    "dubbel": ("adjective", "double", None),
    "duif": ("noun", "pigeon, dove", "de"),
    "duiken": ("verb", "to dive", None),
    "duin": ("noun", "dune", "het"),
    "duivel": ("noun", "devil", "de"),
    "dulden": ("verb", "to tolerate", None),
    "dun": ("adjective", "thin", None),
    "duwen": ("verb", "to push", None),
    "dwaas": ("adjective", "foolish", None),
    "dwalen": ("verb", "to wander; to err", None),
    "dwang": ("noun", "coercion", "de"),
    "dwars": ("adjective", "diagonal; stubborn", None),
}
