WORDS = {
    # E
    "echtgenoot": ("noun", "husband, spouse", "de"),
    "economie": ("noun", "economy", "de"),
    "economisch": ("adjective", "economic", None),
    "eend": ("noun", "duck", "de"),
    "eens": ("adjective", "once; agreed", None),
    "eentje": ("noun", "one (informal)", "het"),
    "eenvoudig": ("adjective", "simple", None),
    "eenzaamheid": ("noun", "loneliness", "de"),
    "eer": ("noun", "honor", "de"),
    "eerder": ("adjective", "earlier; rather", None),
    "eerlijk": ("adjective", "honest", None),
    "eerst": ("adjective", "first", None),
    "eeuwen": ("noun", "century", "de"),
    "effect": ("noun", "effect", "het"),
    "effectief": ("adjective", "effective", None),
    "eigen": ("adjective", "own", None),
    "eigenaardig": ("adjective", "peculiar, strange", None),
    "eigendom": ("noun", "property, ownership", "het"),
    "eigenlijk": ("adjective", "actually; real", None),
    "einde": ("noun", "end", "het"),
    "eindelijk": ("adjective", "finally", None),
    "eis": ("noun", "demand, requirement", "de"),
    "eisen": ("verb", "to demand", None),
    "elektrisch": ("adjective", "electric", None),
    "element": ("noun", "element", "het"),
    "elf": ("adjective", "eleven", None),
    "ellende": ("noun", "misery", "de"),
    "empirisch": ("adjective", "empirical", None),
    "engel": ("noun", "angel", "de"),
    "enig": ("adjective", "only; some; unique", None),
    "enkel": ("adjective", "single; only", None),
    "enorm": ("adjective", "enormous", None),
    "enthousiast": ("adjective", "enthusiastic", None),
    "erg": ("adjective", "bad; very", None),
    "ergens": ("adjective", "somewhere", None),
    "ergeren": ("verb", "to annoy, to irritate", None),
    "erkennen": ("verb", "to acknowledge, to recognize", None),
    "erkenning": ("noun", "recognition", "de"),
    "ernst": ("noun", "seriousness", "de"),
    "ernstig": ("adjective", "serious", None),
    "ervaren": ("verb", "to experience", None),
    "ervaring": ("noun", "experience", "de"),
    "essentieel": ("adjective", "essential", None),
    "ethisch": ("adjective", "ethical", None),
    "eventueel": ("adjective", "possible, potential", None),
    "exemplaar": ("noun", "copy; specimen", "het"),
    # F
    "falen": ("verb", "to fail", None),
    "familielid": ("noun", "family member", "het"),
    "familie": ("noun", "family", "de"),
    "fantasie": ("noun", "fantasy, imagination", "de"),
    "fase": ("noun", "phase", "de"),
    "feit": ("noun", "fact", "het"),
    "feitelijk": ("adjective", "actual, factual", None),
    "figuur": ("noun", "figure", "het"),
    "filosofie": ("noun", "philosophy", "de"),
    "filosoof": ("noun", "philosopher", "de"),
    "financieel": ("adjective", "financial", None),
    "firma": ("noun", "firm, company", "de"),
    "flat": ("noun", "apartment", "de"),
    "flauw": ("adjective", "faint; lame", None),
    "fluiten": ("verb", "to whistle", None),
    "formeel": ("adjective", "formal", None),
    "formuleren": ("verb", "to formulate", None),
    "foto": ("noun", "photo", "de"),
    "fout": ("noun", "mistake, error", "de"),
    "fractie": ("noun", "fraction; political faction", "de"),
    "fris": ("adjective", "fresh, cool", None),
    "front": ("noun", "front", "het"),
    "functie": ("noun", "function, position", "de"),
    "functioneren": ("verb", "to function", None),
    "fysiek": ("adjective", "physical", None),
    # G
    "gang": ("noun", "corridor; course; pace", "de"),
    "gas": ("noun", "gas", "het"),
    "gast": ("noun", "guest", "de"),
    "gauw": ("adjective", "quick, soon", None),
    "gaan": ("verb", "to go", None),
    "geacht": ("adjective", "esteemed", None),
    "gebed": ("noun", "prayer", "het"),
    "gebeuren": ("verb", "to happen", None),
    "gebeurtenis": ("noun", "event", "de"),
    "gebied": ("noun", "area, territory", "het"),
    "gebouw": ("noun", "building", "het"),
    "gebrek": ("noun", "lack; defect", "het"),
    "gebruik": ("noun", "use", "het"),
    "gebruiken": ("verb", "to use", None),
    "gebruiker": ("noun", "user", "de"),
    "gedachte": ("noun", "thought", "de"),
    "gedeelte": ("noun", "part, portion", "het"),
    "geduld": ("noun", "patience", "het"),
    "gedurende": ("adjective", "during", None),
    "gedrag": ("noun", "behavior", "het"),
    "geel": ("adjective", "yellow", None),
    "geen": ("adjective", "no, none", None),
    "geest": ("noun", "spirit, mind", "de"),
    "gegeven": ("noun", "fact, datum", "het"),
    "geheim": ("noun", "secret", "het"),
    "geheimzinnig": ("adjective", "mysterious", None),
    "geheel": ("noun", "whole, entirety", "het"),
    "gek": ("adjective", "crazy, silly", None),
    "geld": ("noun", "money", "het"),
    "gelden": ("verb", "to apply, to be valid", None),
    "geldig": ("adjective", "valid", None),
    "gelegenheid": ("noun", "opportunity; occasion", "de"),
    "geleidelijk": ("adjective", "gradual", None),
    "geloof": ("noun", "faith, belief", "het"),
    "geloven": ("verb", "to believe", None),
    "geluid": ("noun", "sound", "het"),
    "geluk": ("noun", "happiness; luck", "het"),
    "gelukkig": ("adjective", "happy; fortunately", None),
    "gemakkelijk": ("adjective", "easy", None),
    "gemeente": ("noun", "municipality", "de"),
    "gemiddeld": ("adjective", "average", None),
    "geneesmiddel": ("noun", "medicine, drug", "het"),
    "generatie": ("noun", "generation", "de"),
    "genieten": ("verb", "to enjoy", None),
    "genoeg": ("adjective", "enough", None),
    "genoegen": ("noun", "pleasure", "het"),
    "genot": ("noun", "enjoyment, pleasure", "het"),
    "geraakt": ("adjective", "touched, affected", None),
    "geraken": ("verb", "to get to; to become", None),
    "gerecht": ("noun", "dish; court", "het"),
    "gereed": ("adjective", "ready, prepared", None),
    "geregeld": ("adjective", "regular", None),
    "gerust": ("adjective", "reassured, calm", None),
    "geschieden": ("verb", "to happen, to occur", None),
    "geschiedenis": ("noun", "history", "de"),
    "geschikt": ("adjective", "suitable", None),
    "geschrift": ("noun", "writing, document", "het"),
    "geslacht": ("noun", "gender; generation", "het"),
    "gespannen": ("adjective", "tense, nervous", None),
    "gesprek": ("noun", "conversation", "het"),
    "gestalte": ("noun", "figure, shape", "de"),
    "getal": ("noun", "number", "het"),
    "getrouwd": ("adjective", "married", None),
    "getuige": ("noun", "witness", "de"),
    "getuigen": ("verb", "to testify", None),
    "gevaar": ("noun", "danger", "het"),
    "gevaarlijk": ("adjective", "dangerous", None),
    "geval": ("noun", "case", "het"),
    "gevangene": ("noun", "prisoner", "de"),
    "gevangenis": ("noun", "prison", "de"),
    "gevecht": ("noun", "fight, battle", "het"),
    "geven": ("verb", "to give", None),
    "gevoel": ("noun", "feeling", "het"),
    "gevoelig": ("adjective", "sensitive", None),
    "gevolg": ("noun", "consequence", "het"),
    "geweld": ("noun", "violence", "het"),
    "geweldig": ("adjective", "tremendous, great", None),
    "geweten": ("noun", "conscience", "het"),
    "gewicht": ("noun", "weight", "het"),
    "gewoon": ("adjective", "normal, ordinary", None),
    "gewoonte": ("noun", "habit, custom", "de"),
    "gezag": ("noun", "authority", "het"),
    "gezamenlijk": ("adjective", "joint, collective", None),
    "gezeten": ("adjective", "seated; established", None),
    "gezicht": ("noun", "face", "het"),
    "gezin": ("noun", "family (nuclear)", "het"),
    "gezond": ("adjective", "healthy", None),
    "gezondheid": ("noun", "health", "de"),
    "gieten": ("verb", "to pour", None),
    "gillen": ("verb", "to scream", None),
    "glad": ("adjective", "smooth; slippery", None),
    "glas": ("noun", "glass", "het"),
    "glimmen": ("verb", "to shine, to gleam", None),
    "glimlachen": ("verb", "to smile", None),
    "gloeien": ("verb", "to glow", None),
    "god": ("noun", "god", "de"),
    "goddelijk": ("adjective", "divine", None),
    "godsdienstig": ("adjective", "religious", None),
    "goed": ("adjective", "good", None),
    "goedkoop": ("adjective", "cheap", None),
    "goud": ("noun", "gold", "het"),
    "graad": ("noun", "degree", "de"),
    "graaf": ("noun", "count (nobility)", "de"),
    "graag": ("adjective", "gladly, willingly", None),
    "graf": ("noun", "grave", "het"),
    "grap": ("noun", "joke", "de"),
    "grauw": ("adjective", "gray, grim", None),
    "graven": ("verb", "to dig", None),
    "grens": ("noun", "border, limit", "de"),
    "grijnzen": ("verb", "to grin", None),
    "grinniken": ("verb", "to chuckle", None),
    "groei": ("noun", "growth", "de"),
    "groeien": ("verb", "to grow", None),
    "groente": ("noun", "vegetable", "de"),
    "groep": ("noun", "group", "de"),
    "groeten": ("verb", "to greet", None),
    "grof": ("adjective", "coarse, rude", None),
    "grommen": ("verb", "to growl", None),
    "grond": ("noun", "ground; reason", "de"),
    "grondig": ("adjective", "thorough", None),
    "groot": ("adjective", "big, great", None),
    "grootmoeder": ("noun", "grandmother", "de"),
    "grootst": ("adjective", "greatest, largest", None),
    "grootte": ("noun", "size", "de"),
    "grootvader": ("noun", "grandfather", "de"),
    "grotendeels": ("adjective", "largely, mostly", None),
    "gulden": ("noun", "guilder", "de"),
    "gunnen": ("verb", "to grant; to not begrudge", None),
    "gunst": ("noun", "favor", "de"),
    # H
    "haar": ("noun", "hair", "het"),
    "haasten": ("verb", "to hurry", None),
    "haastig": ("adjective", "hasty", None),
    "haat": ("noun", "hatred", "de"),
    "hal": ("noun", "hall", "de"),
    "halen": ("verb", "to get, to fetch", None),
    "half": ("adjective", "half", None),
    "hand": ("noun", "hand", "de"),
    "handelen": ("verb", "to act; to trade", None),
    "handeling": ("noun", "action; plot", "de"),
    "handig": ("adjective", "handy, clever", None),
    "hangen": ("verb", "to hang", None),
    "hanteren": ("verb", "to handle", None),
    "hard": ("adjective", "hard; fast; loud", None),
    "hart": ("noun", "heart", "het"),
    "hartelijk": ("adjective", "warm, cordial", None),
    "haten": ("verb", "to hate", None),
    "haven": ("noun", "harbor, port", "de"),
    "hechten": ("verb", "to attach; to value", None),
    "heffen": ("verb", "to raise; to levy", None),
    "heftig": ("adjective", "fierce, intense", None),
    "hek": ("noun", "fence, gate", "het"),
    "held": ("noun", "hero", "de"),
    "helft": ("noun", "half", "de"),
    "helling": ("noun", "slope", "de"),
    "helpen": ("verb", "to help", None),
    "hemd": ("noun", "shirt, undershirt", "het"),
    "hemel": ("noun", "sky, heaven", "de"),
    "herhaaldelijk": ("adjective", "repeatedly", None),
    "herhalen": ("verb", "to repeat", None),
    "herinneren": ("verb", "to remember; to remind", None),
    "herinnering": ("noun", "memory, recollection", "de"),
    "herkennen": ("verb", "to recognize", None),
    "hersenen": ("noun", "brain", "de"),
    "herstel": ("noun", "recovery", "het"),
    "herstellen": ("verb", "to repair; to recover", None),
    "hertog": ("noun", "duke", "de"),
    "heup": ("noun", "hip", "de"),
    "heus": ("adjective", "really; genuine", None),
    "hevige": ("adjective", "fierce, severe", None),
    "hijgen": ("verb", "to pant", None),
    "historie": ("noun", "history", "de"),
    "historisch": ("adjective", "historical", None),
    "hitte": ("noun", "heat", "de"),
    "hoe": ("adjective", "how", None),
    "hoek": ("noun", "corner; angle", "de"),
    "hof": ("noun", "court; garden", "het"),
    "hol": ("noun", "cave; hollow", "het"),
    "hollen": ("verb", "to run", None),
    "hond": ("noun", "dog", "de"),
    "honderd": ("adjective", "hundred", None),
    "honger": ("noun", "hunger", "de"),
    "hoofd": ("noun", "head", "het"),
    "hoofdstad": ("noun", "capital city", "de"),
    "hoofdstuk": ("noun", "chapter", "het"),
    "hoofdzaak": ("noun", "main thing", "de"),
    "hoog": ("adjective", "high, tall", None),
    "hoogte": ("noun", "height", "de"),
    "hoop": ("noun", "hope; heap", "de"),
    "horen": ("verb", "to hear; to belong", None),
    "horizon": ("noun", "horizon", "de"),
    "horloge": ("noun", "watch", "het"),
    "hotel": ("noun", "hotel", "het"),
    "houden": ("verb", "to hold; to keep; to love", None),
    "houding": ("noun", "attitude, posture", "de"),
    "hout": ("noun", "wood", "het"),
    "huis": ("noun", "house", "het"),
    "huiselijk": ("adjective", "domestic, homely", None),
    "hulp": ("noun", "help", "de"),
    "hulpverlening": ("noun", "assistance, aid", "de"),
    "humeur": ("noun", "mood", "het"),
    "huren": ("verb", "to rent", None),
    "hut": ("noun", "hut; cabin", "de"),
    "huwelijk": ("noun", "marriage", "het"),
    # I
    "ideaal": ("adjective", "ideal", None),
    "idee": ("noun", "idea", "het"),
    "identiteit": ("noun", "identity", "de"),
    "ijs": ("noun", "ice; ice cream", "het"),
    "ijzeren": ("adjective", "iron (made of)", None),
    "illusie": ("noun", "illusion", "de"),
    "immers": ("adjective", "after all", None),
    "indeling": ("noun", "classification, layout", "de"),
    "indruk": ("noun", "impression", "de"),
    "indrukwekkend": ("adjective", "impressive", None),
    "industrie": ("noun", "industry", "de"),
    "industrieel": ("adjective", "industrial", None),
    "informatie": ("noun", "information", "de"),
    "informeren": ("verb", "to inform", None),
    "ingang": ("noun", "entrance", "de"),
    "ingrijpen": ("verb", "to intervene", None),
    "inhoud": ("noun", "content", "de"),
    "inkomen": ("noun", "income", "het"),
    "inleiding": ("noun", "introduction", "de"),
    "inmiddels": ("adjective", "meanwhile", None),
    "inrichten": ("verb", "to furnish; to organize", None),
    "inspanning": ("noun", "effort", "de"),
    "instellen": ("verb", "to set up; to establish", None),
    "instelling": ("noun", "institution; setting", "de"),
    "instituut": ("noun", "institute", "het"),
    "instructie": ("noun", "instruction", "de"),
    "intellectueel": ("adjective", "intellectual", None),
    "intelligent": ("adjective", "intelligent", None),
    "intelligentie": ("noun", "intelligence", "de"),
    "intens": ("adjective", "intense", None),
    "intensief": ("adjective", "intensive", None),
    "interessant": ("adjective", "interesting", None),
    "interesse": ("noun", "interest", "de"),
    "internationaal": ("adjective", "international", None),
    "interpretatie": ("noun", "interpretation", "de"),
    "interpreteren": ("verb", "to interpret", None),
    "interview": ("noun", "interview", "het"),
    "invoeren": ("verb", "to introduce; to import", None),
    "invloed": ("noun", "influence", "de"),
    "inwoner": ("noun", "inhabitant, resident", "de"),
    "inzet": ("noun", "effort; stake", "de"),
    "inzicht": ("noun", "insight", "het"),
    "inzien": ("verb", "to realize; to understand", None),
    # J
    "jaar": ("noun", "year", "het"),
    "jaarlijks": ("adjective", "annual", None),
    "jacht": ("noun", "hunt", "de"),
    "jagen": ("verb", "to hunt", None),
    "jaloers": ("adjective", "jealous", None),
    "jammer": ("adjective", "unfortunate; a pity", None),
    "jarenlang": ("adjective", "for years", None),
    "jasje": ("noun", "jacket", "het"),
    "jeugd": ("noun", "youth", "de"),
    "jong": ("adjective", "young", None),
    "jongen": ("noun", "boy", "de"),
    "jongere": ("noun", "young person", "de"),
    "journalist": ("noun", "journalist", "de"),
    "juist": ("adjective", "correct; precisely", None),
    "juridisch": ("adjective", "legal, juridical", None),
    "justitie": ("noun", "justice", "de"),
    # K
    "kaal": ("adjective", "bald; bare", None),
    "kaart": ("noun", "card; map", "de"),
    "kabinet": ("noun", "cabinet (government)", "het"),
    "kamer": ("noun", "room", "de"),
    "kameraad": ("noun", "comrade", "de"),
    "kamp": ("noun", "camp", "het"),
    "kanaal": ("noun", "channel; canal", "het"),
    "kans": ("noun", "chance, opportunity", "de"),
    "kant": ("noun", "side", "de"),
    "kantoor": ("noun", "office", "het"),
    "kapitaal": ("noun", "capital", "het"),
    "karakter": ("noun", "character", "het"),
    "kasteel": ("noun", "castle", "het"),
    "kat": ("noun", "cat", "de"),
    "keizer": ("noun", "emperor", "de"),
    "kelder": ("noun", "basement, cellar", "de"),
    "kenmerken": ("verb", "to characterize", None),
    "kennen": ("verb", "to know (person/thing)", None),
    "kennis": ("noun", "knowledge; acquaintance", "de"),
    "keren": ("verb", "to turn; to return", None),
    "kerk": ("noun", "church", "de"),
    "kerkelijk": ("adjective", "ecclesiastical", None),
    "kern": ("noun", "core, nucleus", "de"),
    "keuken": ("noun", "kitchen", "de"),
    "keuze": ("noun", "choice", "de"),
    "kijken": ("verb", "to look, to watch", None),
    "kind": ("noun", "child", "het"),
    "klas": ("noun", "class", "de"),
    "klacht": ("noun", "complaint", "de"),
    "klank": ("noun", "sound", "de"),
    "klant": ("noun", "customer", "de"),
    "klap": ("noun", "blow; clap", "de"),
    "klasse": ("noun", "class", "de"),
    "kleden": ("verb", "to dress", None),
    "kleding": ("noun", "clothing", "de"),
    "kleed": ("noun", "rug; garment", "het"),
    "klein": ("adjective", "small", None),
    "kleur": ("noun", "color", "de"),
    "klimaat": ("noun", "climate", "het"),
    "klimmen": ("verb", "to climb", None),
    "klinken": ("verb", "to sound", None),
    "klomp": ("noun", "clog; lump", "de"),
    "klooster": ("noun", "monastery", "het"),
    "kloppen": ("verb", "to knock; to be correct", None),
    "knie": ("noun", "knee", "de"),
    "knoop": ("noun", "button; knot", "de"),
    "koers": ("noun", "course; rate", "de"),
    "koken": ("verb", "to cook; to boil", None),
    "kolonie": ("noun", "colony", "de"),
    "komen": ("verb", "to come", None),
    "koning": ("noun", "king", "de"),
    "koninklijk": ("adjective", "royal", None),
    "koninkrijk": ("noun", "kingdom", "het"),
    "kop": ("noun", "head; cup", "de"),
    "kopen": ("verb", "to buy", None),
    "kopje": ("noun", "small cup", "het"),
    "kort": ("adjective", "short", None),
    "kosten": ("noun", "costs", "de"),
    "koud": ("adjective", "cold", None),
    "kracht": ("noun", "strength, power", "de"),
    "krachtig": ("adjective", "powerful, strong", None),
    "krachtens": ("adjective", "by virtue of", None),
    "krant": ("noun", "newspaper", "de"),
    "krijgen": ("verb", "to get, to receive", None),
    "kritiek": ("noun", "criticism", "de"),
    "kritisch": ("adjective", "critical", None),
    "kroon": ("noun", "crown", "de"),
    "kruipen": ("verb", "to crawl", None),
    "kruis": ("noun", "cross", "het"),
    "kunst": ("noun", "art", "de"),
    "kunstenaar": ("noun", "artist", "de"),
    "kunstmatig": ("adjective", "artificial", None),
    "kust": ("noun", "coast", "de"),
    "kwaad": ("adjective", "angry; evil", None),
    "kwaliteit": ("noun", "quality", "de"),
    "kwartier": ("noun", "quarter (of an hour)", "het"),
    "kwestie": ("noun", "matter, issue", "de"),
}
