WORDS = {
    "aanvaardbaar": ("adjective", "acceptable", None),
    "aanvang": ("noun", "start", "de"),
    "aanvoelen": ("verb", "to sense", None),
    "aanvoeren": ("verb", "to lead", None),
    "aanwenden": ("verb", "to apply", None),
    "aanzet": ("noun", "impulse", "de"),
    "aanzetten": ("verb", "to turn on", None),
    "aap": ("noun", "monkey", "de"),
    "aarzeling": ("noun", "hesitation", "de"),
    "abrupt": ("adjective", "abrupt", None),
    "abstract": ("adjective", "abstract", None),
    "absurd": ("adjective", "absurd", None),
    "academie": ("noun", "academy", "de"),
    "academisch": ("adjective", "academic", None),
    "ach": ("noun", "alas", "de"),
    "achteloos": ("adjective", "careless", None),
    "achten": ("verb", "to consider", None),
    "achterblijven": ("verb", "to stay behind", None),
    "achtergrond": ("noun", "background", "de"),
    "achterhalen": ("verb", "to find out", None),
    "achterkant": ("noun", "back side", "de"),
    "achterlaten": ("verb", "to leave behind", None),
    "achtervolgen": ("verb", "to chase", None),
    "acteur": ("noun", "actor", "de"),
    "actueel": ("adjective", "current", None),
    "acuut": ("adjective", "acute", None),
    "adel": ("noun", "nobility", "de"),
    "ademhaling": ("noun", "breathing", "de"),
    "adequaat": ("adjective", "adequate", None),
    "ader": ("noun", "vein", "de"),
    "administratie": ("noun", "administration", "de"),
    "adolescent": ("noun", "adolescent", "de"),
    "advertentie": ("noun", "advertisement", "de"),
    "adviseren": ("verb", "to advise", None),
    "adviseur": ("noun", "advisor", "de"),
    "afbeelden": ("verb", "to depict", None),
    "afbeelding": ("noun", "image", "de"),
    "afbreken": ("verb", "to break off", None),
    "afdoen": ("verb", "to dismiss", None),
    "affaire": ("noun", "affair", "de"),
    "afgaan": ("verb", "to go off", None),
    "afgevaardigde": ("noun", "delegate", "de"),
    "afgrond": ("noun", "abyss", "de"),
    "afhangen": ("verb", "to depend", None),
    "afkomen": ("verb", "to come from", None),
    "afkomst": ("noun", "origin", "de"),
    "afmaken": ("verb", "to finish", None),
    "afmeting": ("noun", "dimension", "de"),
    "afschaffen": ("verb", "to abolish", None),
    "afsnijden": ("verb", "to cut off", None),
    "afspreken": ("verb", "to agree", None),
    "afstemmen": ("verb", "to tune", None),
    "afval": ("noun", "waste", "het"),
    "afwachten": ("verb", "to wait", None),
    "afwezig": ("adjective", "absent", None),
    "afzetten": ("verb", "to remove", None),
    "agressie": ("noun", "aggression", "de"),
    "akelig": ("adjective", "nasty", None),
    "akker": ("noun", "field", "de"),
    "akkoord": ("noun", "agreement", "het"),
    "akte": ("noun", "deed", "de"),
    "alfabetische": ("adjective", "alphabetical", None),
    "alledaags": ("adjective", "everyday", None),
    "altaar": ("noun", "altar", "het"),
    "ambassade": ("noun", "embassy", "de"),
    "ambassadeur": ("noun", "ambassador", "de"),
    "ambitie": ("noun", "ambition", "de"),
    "ambt": ("noun", "office", "het"),
    "ambtelijk": ("adjective", "official", None),
    "amuseren": ("verb", "to amuse", None),
    "anoniem": ("adjective", "anonymous", None),
    "antiek": ("adjective", "antique", None),
    "apparatuur": ("noun", "equipment", "de"),
    "appartement": ("noun", "apartment", "het"),
    "april": ("noun", "April", "de"),
    "arbeidsmarkt": ("noun", "labor market", "de"),
    "architect": ("noun", "architect", "de"),
    "armoede": ("noun", "poverty", "de"),
    "arresteren": ("verb", "to arrest", None),
    "arriveren": ("verb", "to arrive", None),
    "artistiek": ("adjective", "artistic", None),
    "asbak": ("noun", "ashtray", "de"),
    "assistent": ("noun", "assistant", "de"),
    "atelier": ("noun", "studio", "het"),
    "atmosfeer": ("noun", "atmosphere", "de"),
    "attitude": ("noun", "attitude", "de"),
    "augustus": ("noun", "August", "de"),
    "autonomie": ("noun", "autonomy", "de"),
    "autonoom": ("adjective", "autonomous", None),
    "baai": ("noun", "bay", "de"),
    "baard": ("noun", "beard", "de"),
    "baat": ("noun", "benefit", "de"),
    "babbelen": ("verb", "to chat", None),
    "bacterie": ("noun", "bacterium", "de"),
    "baden": ("verb", "to bathe", None),
    "bagage": ("noun", "luggage", "de"),
    "bak": ("noun", "container", "de"),
    "bakken": ("verb", "to bake", None),
    "bakker": ("noun", "baker", "de"),
    "balans": ("noun", "balance", "de"),
    "balk": ("noun", "beam", "de"),
    "balkon": ("noun", "balcony", "het"),
    "bankier": ("noun", "banker", "de"),
    "baren": ("verb", "to give birth", None),
    "baron": ("noun", "baron", "de"),
    "bedaren": ("verb", "to calm down", None),
    "bedekt": ("adjective", "covered", None),
    "bederven": ("verb", "to spoil", None),
    "bediende": ("noun", "servant", "de"),
    "bedrijfsleven": ("noun", "business world", "het"),
    "bedrog": ("noun", "deceit", "het"),
    "bedwingen": ("verb", "to restrain", None),
    "beek": ("noun", "brook", "de"),
    "beer": ("noun", "bear", "de"),
    "begaafd": ("adjective", "gifted", None),
    "begaan": ("verb", "to commit", None),
    "begeerte": ("noun", "desire", "de"),
    "begeleiding": ("noun", "guidance", "de"),
    "begeren": ("verb", "to desire", None),
    "beginselen": ("noun", "principles", "de"),
    "begrepen": ("verb", "to understand", None),
    "behalen": ("verb", "to achieve", None),
    "beheer": ("noun", "management", "het"),
    "beheerst": ("adjective", "controlled", None),
    "behoedzaam": ("adjective", "cautious", None),
    "behoeven": ("verb", "to need", None),
    "behoud": ("noun", "preservation", "het"),
    "bek": ("noun", "mouth", "de"),
    "beker": ("noun", "cup", "de"),
    "beklagen": ("verb", "to complain", None),
    "bekleden": ("verb", "to occupy", None),
    "beklimmen": ("verb", "to climb", None),
    "bekommeren": ("verb", "to worry", None),
    "bekwaam": ("adjective", "competent", None),
    "belanden": ("verb", "to end up", None),
    "belasten": ("verb", "to tax", None),
    "beledigen": ("verb", "to insult", None),
    "beleefd": ("adjective", "polite", None),
    "belemmeren": ("verb", "to hinder", None),
    "beletten": ("verb", "to prevent", None),
    "belonen": ("verb", "to reward", None),
    "beloning": ("noun", "reward", "de"),
    "bemerken": ("verb", "to notice", None),
    "benadrukken": ("verb", "to emphasize", None),
    "benaming": ("noun", "designation", "de"),
    "bende": ("noun", "gang", "de"),
    "benodigd": ("adjective", "required", None),
    "benoeming": ("noun", "appointment", "de"),
    "benutten": ("verb", "to utilize", None),
    "beoefenen": ("verb", "to practice", None),
    "beogen": ("verb", "to aim at", None),
    "bepleiten": ("verb", "to advocate", None),
    "bereik": ("noun", "range", "het"),
    "berekenen": ("verb", "to calculate", None),
    "berekening": ("noun", "calculation", "de"),
    "bergen": ("verb", "to store", None),
    "beroepen": ("verb", "to appeal", None),
    "beroven": ("verb", "to rob", None),
    "berucht": ("adjective", "notorious", None),
    "beschuldigen": ("verb", "to accuse", None),
    "beschuldiging": ("noun", "accusation", "de"),
    "beslissend": ("adjective", "decisive", None),
    "besluitvorming": ("noun", "decision-making", "de"),
    "besparen": ("verb", "to save", None),
    "bespeuren": ("verb", "to detect", None),
    "bestand": ("noun", "file", "het"),
    "bestanddeel": ("noun", "component", "het"),
    "bestel": ("noun", "system", "het"),
    "bestemming": ("noun", "destination", "de"),
    "bestemmingsplan": ("noun", "zoning plan", "het"),
    "besturen": ("verb", "to govern", None),
    "bestuurder": ("noun", "driver", "de"),
    "betogen": ("verb", "to argue", None),
    "betoog": ("noun", "argument", "het"),
    "betrappen": ("verb", "to catch", None),
    "betreden": ("verb", "to enter", None),
    "betreuren": ("verb", "to regret", None),
    "betwijfelen": ("verb", "to doubt", None),
    "bevinding": ("noun", "finding", "de"),
    "bevoegd": ("adjective", "authorized", None),
    "bevriend": ("adjective", "befriended", None),
    "bevriezen": ("verb", "to freeze", None),
    "bewaken": ("verb", "to guard", None),
    "bewering": ("noun", "claim", "de"),
    "bewerken": ("verb", "to edit", None),
    "bewerkstelligen": ("verb", "to accomplish", None),
    "bewind": ("noun", "rule", "het"),
    "bewogen": ("adjective", "moved", None),
    "bewonen": ("verb", "to inhabit", None),
    "bezet": ("adjective", "occupied", None),
    "bezetten": ("verb", "to occupy", None),
    "bezetting": ("noun", "occupation", "de"),
    "bezigheid": ("noun", "activity", "de"),
    "bezitting": ("noun", "possession", "de"),
    "bezweren": ("verb", "to swear", None),
    "beëindigen": ("verb", "to terminate", None),
    "beïnvloeden": ("verb", "to influence", None),
    "bijkomen": ("verb", "to recover", None),
    "bijzonderheid": ("noun", "detail", "de"),
    "bil": ("noun", "buttock", "de"),
    "binnendringen": ("verb", "to intrude", None),
    "binnenkant": ("noun", "inside", "de"),
    "binnenkomen": ("verb", "to enter", None),
    "binnenlands": ("adjective", "domestic", None),
    "binnenplaats": ("noun", "courtyard", "de"),
    "bioscoop": ("noun", "cinema", "de"),
    "bladeren": ("verb", "to browse", None),
    "blaffen": ("verb", "to bark", None),
    "blijk": ("noun", "sign", "het"),
    "blijkens": ("adjective", "according to", None),
    "blijvend": ("adjective", "lasting", None),
    "bliksem": ("noun", "lightning", "de"),
    "blinken": ("verb", "to shine", None),
    "bloeden": ("verb", "to bleed", None),
    "bloei": ("noun", "bloom", "de"),
    "blozen": ("verb", "to blush", None),
    "bobby": ("noun", "bobby", "de"),
    "boeiend": ("adjective", "fascinating", None),
    "boeken": ("verb", "to book", None),
    "boerin": ("noun", "farmer's wife", "de"),
    "bol": ("noun", "sphere", "de"),
    "bom": ("noun", "bomb", "de"),
    "bond": ("noun", "union", "de"),
    "bonken": ("verb", "to thump", None),
    "bont": ("adjective", "colorful", None),
    "bonzen": ("verb", "to pound", None),
    "boon": ("noun", "bean", "de"),
    "boren": ("verb", "to drill", None),
    "borrel": ("noun", "drink", "de"),
    "bot": ("adjective", "blunt", None),
    "boterham": ("noun", "sandwich", "de"),
    "botsen": ("verb", "to collide", None),
    "botsing": ("noun", "collision", "de"),
    "bouw": ("noun", "construction", "de"),
    "bouwwerk": ("noun", "structure", "het"),
    "bovengenoemd": ("adjective", "above-mentioned", None),
    "bovenop": ("adjective", "on top", None),
    "bovenstaand": ("adjective", "above", None),
    "boze": ("adjective", "angry", None),
    "breien": ("verb", "to knit", None),
    "brein": ("noun", "brain", "het"),
    "breuk": ("noun", "fracture", "de"),
    "briljant": ("adjective", "brilliant", None),
    "brok": ("noun", "chunk", "de"),
    "brommen": ("verb", "to grumble", None),
    "brouwerij": ("noun", "brewery", "de"),
    "bruikbaar": ("adjective", "usable", None),
    "brutaal": ("adjective", "rude", None),
    "bui": ("noun", "shower", "de"),
    "buit": ("noun", "loot", "de"),
    "buitenaf": ("adjective", "from outside", None),
    "buitengewoon": ("adjective", "extraordinary", None),
    "buitenland": ("noun", "abroad", "het"),
    "buitenlander": ("noun", "foreigner", "de"),
    "buitenlands": ("adjective", "foreign", None),
    "buitenstaander": ("noun", "outsider", "de"),
    "buitenwereld": ("noun", "outside world", "de"),
    "bukken": ("verb", "to duck", None),
    "buurman": ("noun", "neighbor", "de"),
    "cabine": ("noun", "cabin", "de"),
    "cadeau": ("noun", "gift", "het"),
    "cadet": ("noun", "cadet", "de"),
    "café": ("noun", "cafe", "het"),
    "camera": ("noun", "camera", "de"),
    "capaciteit": ("noun", "capacity", "de"),
    "carrière": ("noun", "career", "de"),
    "casino": ("noun", "casino", "het"),
    "chaos": ("noun", "chaos", "de"),
    "charmant": ("adjective", "charming", None),
    "charme": ("noun", "charm", "de"),
    "chip": ("noun", "chip", "de"),
    "christus": ("noun", "Christ", "de"),
    "chronisch": ("adjective", "chronic", None),
    "citaat": ("noun", "quote", "het"),
    "citroen": ("noun", "lemon", "de"),
    "cliënt": ("noun", "client", "de"),
    "club": ("noun", "club", "de"),
    "code": ("noun", "code", "de"),
    "cognac": ("noun", "cognac", "de"),
    "cognitief": ("adjective", "cognitive", None),
    "collectie": ("noun", "collection", "de"),
    "collega": ("noun", "colleague", "de"),
    "combineren": ("verb", "to combine", None),
    "comité": ("noun", "committee", "het"),
    "commercieel": ("adjective", "commercial", None),
    "communisme": ("noun", "communism", "het"),
    "communist": ("noun", "communist", "de"),
    "compagnie": ("noun", "company", "de"),
    "complex": ("noun", "complex", "het"),
    "compliment": ("noun", "compliment", "het"),
    "component": ("noun", "component", "de"),
    "componist": ("noun", "composer", "de"),
    "compromis": ("noun", "compromise", "het"),
    "concentratie": ("noun", "concentration", "de"),
    "concept": ("noun", "concept", "het"),
    "conceptie": ("noun", "conception", "de"),
    "concert": ("noun", "concert", "het"),
    "concilie": ("noun", "council", "het"),
    "concurrentie": ("noun", "competition", "de"),
    "conditie": ("noun", "condition", "de"),
    "conferentie": ("noun", "conference", "de"),
    "confrontatie": ("noun", "confrontation", "de"),
    "congres": ("noun", "congress", "het"),
    "consequent": ("adjective", "consistent", None),
    "conservatief": ("adjective", "conservative", None),
    "constant": ("adjective", "constant", None),
    "constructie": ("noun", "construction", "de"),
    "construeren": ("verb", "to construct", None),
    "consumptie": ("noun", "consumption", "de"),
    "context": ("noun", "context", "de"),
    "continent": ("noun", "continent", "het"),
    "contract": ("noun", "contract", "het"),
    "contrast": ("noun", "contrast", "het"),
    "correct": ("adjective", "correct", None),
    "corrigeren": ("verb", "to correct", None),
    "coöperatie": ("noun", "cooperation", "de"),
    "coördinatie": ("noun", "coordination", "de"),
    "creatief": ("adjective", "creative", None),
    "creëren": ("verb", "to create", None),
    "cursus": ("noun", "course", "de"),
    "daadwerkelijk": ("adjective", "actual", None),
    "daags": ("adjective", "daily", None),
    "dader": ("noun", "perpetrator", "de"),
    "dagblad": ("noun", "newspaper", "het"),
    "daglicht": ("noun", "daylight", "het"),
    "dans": ("noun", "dance", "de"),
    "dapper": ("adjective", "brave", None),
    "darm": ("noun", "intestine", "de"),
    "dateren": ("verb", "to date", None),
    "datum": ("noun", "date", "de"),
    "debat": ("noun", "debate", "het"),
    "december": ("noun", "December", "de"),
    "decennium": ("noun", "decade", "het"),
    "deels": ("adjective", "partly", None),
    "definiëren": ("verb", "to define", None),
    "deftig": ("adjective", "dignified", None),
    "dek": ("noun", "deck", "het"),
    "deksel": ("noun", "lid", "het"),
    "delegatie": ("noun", "delegation", "de"),
    "delven": ("verb", "to dig", None),
    "demonstratie": ("noun", "demonstration", "de"),
    "demonstreren": ("verb", "to demonstrate", None),
    "dempen": ("verb", "to dampen", None),
    "denkbeeldig": ("adjective", "imaginary", None),
    "departement": ("noun", "department", "het"),
    "depressie": ("noun", "depression", "de"),
    "deskundig": ("adjective", "expert", None),
    "deugd": ("noun", "virtue", "de"),
    "deugen": ("verb", "to be good", None),
    "deuropening": ("noun", "doorway", "de"),
    "dialoog": ("noun", "dialogue", "de"),
    "dictatuur": ("noun", "dictatorship", "de"),
    "dieet": ("noun", "diet", "het"),
    "dief": ("noun", "thief", "de"),
    "dienstverlening": ("noun", "service", "de"),
    "dierenarts": ("noun", "veterinarian", "de"),
    "diner": ("noun", "dinner", "het"),
    "discipline": ("noun", "discipline", "de"),
    "district": ("noun", "district", "het"),
    "docent": ("noun", "teacher", "de"),
    "doelen": ("verb", "to aim", None),
    "doeltreffend": ("adjective", "effective", None),
    "dof": ("adjective", "dull", None),
    "domein": ("noun", "domain", "het"),
    "dominee": ("noun", "minister", "de"),
    "domineren": ("verb", "to dominate", None),
    "donder": ("noun", "thunder", "de"),
    "donderen": ("verb", "to thunder", None),
    "doodgaan": ("verb", "to die", None),
    "doodstil": ("adjective", "dead silent", None),
    "doorgeven": ("verb", "to pass on", None),
    "doormaken": ("verb", "to go through", None),
    "doorstaan": ("verb", "to endure", None),
    "doorzichtig": ("adjective", "transparent", None),
    "dopen": ("verb", "to baptize", None),
    "dorst": ("noun", "thirst", "de"),
    "dosis": ("noun", "dose", "de"),
    "dossier": ("noun", "dossier", "het"),
    "douche": ("noun", "shower", "de"),
    "doven": ("verb", "to extinguish", None),
    "dozijn": ("noun", "dozen", "het"),
    "drama": ("noun", "drama", "het"),
    "dramatisch": ("adjective", "dramatic", None),
    "drang": ("noun", "urge", "de"),
    "dreiging": ("noun", "threat", "de"),
    "drempel": ("noun", "threshold", "de"),
    "dreunen": ("verb", "to rumble", None),
    "drift": ("noun", "temper", "de"),
    "driftig": ("adjective", "hot-tempered", None),
    "drijven": ("verb", "to float", None),
    "dringend": ("adjective", "urgent", None),
    "droevig": ("adjective", "sad", None),
    "dromer": ("noun", "dreamer", "de"),
    "drug": ("noun", "drug", "de"),
    "druipen": ("verb", "to drip", None),
    "drukte": ("noun", "bustle", "de"),
    "dubbel": ("adjective", "double", None),
    "duif": ("noun", "pigeon", "de"),
    "duiken": ("verb", "to dive", None),
    "duin": ("noun", "dune", "het"),
    "duivel": ("noun", "devil", "de"),
    "dulden": ("verb", "to tolerate", None),
    "dun": ("adjective", "thin", None),
    "dunne": ("adjective", "thin", None),
    "duwen": ("verb", "to push", None),
    "dwaas": ("adjective", "foolish", None),
    "dwalen": ("verb", "to wander", None),
    "dwang": ("noun", "coercion", "de"),
    "dwars": ("adjective", "cross", None),
}
