WORDS = {
    "laars": ("noun", "boot", "de"),
    "laboratorium": ("noun", "laboratory", "het"),
    "ladder": ("noun", "ladder", "de"),
    "lading": ("noun", "cargo; charge", "de"),
    "lady": ("noun", "lady", "de"),
    "laken": ("noun", "sheet; cloth", "het"),
    "lamp": ("noun", "lamp", "de"),
    "lanceren": ("verb", "to launch", None),
    "landbouw": ("noun", "agriculture", "de"),
    "landschap": ("noun", "landscape", "het"),
    "langdurig": ("adjective", "prolonged", None),
    "lastig": ("adjective", "difficult; annoying", None),
    "latijn": ("noun", "Latin", "het"),
    "lauw": ("adjective", "lukewarm", None),
    "lawaai": ("noun", "noise", "het"),
    "leeg": ("adjective", "empty", None),
    "leegte": ("noun", "emptiness", "de"),
    "leek": ("noun", "layperson", "de"),
    "legende": ("noun", "legend", "de"),
    "lekker": ("adjective", "tasty; nice", None),
    "lenen": ("verb", "to lend; to borrow", None),
    "lente": ("noun", "spring", "de"),
    "lepel": ("noun", "spoon", "de"),
    "leraar": ("noun", "teacher", "de"),
    "letten": ("verb", "to pay attention", None),
    "leugen": ("noun", "lie", "de"),
    "levendig": ("adjective", "lively", None),
    "lever": ("noun", "liver", "de"),
    "leverancier": ("noun", "supplier", "de"),
    "lezing": ("noun", "lecture; reading", "de"),
    "lichten": ("verb", "to light; to lift", None),
    "lied": ("noun", "song", "het"),
    "lieden": ("noun", "people", "de"),
    "liefhebben": ("verb", "to love", None),
    "liefje": ("noun", "sweetheart", "het"),
    "liegen": ("verb", "to lie", None),
    "lies": ("noun", "groin", "de"),
    "lift": ("noun", "elevator", "de"),
    "likken": ("verb", "to lick", None),
    "linker": ("adjective", "left", None),
    "linkerhand": ("noun", "left hand", "de"),
    "liter": ("noun", "liter", "de"),
    "literair": ("adjective", "literary", None),
    "litteken": ("noun", "scar", "het"),
    "loeien": ("verb", "to moo", None),
    "loeren": ("verb", "to lurk; to peep", None),
    "logeren": ("verb", "to stay as guest", None),
    "logica": ("noun", "logic", "de"),
    "lokken": ("verb", "to lure", None),
    "long": ("noun", "lung", "de"),
    "lopend": ("adjective", "running; current", None),
    "losmaken": ("verb", "to loosen; to detach", None),
    "lossen": ("verb", "to unload; to solve", None),
    "louter": ("adjective", "mere; pure", None),
    "luchten": ("verb", "to air out", None),
    "luchtig": ("adjective", "airy; light", None),
    "lucifer": ("noun", "match", "de"),
    "luid": ("adjective", "loud", None),
    "luidruchtig": ("adjective", "noisy", None),
    "luik": ("noun", "shutter; hatch", "het"),
    "luitenant": ("noun", "lieutenant", "de"),
    "lunch": ("noun", "lunch", "de"),
    "luxe": ("noun", "luxury", "de"),
    "maag": ("noun", "stomach", "de"),
    "maagd": ("noun", "virgin", "de"),
    "maaltijd": ("noun", "meal", "de"),
    "maan": ("noun", "moon", "de"),
    "maart": ("noun", "March", "de"),
    "maat": ("noun", "measure; size; mate", "de"),
    "maatschappelijk": ("adjective", "social", None),
    "maatschappij": ("noun", "society", "de"),
    "maatstaf": ("noun", "standard; criterion", "de"),
    "machine": ("noun", "machine", "de"),
    "machteloos": ("adjective", "powerless", None),
    "madame": ("noun", "madam", "de"),
    "magie": ("noun", "magic", "de"),
    "magisch": ("adjective", "magical", None),
    "majesteit": ("noun", "majesty", "de"),
    "majoor": ("noun", "major", "de"),
    "makkelijk": ("adjective", "easy", None),
    "malen": ("verb", "to grind", None),
    "mama": ("noun", "mom", "de"),
    "mand": ("noun", "basket", "de"),
    "manieren": ("noun", "manners", "de"),
    "manifesteren": ("verb", "to manifest", None),
    "mankeren": ("verb", "to be wrong with", None),
    "mannelijk": ("adjective", "masculine", None),
    "mannetje": ("noun", "little man", "het"),
    "mantel": ("noun", "coat; cloak", "de"),
    "manuscript": ("noun", "manuscript", "het"),
    "marcheren": ("verb", "to march", None),
    "markt": ("noun", "market", "de"),
    "marxisme": ("noun", "Marxism", "het"),
    "marxistisch": ("adjective", "Marxist", None),
    "masker": ("noun", "mask", "het"),
    "massaal": ("adjective", "massive; mass", None),
    "massief": ("adjective", "massive; solid", None),
    "mate": ("noun", "degree; extent", "de"),
    "materie": ("noun", "matter", "de"),
    "materieel": ("adjective", "material", None),
    "matras": ("noun", "mattress", "de"),
    "matroos": ("noun", "sailor", "de"),
    "maximaal": ("adjective", "maximum", None),
    "mechanisch": ("adjective", "mechanical", None),
    "medelijden": ("noun", "compassion", "het"),
    "medemens": ("noun", "fellow human", "de"),
    "media": ("noun", "media", "de"),
    "medisch": ("adjective", "medical", None),
    "medium": ("noun", "medium", "het"),
    "meebrengen": ("verb", "to bring along", None),
    "meedelen": ("verb", "to inform; to share", None),
    "meedogenloos": ("adjective", "merciless", None),
    "meegaan": ("verb", "to go along", None),
    "meemaken": ("verb", "to experience", None),
    "meer": ("noun", "lake", "het"),
    "meerdere": ("adjective", "several; superior", None),
    "meeslepen": ("verb", "to drag along", None),
    "mei": ("noun", "May", "de"),
    "meid": ("noun", "girl; maid", "de"),
    "melding": ("noun", "report; notification", "de"),
    "melodie": ("noun", "melody", "de"),
    "meneer": ("noun", "mister", "de"),
    "menen": ("verb", "to mean; to believe", None),
    "mengsel": ("noun", "mixture", "het"),
    "menig": ("adjective", "many a", None),
    "menigte": ("noun", "crowd", "de"),
    "mensheid": ("noun", "humanity", "de"),
    "mentaal": ("adjective", "mental", None),
    "mentaliteit": ("noun", "mentality", "de"),
    "merendeel": ("noun", "majority", "het"),
    "merk": ("noun", "brand", "het"),
    "merkwaardig": ("adjective", "remarkable", None),
    "metaal": ("noun", "metal", "het"),
    "meter": ("noun", "meter", "de"),
    "meubel": ("noun", "piece of furniture", "het"),
    "mevrouw": ("noun", "madam", "de"),
    "middelbaar": ("adjective", "secondary; average", None),
    "middeleeuwen": ("noun", "Middle Ages", "de"),
    "middeleeuws": ("adjective", "medieval", None),
    "middelen": ("noun", "means; resources", "de"),
    "middelpunt": ("noun", "center point", "het"),
    "middernacht": ("noun", "midnight", "de"),
    "mijl": ("noun", "mile", "de"),
    "mijnheer": ("noun", "sir", "de"),
    "mild": ("adjective", "mild; generous", None),
    "minderheid": ("noun", "minority", "de"),
    "minimaal": ("adjective", "minimal", None),
    "minimum": ("noun", "minimum", "het"),
    "minnaar": ("noun", "lover", "de"),
    "minuut": ("noun", "minute", "de"),
    "misbruik": ("noun", "abuse", "het"),
    "misdaad": ("noun", "crime", "de"),
    "misdadiger": ("noun", "criminal", "de"),
    "misleiden": ("verb", "to mislead", None),
    "mislukken": ("verb", "to fail", None),
    "mislukking": ("noun", "failure", "de"),
    "miss": ("noun", "miss", "de"),
    "misselijk": ("adjective", "nauseous", None),
    "missen": ("verb", "to miss", None),
    "missie": ("noun", "mission", "de"),
    "mist": ("noun", "fog", "de"),
    "misverstand": ("noun", "misunderstanding", "het"),
    "modder": ("noun", "mud", "de"),
    "mode": ("noun", "fashion", "de"),
    "model": ("noun", "model", "het"),
    "moe": ("adjective", "tired", None),
    "moed": ("noun", "courage", "de"),
    "moedig": ("adjective", "brave", None),
    "moeizaam": ("adjective", "laborious", None),
    "moeras": ("noun", "swamp", "het"),
    "momenteel": ("adjective", "current", None),
    "mompelen": ("verb", "to mumble", None),
    "monnik": ("noun", "monk", "de"),
    "monsieur": ("noun", "sir", "de"),
    "monster": ("noun", "monster; sample", "het"),
    "monument": ("noun", "monument", "het"),
    "moordenaar": ("noun", "murderer", "de"),
    "mopperen": ("verb", "to grumble", None),
    "motief": ("noun", "motive", "het"),
    "motivatie": ("noun", "motivation", "de"),
    "muis": ("noun", "mouse", "de"),
    "mus": ("noun", "sparrow", "de"),
    "museum": ("noun", "museum", "het"),
    "muzikaal": ("adjective", "musical", None),
    "mysterie": ("noun", "mystery", "het"),
    "mysterieus": ("adjective", "mysterious", None),
    "mystiek": ("noun", "mysticism", "de"),
    "mythe": ("noun", "myth", "de"),
    "naakt": ("adjective", "naked", None),
    "naald": ("noun", "needle", "de"),
    "naast": ("adjective", "next to; nearest", None),
    "nabij": ("adjective", "nearby", None),
    "nabijheid": ("noun", "proximity", "de"),
    "nachtelijk": ("adjective", "nocturnal", None),
    "nachtmerrie": ("noun", "nightmare", "de"),
    "nadeel": ("noun", "disadvantage", "het"),
    "nadenken": ("verb", "to think about", None),
    "naderen": ("verb", "to approach", None),
    "nadrukkelijk": ("adjective", "emphatic", None),
    "nagel": ("noun", "nail", "de"),
    "namiddag": ("noun", "afternoon", "de"),
    "nastreven": ("verb", "to pursue", None),
    "nat": ("adjective", "wet", None),
    "natie": ("noun", "nation", "de"),
    "nationaal": ("adjective", "national", None),
    "naïef": ("adjective", "naive", None),
    "nederlaag": ("noun", "defeat", "de"),
    "nederlands": ("adjective", "Dutch", None),
    "neef": ("noun", "cousin; nephew", "de"),
    "neerkomen": ("verb", "to come down", None),
    "neerzetten": ("verb", "to put down", None),
    "neger": ("noun", "Black person", "de"),
    "negeren": ("verb", "to ignore", None),
    "neigen": ("verb", "to tend; to lean", None),
    "nek": ("noun", "neck", "de"),
    "nerveus": ("adjective", "nervous", None),
    "nest": ("noun", "nest", "het"),
    "nestelen": ("verb", "to nestle", None),
    "netjes": ("adjective", "neat; tidy", None),
    "netwerk": ("noun", "network", "het"),
    "neuken": ("verb", "to fuck", None),
    "nevel": ("noun", "mist; haze", "de"),
    "nicht": ("noun", "niece; female cousin", "de"),
    "nier": ("noun", "kidney", "de"),
    "nieuwsgierig": ("adjective", "curious", None),
    "nijdig": ("adjective", "angry", None),
    "nodigen": ("verb", "to invite", None),
    "non": ("noun", "nun", "de"),
    "noodlot": ("noun", "fate", "het"),
    "noordelijk": ("adjective", "northern", None),
    "noorden": ("noun", "north", "het"),
    "noot": ("noun", "note; nut", "de"),
    "nors": ("adjective", "gruff; surly", None),
    "notaris": ("noun", "notary", "de"),
    "noteren": ("verb", "to note down", None),
    "november": ("noun", "November", "de"),
    "nuchter": ("adjective", "sober; sensible", None),
    "nutteloos": ("adjective", "useless", None),
    "ober": ("noun", "waiter", "de"),
    "object": ("noun", "object", "het"),
    "objectief": ("adjective", "objective", None),
    "observatie": ("noun", "observation", "de"),
    "observeren": ("verb", "to observe", None),
    "oceaan": ("noun", "ocean", "de"),
    "offeren": ("verb", "to sacrifice", None),
    "ogenblik": ("noun", "moment", "het"),
    "oktober": ("noun", "October", "de"),
    "olie": ("noun", "oil", "de"),
    "oma": ("noun", "grandmother", "de"),
    "omdraaien": ("verb", "to turn around", None),
    "omgaan": ("verb", "to deal with", None),
    "omgekeerd": ("adjective", "reversed", None),
    "omgeven": ("verb", "to surround", None),
    "omhelzen": ("verb", "to embrace", None),
    "omkeren": ("verb", "to turn around; to reverse", None),
    "omringen": ("verb", "to surround", None),
    "omroep": ("noun", "broadcasting", "de"),
    "omschrijven": ("verb", "to describe", None),
    "omschrijving": ("noun", "description", "de"),
    "omvangrijk": ("adjective", "extensive", None),
    "omweg": ("noun", "detour", "de"),
    "onafgebroken": ("adjective", "uninterrupted", None),
    "onbeweeglijk": ("adjective", "motionless", None),
    "onderbreken": ("verb", "to interrupt", None),
    "onderbrengen": ("verb", "to accommodate", None),
    "onderdak": ("noun", "shelter", "het"),
    "onderdrukken": ("verb", "to suppress", None),
    "ondergaan": ("verb", "to undergo", None),
    "ondergeschikt": ("adjective", "subordinate", None),
    "ondergrond": ("noun", "underground; subsoil", "de"),
    "ondergronds": ("adjective", "underground", None),
    "onderhandelen": ("verb", "to negotiate", None),
    "onderhandeling": ("noun", "negotiation", "de"),
    "onderhoud": ("noun", "maintenance", "het"),
    "onderkennen": ("verb", "to recognize", None),
    "onderling": ("adjective", "mutual", None),
    "onderschatten": ("verb", "to underestimate", None),
    "onderscheiding": ("noun", "distinction", "de"),
    "ondertekenen": ("verb", "to sign", None),
    "ondervinden": ("verb", "to experience", None),
    "ondervragen": ("verb", "to interrogate", None),
    "onderwerpen": ("verb", "to subject", None),
    "onderwijskundig": ("adjective", "educational", None),
    "oneindig": ("adjective", "infinite", None),
    "ongelijk": ("noun", "wrong; inequality", "het"),
    "ongelovig": ("adjective", "incredulous", None),
    "ongelukkig": ("adjective", "unhappy", None),
    "ongemerkt": ("adjective", "unnoticed", None),
    "ongewenst": ("adjective", "unwanted", None),
    "onherroepelijk": ("adjective", "irrevocable", None),
    "onmacht": ("noun", "powerlessness", "de"),
    "onmisbaar": ("adjective", "indispensable", None),
    "onmiskenbaar": ("adjective", "unmistakable", None),
    "onnodig": ("adjective", "unnecessary", None),
    "onnozel": ("adjective", "foolish; silly", None),
    "onophoudelijk": ("adjective", "incessant", None),
    "onrustig": ("adjective", "restless", None),
    "ontbijt": ("noun", "breakfast", "het"),
    "ontdoen": ("verb", "to rid of", None),
    "ontelbaar": ("adjective", "countless", None),
    "ontgaan": ("verb", "to escape notice", None),
    "onthouden": ("verb", "to remember", None),
    "onthullen": ("verb", "to reveal", None),
    "ontkomen": ("verb", "to escape", None),
    "ontlenen": ("verb", "to derive; to borrow", None),
    "ontplooien": ("verb", "to develop; to unfold", None),
    "ontroeren": ("verb", "to move emotionally", None),
    "ontspannen": ("verb", "to relax", None),
    "ontspanning": ("noun", "relaxation", "de"),
    "ontsteking": ("noun", "inflammation; ignition", "de"),
    "onttrekken": ("verb", "to withdraw", None),
    "ontwaken": ("verb", "to awaken", None),
    "ontwijken": ("verb", "to evade", None),
    "ontwikkeld": ("adjective", "developed; educated", None),
    "ontzetten": ("verb", "to horrify", None),
    "ontzettend": ("adjective", "tremendous", None),
    "onvermijdelijk": ("adjective", "inevitable", None),
    "onverschillig": ("adjective", "indifferent", None),
    "onverwacht": ("adjective", "unexpected", None),
    "onwillekeurig": ("adjective", "involuntary", None),
    "onzichtbaar": ("adjective", "invisible", None),
    "onzin": ("noun", "nonsense", "de"),
    "ooglid": ("noun", "eyelid", "het"),
    "oogpunt": ("noun", "point of view", "het"),
    "oogst": ("noun", "harvest", "de"),
    "oorsprong": ("noun", "origin", "de"),
    "oorspronkelijk": ("adjective", "original", None),
    "oostelijk": ("adjective", "eastern", None),
    "oosten": ("noun", "east", "het"),
    "oosters": ("adjective", "oriental; eastern", None),
    "opa": ("noun", "grandfather", "de"),
    "opbellen": ("verb", "to call up", None),
    "opbergen": ("verb", "to store; to put away", None),
    "opbouw": ("noun", "construction; structure", "de"),
    "opbrengen": ("verb", "to yield", None),
    "opbrengst": ("noun", "yield; revenue", "de"),
    "opdoen": ("verb", "to gain", None),
    "opdragen": ("verb", "to dedicate; to assign", None),
    "opdringen": ("verb", "to impose; to force upon", None),
    "opduiken": ("verb", "to surface; to turn up", None),
    "openbaren": ("verb", "to reveal", None),
    "openbaring": ("noun", "revelation", "de"),
    "opendoen": ("verb", "to open the door", None),
    "openlijk": ("adjective", "open; public", None),
    "openstaan": ("verb", "to be open", None),
    "opereren": ("verb", "to operate", None),
    "opeten": ("verb", "to eat up", None),
    "opgaan": ("verb", "to rise; to be absorbed", None),
    "opgave": ("noun", "task; assignment", "de"),
    "opgeven": ("verb", "to give up", None),
    "opgewekt": ("adjective", "cheerful", None),
    "opgewonden": ("adjective", "excited", None),
    "opgroeien": ("verb", "to grow up", None),
    "ophalen": ("verb", "to pick up; to collect", None),
    "ophangen": ("verb", "to hang up", None),
    "opinie": ("noun", "opinion", "de"),
    "opkijken": ("verb", "to look up", None),
    "opkomst": ("noun", "rise; turnout", "de"),
    "opleveren": ("verb", "to deliver; to yield", None),
    "oplopen": ("verb", "to walk up; to increase", None),
    "opluchten": ("verb", "to relieve", None),
    "opluchting": ("noun", "relief", "de"),
    "opmaken": ("verb", "to use up; to make up", None),
    "opname": ("noun", "recording; admission", "de"),
    "oppassen": ("verb", "to watch out; to babysit", None),
    "opperen": ("verb", "to suggest", None),
    "oppervlakkig": ("adjective", "superficial", None),
    "oppervlakte": ("noun", "surface; area", "de"),
    "oppositie": ("noun", "opposition", "de"),
    "oprecht": ("adjective", "sincere", None),
    "opschieten": ("verb", "to hurry up", None),
    "opschrijven": ("verb", "to write down", None),
    "opslaan": ("verb", "to store; to save", None),
    "opsluiten": ("verb", "to lock up", None),
    "opstaan": ("verb", "to stand up; to get up", None),
    "opsteken": ("verb", "to pick up; to light", None),
    "opstel": ("noun", "essay", "het"),
    "opstelling": ("noun", "lineup; arrangement", "de"),
    "opstijgen": ("verb", "to ascend; to take off", None),
    "optimaal": ("adjective", "optimal", None),
    "optrekken": ("verb", "to pull up", None),
    "opvangen": ("verb", "to catch; to absorb", None),
    "opvoeren": ("verb", "to increase; to perform", None),
    "opvolgen": ("verb", "to succeed; to follow up", None),
    "opvolger": ("noun", "successor", "de"),
    "opwekken": ("verb", "to arouse; to generate", None),
    "opwinden": ("verb", "to excite; to wind up", None),
    "opwinding": ("noun", "excitement", "de"),
    "opzet": ("noun", "intention; design", "het"),
    "opzettelijk": ("adjective", "deliberate", None),
    "opzoeken": ("verb", "to look up; to visit", None),
    "ordening": ("noun", "arrangement; ordering", "de"),
    "order": ("noun", "order", "de"),
    "organisch": ("adjective", "organic", None),
    "organisme": ("noun", "organism", "het"),
    "orgasme": ("noun", "orgasm", "het"),
    "origineel": ("adjective", "original", None),
    "oriëntatie": ("noun", "orientation", "de"),
    "oriënteren": ("verb", "to orient", None),
    "orkest": ("noun", "orchestra", "het"),
    "ouderdom": ("noun", "old age", "de"),
    "ouderen": ("noun", "elderly people", "de"),
    "ouderlijk": ("adjective", "parental", None),
    "ouderwets": ("adjective", "old-fashioned", None),
    "oudheid": ("noun", "antiquity", "de"),
    "oven": ("noun", "oven", "de"),
    "overblijven": ("verb", "to remain", None),
    "overbodig": ("adjective", "superfluous", None),
    "overbrengen": ("verb", "to convey; to transfer", None),
    "overdracht": ("noun", "transfer", "de"),
    "overdragen": ("verb", "to transfer", None),
    "overdreven": ("adjective", "exaggerated", None),
    "overdrijven": ("verb", "to exaggerate", None),
    "overeenkomen": ("verb", "to agree", None),
    "overeenkomst": ("noun", "agreement", "de"),
    "overeenkomstig": ("adjective", "corresponding", None),
    "overeenstemming": ("noun", "agreement; consensus", "de"),
    "overgaan": ("verb", "to pass over", None),
    "overgang": ("noun", "transition", "de"),
    "overgave": ("noun", "surrender", "de"),
    "overgeven": ("verb", "to surrender; to vomit", None),
    "overhandigen": ("verb", "to hand over", None),
    "overheersen": ("verb", "to dominate", None),
    "overhemd": ("noun", "shirt", "het"),
    "overkant": ("noun", "other side", "de"),
    "overkomen": ("verb", "to happen to", None),
    "overlaten": ("verb", "to leave to", None),
    "overleveren": ("verb", "to hand down", None),
    "overlijden": ("verb", "to pass away", None),
    "overslaan": ("verb", "to skip", None),
    "overtreding": ("noun", "offense; violation", "de"),
    "overtreffen": ("verb", "to surpass", None),
    "overtuigd": ("adjective", "convinced", None),
    "overvallen": ("verb", "to attack; to rob", None),
    "overvloed": ("noun", "abundance", "de"),
    "overvloedig": ("adjective", "abundant", None),
    "overwegend": ("adjective", "predominantly", None),
    "overzien": ("verb", "to oversee; to survey", None),
    "paal": ("noun", "pole; post", "de"),
    "paars": ("adjective", "purple", None),
    "pakje": ("noun", "parcel; package", "het"),
    "palm": ("noun", "palm", "de"),
    "pand": ("noun", "building; premises", "het"),
    "papa": ("noun", "dad", "de"),
    "papieren": ("noun", "papers; documents", "de"),
    "paradijs": ("noun", "paradise", "het"),
    "paragraaf": ("noun", "paragraph", "de"),
    "paranormaal": ("adjective", "paranormal", None),
    "paren": ("verb", "to mate", None),
    "parfum": ("noun", "perfume", "het"),
    "park": ("noun", "park", "het"),
    "parkeren": ("verb", "to park", None),
    "parlementair": ("adjective", "parliamentary", None),
    "particulier": ("adjective", "private", None),
    "paspoort": ("noun", "passport", "het"),
    "passage": ("noun", "passage", "de"),
    "passagier": ("noun", "passenger", "de"),
    "passief": ("adjective", "passive", None),
    "pastoor": ("noun", "parish priest", "de"),
    "pater": ("noun", "father; friar", "de"),
    "patiënt": ("noun", "patient", "de"),
    "pauze": ("noun", "break; pause", "de"),
    "pedagogisch": ("adjective", "pedagogical", None),
    "peil": ("noun", "level", "het"),
    "peinzen": ("verb", "to ponder", None),
    "penis": ("noun", "penis", "de"),
    "penning": ("noun", "coin; medal", "de"),
    "pensioen": ("noun", "pension", "het"),
    "peper": ("noun", "pepper", "de"),
    "percentage": ("noun", "percentage", "het"),
    "perfect": ("adjective", "perfect", None),
    "perron": ("noun", "platform", "het"),
    "pers": ("noun", "press", "de"),
    "persen": ("verb", "to press; to squeeze", None),
    "personage": ("noun", "character", "het"),
    "personeel": ("noun", "staff; personnel", "het"),
    "perspectief": ("noun", "perspective", "het"),
    "pest": ("noun", "plague; pest", "de"),
    "pet": ("noun", "cap", "de"),
    "peter": ("noun", "godfather", "de"),
    "piano": ("noun", "piano", "de"),
    "piekeren": ("verb", "to worry; to brood", None),
    "piepen": ("verb", "to squeak", None),
    "pijl": ("noun", "arrow", "de"),
    "pijnlijk": ("adjective", "painful", None),
    "pil": ("noun", "pill", "de"),
    "piloot": ("noun", "pilot", "de"),
    "pistool": ("noun", "pistol", "het"),
    "plafond": ("noun", "ceiling", "het"),
    "plagen": ("verb", "to tease", None),
    "plak": ("noun", "slice", "de"),
    "plakken": ("verb", "to stick; to paste", None),
    "planeet": ("noun", "planet", "de"),
    "planning": ("noun", "planning; schedule", "de"),
    "plantage": ("noun", "plantation", "de"),
    "plas": ("noun", "puddle; pond", "de"),
    "plechtig": ("adjective", "solemn", None),
    "pleiten": ("verb", "to plead", None),
    "plezierig": ("adjective", "pleasant", None),
    "plooi": ("noun", "fold; crease", "de"),
    "plukken": ("verb", "to pick; to pluck", None),
    "podium": ("noun", "stage; podium", "het"),
    "poetsen": ("verb", "to polish; to clean", None),
    "pogen": ("verb", "to attempt", None),
    "politieman": ("noun", "policeman", "de"),
    "pols": ("noun", "wrist; pulse", "de"),
    "pony": ("noun", "pony", "de"),
    "pool": ("noun", "pole", "de"),
    "poos": ("noun", "while; spell", "de"),
    "poot": ("noun", "paw; leg", "de"),
    "portefeuille": ("noun", "wallet; portfolio", "de"),
    "portier": ("noun", "doorman", "de"),
    "portret": ("noun", "portrait", "het"),
    "potentieel": ("adjective", "potential", None),
    "potlood": ("noun", "pencil", "het"),
    "poëzie": ("noun", "poetry", "de"),
    "praatje": ("noun", "chat; rumor", "het"),
    "predikant": ("noun", "preacher; minister", "de"),
    "premier": ("noun", "prime minister", "de"),
    "presenteren": ("verb", "to present", None),
    "pretentie": ("noun", "pretension", "de"),
    "prijs": ("noun", "price; prize", "de"),
    "prijzen": ("verb", "to praise", None),
    "prikkel": ("noun", "stimulus", "de"),
    "prikkelen": ("verb", "to stimulate", None),
    "prikken": ("verb", "to prick", None),
    "prima": ("adjective", "excellent; fine", None),
    "primair": ("adjective", "primary", None),
    "primitief": ("adjective", "primitive", None),
    "principieel": ("adjective", "principled", None),
    "proberen": ("verb", "to try", None),
    "problematiek": ("noun", "set of problems", "de"),
    "procent": ("noun", "percent", "het"),
    "producent": ("noun", "producer", "de"),
    "proef": ("noun", "test; experiment", "de"),
    "proefpersoon": ("noun", "test subject", "de"),
    "proeven": ("verb", "to taste", None),
    "prof": ("noun", "professor", "de"),
    "profeet": ("noun", "prophet", "de"),
    "profiteren": ("verb", "to profit; to benefit", None),
    "progressief": ("adjective", "progressive", None),
    "projecteren": ("verb", "to project", None),
    "prompt": ("adjective", "prompt", None),
    "prooi": ("noun", "prey", "de"),
    "propaganda": ("noun", "propaganda", "de"),
    "provinciaal": ("adjective", "provincial", None),
    "proza": ("noun", "prose", "het"),
    "psychiater": ("noun", "psychiatrist", "de"),
    "psychiatrisch": ("adjective", "psychiatric", None),
    "psychisch": ("adjective", "psychological", None),
    "psychologie": ("noun", "psychology", "de"),
    "psychologisch": ("adjective", "psychological", None),
    "psycholoog": ("noun", "psychologist", "de"),
    "publicatie": ("noun", "publication", "de"),
    "publiceren": ("verb", "to publish", None),
    "publiciteit": ("noun", "publicity", "de"),
    "puk": ("noun", "tot; toddler", "de"),
    "putten": ("verb", "to draw from", None),
    "raadsel": ("noun", "riddle; puzzle", "het"),
    "raden": ("verb", "to guess; to advise", None),
    "radicaal": ("adjective", "radical", None),
    "radio": ("noun", "radio", "de"),
    "raket": ("noun", "rocket", "de"),
    "ramp": ("noun", "disaster", "de"),
    "rangschikken": ("verb", "to arrange; to classify", None),
    "rapen": ("verb", "to pick up", None),
    "rapport": ("noun", "report", "het"),
    "ras": ("noun", "race; breed", "het"),
    "rat": ("noun", "rat", "de"),
    "ratelen": ("verb", "to rattle", None),
    "rationeel": ("adjective", "rational", None),
    "rauw": ("adjective", "raw", None),
    "razen": ("verb", "to rage", None),
    "realistisch": ("adjective", "realistic", None),
    "realiteit": ("noun", "reality", "de"),
    "recept": ("noun", "recipe; prescription", "het"),
    "rechercheur": ("noun", "detective", "de"),
    "rechtbank": ("noun", "court", "de"),
    "rechten": ("noun", "rights; law", "de"),
    "rechterhand": ("noun", "right hand", "de"),
    "rechtspraak": ("noun", "justice; jurisdiction", "de"),
    "rechtvaardigen": ("verb", "to justify", None),
    "reclame": ("noun", "advertising", "de"),
    "rector": ("noun", "rector", "de"),
    "redacteur": ("noun", "editor", "de"),
    "redactie": ("noun", "editorial office", "de"),
    "redenering": ("noun", "reasoning", "de"),
    "reduceren": ("verb", "to reduce", None),
    "regenen": ("verb", "to rain", None),
    "regent": ("noun", "regent", "de"),
    "regeren": ("verb", "to govern", None),
    "registreren": ("verb", "to register", None),
    "reiken": ("verb", "to reach", None),
    "reiziger": ("noun", "traveler", "de"),
    "rekenschap": ("noun", "account; accountability", "de"),
    "rekken": ("verb", "to stretch", None),
    "relevant": ("adjective", "relevant", None),
    "remmen": ("verb", "to brake", None),
    "republiek": ("noun", "republic", "de"),
    "research": ("noun", "research", "de"),
    "resteren": ("verb", "to remain", None),
    "resulteren": ("verb", "to result", None),
    "reus": ("noun", "giant", "de"),
    "reusachtig": ("adjective", "enormous", None),
    "revolutie": ("noun", "revolution", "de"),
    "revolutionair": ("adjective", "revolutionary", None),
    "revolver": ("noun", "revolver", "de"),
    "reëel": ("adjective", "real; realistic", None),
    "richtlijn": ("noun", "guideline", "de"),
    "ridder": ("noun", "knight", "de"),
    "riem": ("noun", "belt; strap", "de"),
    "riet": ("noun", "reed", "het"),
    "rij": ("noun", "row; line", "de"),
    "rijp": ("adjective", "ripe; mature", None),
    "rijpen": ("verb", "to ripen", None),
    "rijzen": ("verb", "to rise", None),
    "rillen": ("verb", "to shiver", None),
    "rimpel": ("noun", "wrinkle", "de"),
    "rinkelen": ("verb", "to jingle; to ring", None),
    "rit": ("noun", "ride; trip", "de"),
    "ritme": ("noun", "rhythm", "het"),
    "ritueel": ("noun", "ritual", "het"),
    "roeien": ("verb", "to row", None),
    "roeren": ("verb", "to stir", None),
    "roerloos": ("adjective", "motionless", None),
    "roken": ("verb", "to smoke", None),
    "rollen": ("verb", "to roll", None),
    "rommel": ("noun", "mess; junk", "de"),
    "romp": ("noun", "hull; torso", "de"),
    "ronde": ("noun", "round", "de"),
    "rondlopen": ("verb", "to walk around", None),
    "roos": ("noun", "rose", "de"),
    "roosteren": ("verb", "to roast; to grill", None),
    "rot": ("adjective", "rotten; lousy", None),
    "rots": ("noun", "rock", "de"),
    "route": ("noun", "route", "de"),
    "roze": ("adjective", "pink", None),
    "ruil": ("noun", "exchange; trade", "de"),
    "ruimen": ("verb", "to clear", None),
    "ruisen": ("verb", "to rustle", None),
    "ruit": ("noun", "window pane", "de"),
    "ruiter": ("noun", "rider; horseman", "de"),
    "ruk": ("noun", "jerk; tug", "de"),
    "rukken": ("verb", "to tug; to jerk", None),
    "ruw": ("adjective", "rough", None),
    "ruzie": ("noun", "quarrel", "de"),
    "ruïne": ("noun", "ruin", "de"),
}
