WORDS = {
    "saai": ("adjective", "boring", None),
    "salaris": ("noun", "salary", "het"),
    "salon": ("noun", "salon", "de"),
    "samenhang": ("noun", "coherence", "de"),
    "samenhangen": ("verb", "to be connected", None),
    "samenvatten": ("verb", "to summarize", None),
    "sanctie": ("noun", "sanction", "de"),
    "saus": ("noun", "sauce", "de"),
    "schaal": ("noun", "scale", "de"),
    "schaamte": ("noun", "shame", "de"),
    "schaap": ("noun", "sheep", "het"),
    "schaars": ("adjective", "scarce", None),
    "schade": ("noun", "damage", "de"),
    "schakelen": ("verb", "to switch", None),
    "schatting": ("noun", "estimate", "de"),
    "schedel": ("noun", "skull", "de"),
    "scheef": ("adjective", "crooked", None),
    "scheiden": ("verb", "to separate", None),
    "schelen": ("verb", "to differ", None),
    "schema": ("noun", "scheme", "het"),
    "schemering": ("noun", "twilight", "de"),
    "schepping": ("noun", "creation", "de"),
    "scheren": ("verb", "to shave", None),
    "scherm": ("noun", "screen", "het"),
    "schets": ("noun", "sketch", "de"),
    "schetsen": ("verb", "to sketch", None),
    "scheuren": ("verb", "to tear", None),
    "schijf": ("noun", "disk", "de"),
    "schijn": ("noun", "appearance", "de"),
    "schijnbaar": ("adjective", "apparent", None),
    "schijnen": ("verb", "to seem", None),
    "schikken": ("verb", "to arrange", None),
    "schilder": ("noun", "painter", "de"),
    "schildering": ("noun", "painting", "de"),
    "schim": ("noun", "shadow", "de"),
    "schitteren": ("verb", "to sparkle", None),
    "schitterend": ("adjective", "brilliant", None),
    "schoen": ("noun", "shoe", "de"),
    "schok": ("noun", "shock", "de"),
    "schokken": ("verb", "to shock", None),
    "scholengemeenschap": ("noun", "school community", "de"),
    "schommelen": ("verb", "to swing", None),
    "schoonmaken": ("verb", "to clean", None),
    "schoot": ("noun", "lap", "de"),
    "schoppen": ("verb", "to kick", None),
    "schot": ("noun", "shot", "het"),
    "schotel": ("noun", "dish", "de"),
    "schrapen": ("verb", "to scrape", None),
    "schreien": ("verb", "to cry", None),
    "schriftelijk": ("adjective", "written", None),
    "schrik": ("noun", "fright", "de"),
    "schudden": ("verb", "to shake", None),
    "schuifelen": ("verb", "to shuffle", None),
    "schuilen": ("verb", "to shelter", None),
    "schuilplaats": ("noun", "shelter", "de"),
    "schuin": ("adjective", "slanted", None),
    "schuiven": ("verb", "to slide", None),
    "schuur": ("noun", "barn", "de"),
    "scène": ("noun", "scene", "de"),
    "seconde": ("noun", "second", "de"),
    "secretaresse": ("noun", "secretary (female)", "de"),
    "secretaris": ("noun", "secretary", "de"),
    "sectie": ("noun", "section", "de"),
    "secundair": ("adjective", "secondary", None),
    "seizoen": ("noun", "season", "het"),
    "seks": ("noun", "sex", "de"),
    "seksualiteit": ("noun", "sexuality", "de"),
    "seksueel": ("adjective", "sexual", None),
    "sekte": ("noun", "sect", "de"),
    "selecteren": ("verb", "to select", None),
    "selectie": ("noun", "selection", "de"),
    "sensatie": ("noun", "sensation", "de"),
    "september": ("noun", "September", "de"),
    "sergeant": ("noun", "sergeant", "de"),
    "serie": ("noun", "series", "de"),
    "serieus": ("adjective", "serious", None),
    "serveren": ("verb", "to serve", None),
    "sherry": ("noun", "sherry", "de"),
    "sierlijk": ("adjective", "graceful", None),
    "sigaar": ("noun", "cigar", "de"),
    "sigaret": ("noun", "cigarette", "de"),
    "signaleren": ("verb", "to signal", None),
    "simpel": ("adjective", "simple", None),
    "sint": ("noun", "saint", "de"),
    "sissen": ("verb", "to hiss", None),
    "slaaf": ("noun", "slave", "de"),
    "slaapkamer": ("noun", "bedroom", "de"),
    "slaken": ("verb", "to utter", None),
    "slang": ("noun", "snake", "de"),
    "slank": ("adjective", "slim", None),
    "slap": ("adjective", "weak", None),
    "slaperig": ("adjective", "sleepy", None),
    "slavernij": ("noun", "slavery", "de"),
    "slenteren": ("verb", "to stroll", None),
    "slepen": ("verb", "to drag", None),
    "sleuren": ("verb", "to haul", None),
    "slikken": ("verb", "to swallow", None),
    "slingeren": ("verb", "to swing", None),
    "slok": ("noun", "sip", "de"),
    "sloot": ("noun", "ditch", "de"),
    "slordig": ("adjective", "sloppy", None),
    "sluipen": ("verb", "to sneak", None),
    "smaken": ("verb", "to taste", None),
    "smeken": ("verb", "to beg", None),
    "smeren": ("verb", "to smear", None),
    "smerig": ("adjective", "dirty", None),
    "snappen": ("verb", "to understand", None),
    "snauwen": ("verb", "to snarl", None),
    "sneeuw": ("noun", "snow", "de"),
    "sneuvelen": ("verb", "to perish", None),
    "snikken": ("verb", "to sob", None),
    "snor": ("noun", "moustache", "de"),
    "snuiven": ("verb", "to sniff", None),
    "socialisme": ("noun", "socialism", "het"),
    "socialist": ("noun", "socialist", "de"),
    "socialistisch": ("adjective", "socialist", None),
    "sociologie": ("noun", "sociology", "de"),
    "socioloog": ("noun", "sociologist", "de"),
    "soep": ("noun", "soup", "de"),
    "sok": ("noun", "sock", "de"),
    "solidariteit": ("noun", "solidarity", "de"),
    "som": ("noun", "sum", "de"),
    "somber": ("adjective", "gloomy", None),
    "spannen": ("verb", "to tighten", None),
    "spatten": ("verb", "to splash", None),
    "specialist": ("noun", "specialist", "de"),
    "specifiek": ("adjective", "specific", None),
    "speelgoed": ("noun", "toys", "het"),
    "speels": ("adjective", "playful", None),
    "spelling": ("noun", "spelling", "de"),
    "spijten": ("verb", "to regret", None),
    "spleet": ("noun", "crack", "de"),
    "spoedig": ("adjective", "speedy", None),
    "spoelen": ("verb", "to rinse", None),
    "spontaan": ("adjective", "spontaneous", None),
    "spook": ("noun", "ghost", "het"),
    "sporen": ("verb", "to track", None),
    "spot": ("noun", "mockery", "de"),
    "spotten": ("verb", "to mock", None),
    "spreiden": ("verb", "to spread", None),
    "sprong": ("noun", "jump", "de"),
    "sprookje": ("noun", "fairy tale", "het"),
    "spuiten": ("verb", "to spray", None),
    "spul": ("noun", "stuff", "het"),
    "spullen": ("noun", "belongings", "de"),
    "staal": ("noun", "steel", "het"),
    "staande": ("adjective", "standing", None),
    "staatssecretaris": ("noun", "state secretary", "de"),
    "stal": ("noun", "stable", "de"),
    "stamelen": ("verb", "to stammer", None),
    "stammen": ("verb", "to originate", None),
    "stampen": ("verb", "to stamp", None),
    "stand": ("noun", "position", "de"),
    "stank": ("noun", "stench", "de"),
    "stapel": ("noun", "pile", "de"),
    "star": ("adjective", "rigid", None),
    "staren": ("verb", "to stare", None),
    "start": ("noun", "start", "de"),
    "starten": ("verb", "to start", None),
    "station": ("noun", "station", "het"),
    "status": ("noun", "status", "de"),
    "stedelijk": ("adjective", "urban", None),
    "steek": ("noun", "stitch", "de"),
    "steil": ("adjective", "steep", None),
    "stel": ("noun", "couple", "het"),
    "stellig": ("adjective", "firm", None),
    "stempel": ("noun", "stamp", "de"),
    "sterkte": ("noun", "strength", "de"),
    "stevig": ("adjective", "sturdy", None),
    "stiekem": ("adjective", "sneaky", None),
    "stier": ("noun", "bull", "de"),
    "stijf": ("adjective", "stiff", None),
    "stikken": ("verb", "to choke", None),
    "stille": ("adjective", "quiet", None),
    "stilstaan": ("verb", "to stand still", None),
    "stilstand": ("noun", "standstill", "de"),
    "stimuleren": ("verb", "to stimulate", None),
    "stinken": ("verb", "to stink", None),
    "stoep": ("noun", "sidewalk", "de"),
    "stoet": ("noun", "procession", "de"),
    "stoornis": ("noun", "disorder", "de"),
    "stoot": ("noun", "push", "de"),
    "stormen": ("verb", "to storm", None),
    "storten": ("verb", "to collapse", None),
    "stoten": ("verb", "to bump", None),
    "straal": ("noun", "ray", "de"),
    "strak": ("adjective", "tight", None),
    "stralend": ("adjective", "radiant", None),
    "straling": ("noun", "radiation", "de"),
    "strand": ("noun", "beach", "het"),
    "strategisch": ("adjective", "strategic", None),
    "streep": ("noun", "stripe", "de"),
    "strekking": ("noun", "purport", "de"),
    "strelen": ("verb", "to caress", None),
    "streng": ("adjective", "strict", None),
    "stress": ("noun", "stress", "de"),
    "strijken": ("verb", "to iron", None),
    "stro": ("noun", "straw", "het"),
    "stromen": ("verb", "to flow", None),
    "stroming": ("noun", "current", "de"),
    "strooien": ("verb", "to scatter", None),
    "structureel": ("adjective", "structural", None),
    "struik": ("noun", "bush", "de"),
    "struikelen": ("verb", "to stumble", None),
    "stuiten": ("verb", "to halt", None),
    "stuur": ("noun", "steering wheel", "het"),
    "subject": ("noun", "subject", "het"),
    "subjectief": ("adjective", "subjective", None),
    "subsidie": ("noun", "subsidy", "de"),
    "subtiel": ("adjective", "subtle", None),
    "succesvol": ("adjective", "successful", None),
    "suggestie": ("noun", "suggestion", "de"),
    "suiker": ("noun", "sugar", "de"),
    "sultan": ("noun", "sultan", "de"),
    "sussen": ("verb", "to soothe", None),
    "symbolisch": ("adjective", "symbolic", None),
    "sympathiek": ("adjective", "likeable", None),
    "symptoom": ("noun", "symptom", "het"),
    "systematisch": ("adjective", "systematic", None),
    "taai": ("adjective", "tough", None),
    "taalgebruik": ("noun", "language use", "het"),
    "tabak": ("noun", "tobacco", "de"),
    "tabel": ("noun", "table", "de"),
    "tablet": ("noun", "tablet", "het"),
    "tafereel": ("noun", "scene", "het"),
    "tal": ("noun", "number", "het"),
    "talent": ("noun", "talent", "het"),
    "talloos": ("adjective", "countless", None),
    "talrijk": ("adjective", "numerous", None),
    "tandarts": ("noun", "dentist", "de"),
    "tank": ("noun", "tank", "de"),
    "tapijt": ("noun", "carpet", "het"),
    "tas": ("noun", "bag", "de"),
    "tasten": ("verb", "to grope", None),
    "taxi": ("noun", "taxi", "de"),
    "team": ("noun", "team", "het"),
    "teder": ("adjective", "tender", None),
    "tegendeel": ("noun", "opposite", "het"),
    "tegenhouden": ("verb", "to hold back", None),
    "tegenkomen": ("verb", "to encounter", None),
    "tegenzin": ("noun", "reluctance", "de"),
    "tehuis": ("noun", "home", "het"),
    "teleurstellen": ("verb", "to disappoint", None),
    "televisie": ("noun", "television", "de"),
    "tempo": ("noun", "pace", "het"),
    "tendens": ("noun", "tendency", "de"),
    "tepel": ("noun", "nipple", "de"),
    "terecht": ("adjective", "justified", None),
    "terechtkomen": ("verb", "to end up", None),
    "term": ("noun", "term", "de"),
    "termijn": ("noun", "term", "de"),
    "terras": ("noun", "terrace", "het"),
    "terugbrengen": ("verb", "to bring back", None),
    "teruggaan": ("verb", "to go back", None),
    "terugkeer": ("noun", "return", "de"),
    "terugkomen": ("verb", "to come back", None),
    "terugvinden": ("verb", "to find back", None),
    "test": ("noun", "test", "de"),
    "testament": ("noun", "testament", "het"),
    "teug": ("noun", "gulp", "de"),
    "teweegbrengen": ("verb", "to bring about", None),
    "thee": ("noun", "tea", "de"),
    "theelepel": ("noun", "teaspoon", "de"),
    "theologie": ("noun", "theology", "de"),
    "theologisch": ("adjective", "theological", None),
    "theoloog": ("noun", "theologian", "de"),
    "theoretisch": ("adjective", "theoretical", None),
    "therapeut": ("noun", "therapist", "de"),
    "therapie": ("noun", "therapy", "de"),
    "thuiskomen": ("verb", "to come home", None),
    "tiental": ("noun", "group of ten", "het"),
    "tijdig": ("adjective", "timely", None),
    "tijdstip": ("noun", "moment", "het"),
    "tikken": ("verb", "to tap", None),
    "tillen": ("verb", "to lift", None),
    "timmeren": ("verb", "to hammer", None),
    "tint": ("noun", "tint", "de"),
    "titel": ("noun", "title", "de"),
    "toedienen": ("verb", "to administer", None),
    "toegankelijk": ("adjective", "accessible", None),
    "toegeven": ("verb", "to admit", None),
    "toekennen": ("verb", "to award", None),
    "toekijken": ("verb", "to watch", None),
    "toelichting": ("noun", "explanation", "de"),
    "toename": ("noun", "increase", "de"),
    "toenmalig": ("adjective", "then", None),
    "toerist": ("noun", "tourist", "de"),
    "toeschouwer": ("noun", "spectator", "de"),
    "toeschrijven": ("verb", "to attribute", None),
    "toespraak": ("noun", "speech", "de"),
    "toestaan": ("verb", "to allow", None),
    "toestel": ("noun", "device", "het"),
    "toetsen": ("verb", "to test", None),
    "toeval": ("noun", "coincidence", "het"),
    "toevallig": ("adjective", "coincidental", None),
    "toevertrouwen": ("verb", "to entrust", None),
    "toevoegen": ("verb", "to add", None),
    "toewijzen": ("verb", "to assign", None),
    "toezicht": ("noun", "supervision", "het"),
    "toezien": ("verb", "to supervise", None),
    "toilet": ("noun", "toilet", "het"),
    "totaal": ("adjective", "total", None),
    "touw": ("noun", "rope", "het"),
    "traag": ("adjective", "slow", None),
    "tragisch": ("adjective", "tragic", None),
    "training": ("noun", "training", "de"),
    "tram": ("noun", "tram", "de"),
    "transport": ("noun", "transport", "het"),
    "trap": ("noun", "stairs", "de"),
    "trappen": ("verb", "to kick", None),
    "treden": ("verb", "to step", None),
    "treffen": ("verb", "to hit", None),
    "trein": ("noun", "train", "de"),
    "trek": ("noun", "appetite", "de"),
    "treurig": ("adjective", "sad", None),
    "triest": ("adjective", "sad", None),
    "trillen": ("verb", "to tremble", None),
    "triomf": ("noun", "triumph", "de"),
    "triomfantelijk": ("adjective", "triumphant", None),
    "troep": ("noun", "mess", "de"),
    "trommel": ("noun", "drum", "de"),
    "troost": ("noun", "comfort", "de"),
    "troosten": ("verb", "to comfort", None),
    "tropisch": ("adjective", "tropical", None),
    "trottoir": ("noun", "pavement", "het"),
    "truc": ("noun", "trick", "de"),
    "trui": ("noun", "sweater", "de"),
    "turen": ("verb", "to peer", None),
    "tweetal": ("noun", "pair", "het"),
    "typeren": ("verb", "to characterize", None),
    "uitbreken": ("verb", "to break out", None),
    "uitbrengen": ("verb", "to release", None),
    "uitbundig": ("adjective", "exuberant", None),
    "uitdagen": ("verb", "to challenge", None),
    "uitdrukkelijk": ("adjective", "explicit", None),
    "uiteenlopen": ("verb", "to diverge", None),
    "uiteenzetting": ("noun", "exposition", "de"),
    "uiteinde": ("noun", "end", "het"),
    "uiten": ("verb", "to express", None),
    "uiterste": ("noun", "extreme", "het"),
    "uitgang": ("noun", "exit", "de"),
    "uitgeput": ("adjective", "exhausted", None),
    "uitgesproken": ("adjective", "outspoken", None),
    "uitgestrekt": ("adjective", "vast", None),
    "uitgever": ("noun", "publisher", "de"),
    "uitgroeien": ("verb", "to grow into", None),
    "uithalen": ("verb", "to pull out", None),
    "uiting": ("noun", "expression", "de"),
    "uitkiezen": ("verb", "to choose", None),
    "uitkijken": ("verb", "to look out", None),
    "uitkomst": ("noun", "outcome", "de"),
    "uitleg": ("noun", "explanation", "de"),
    "uitlopen": ("verb", "to run out", None),
    "uitnodigen": ("verb", "to invite", None),
    "uitnodiging": ("noun", "invitation", "de"),
    "uitroepen": ("verb", "to exclaim", None),
    "uitrusten": ("verb", "to rest", None),
    "uitsluiten": ("verb", "to exclude", None),
    "uitstappen": ("verb", "to get off", None),
    "uitstek": ("noun", "excellence", "het"),
    "uitstekend": ("adjective", "excellent", None),
    "uitstrekken": ("verb", "to stretch", None),
    "uittrekken": ("verb", "to take off", None),
    "uitvallen": ("verb", "to fall out", None),
    "uitvinden": ("verb", "to invent", None),
    "uitvinding": ("noun", "invention", "de"),
    "uitvoerig": ("adjective", "detailed", None),
    "uitweg": ("noun", "way out", "de"),
    "uitzenden": ("verb", "to broadcast", None),
    "uitzending": ("noun", "broadcast", "de"),
    "uitzoeken": ("verb", "to sort out", None),
    "uitzonderlijk": ("adjective", "exceptional", None),
    "unie": ("noun", "union", "de"),
    "uniek": ("adjective", "unique", None),
    "uniform": ("noun", "uniform", "het"),
    "universeel": ("adjective", "universal", None),
    "universitair": ("adjective", "university", None),
    "urenlang": ("adjective", "lasting hours", None),
    "vaart": ("noun", "speed", "de"),
    "vaas": ("noun", "vase", "de"),
    "vaderland": ("noun", "fatherland", "het"),
    "vak": ("noun", "subject", "het"),
    "vakbeweging": ("noun", "labor movement", "de"),
    "val": ("noun", "fall", "de"),
    "varen": ("verb", "to sail", None),
    "variant": ("noun", "variant", "de"),
    "variatie": ("noun", "variation", "de"),
    "variëren": ("verb", "to vary", None),
    "varken": ("noun", "pig", "het"),
    "vastbesloten": ("adjective", "determined", None),
    "vasthouden": ("verb", "to hold on", None),
    "vastleggen": ("verb", "to record", None),
    "vat": ("noun", "barrel", "het"),
    "vatten": ("verb", "to grasp", None),
    "vechten": ("verb", "to fight", None),
    "vee": ("noun", "cattle", "het"),
    "veelvuldig": ("adjective", "frequent", None),
    "veer": ("noun", "feather", "de"),
    "vegen": ("verb", "to sweep", None),
    "vel": ("noun", "skin", "het"),
    "velen": ("verb", "to endure", None),
    "vellen": ("verb", "to fell", None),
    "venster": ("noun", "window", "het"),
    "vent": ("noun", "guy", "de"),
    "verantwoorden": ("verb", "to justify", None),
    "verantwoording": ("noun", "accountability", "de"),
    "verbaal": ("adjective", "verbal", None),
    "verbaasd": ("adjective", "amazed", None),
    "verbazen": ("verb", "to amaze", None),
    "verbazing": ("noun", "amazement", "de"),
    "verbeelden": ("verb", "to imagine", None),
    "verblijven": ("verb", "to stay", None),
    "verblinden": ("verb", "to blind", None),
    "verbod": ("noun", "ban", "het"),
    "verboden": ("adjective", "forbidden", None),
    "verbond": ("noun", "alliance", "het"),
    "verbouwen": ("verb", "to renovate", None),
    "verbranden": ("verb", "to burn", None),
    "verdacht": ("adjective", "suspicious", None),
    "verdeeld": ("adjective", "divided", None),
    "verdenken": ("verb", "to suspect", None),
    "verdienste": ("noun", "merit", "de"),
    "verdiepen": ("verb", "to deepen", None),
    "verdoven": ("verb", "to numb", None),
    "verdriet": ("noun", "sorrow", "het"),
    "verdrietig": ("adjective", "sad", None),
    "verdrijven": ("verb", "to drive away", None),
    "verdringen": ("verb", "to repress", None),
    "verdrinken": ("verb", "to drown", None),
    "verduidelijken": ("verb", "to clarify", None),
    "vereiste": ("noun", "requirement", "de"),
    "vereren": ("verb", "to honor", None),
    "verf": ("noun", "paint", "de"),
    "verfijnen": ("verb", "to refine", None),
    "vergaan": ("verb", "to perish", None),
    "vergeefs": ("adjective", "futile", None),
    "vergen": ("verb", "to require", None),
    "vergeven": ("verb", "to forgive", None),
    "vergezellen": ("verb", "to accompany", None),
    "vergissen": ("verb", "to be mistaken", None),
    "vergissing": ("noun", "mistake", "de"),
    "verheffen": ("verb", "to raise", None),
    "verheugen": ("verb", "to delight", None),
    "verhinderen": ("verb", "to prevent", None),
    "verhogen": ("verb", "to raise", None),
    "verhoging": ("noun", "increase", "de"),
    "verhoor": ("noun", "interrogation", "het"),
    "verhuizen": ("verb", "to move house", None),
    "verjaardag": ("noun", "birthday", "de"),
    "verjagen": ("verb", "to chase away", None),
    "verkennen": ("verb", "to explore", None),
    "verkeren": ("verb", "to be in a state", None),
    "verkiezingen": ("noun", "elections", "de"),
    "verkondigen": ("verb", "to proclaim", None),
    "verkoop": ("noun", "sale", "de"),
    "verkoper": ("noun", "seller", "de"),
    "verlegen": ("adjective", "shy", None),
    "verleiden": ("verb", "to seduce", None),
    "verleiding": ("noun", "temptation", "de"),
    "verlenen": ("verb", "to grant", None),
    "verlengen": ("verb", "to extend", None),
    "verlicht": ("adjective", "enlightened", None),
    "verlichten": ("verb", "to lighten", None),
    "verliefd": ("adjective", "in love", None),
    "verlof": ("noun", "leave", "het"),
    "verloop": ("noun", "course", "het"),
    "verlopen": ("verb", "to expire", None),
    "verloren": ("adjective", "lost", None),
    "verlossen": ("verb", "to deliver", None),
    "vermelden": ("verb", "to mention", None),
    "vermengen": ("verb", "to mix", None),
    "vermindering": ("noun", "reduction", "de"),
    "vermoedelijk": ("adjective", "presumable", None),
    "vermoeden": ("verb", "to suspect", None),
    "vermoeidheid": ("noun", "fatigue", "de"),
    "vermoeien": ("verb", "to tire", None),
    "vernederen": ("verb", "to humiliate", None),
    "vernemen": ("verb", "to learn", None),
    "vernielen": ("verb", "to destroy", None),
    "vernieuwen": ("verb", "to renew", None),
    "vernieuwing": ("noun", "renewal", "de"),
    "veronderstellen": ("verb", "to assume", None),
    "veronderstelling": ("noun", "assumption", "de"),
    "verontwaardiging": ("noun", "indignation", "de"),
    "veroordelen": ("verb", "to condemn", None),
    "veroveren": ("verb", "to conquer", None),
    "verovering": ("noun", "conquest", "de"),
    "verplaatsen": ("verb", "to move", None),
    "verraad": ("noun", "betrayal", "het"),
    "verraden": ("verb", "to betray", None),
    "verrichten": ("verb", "to perform", None),
    "verrukkelijk": ("adjective", "delightful", None),
    "vers": ("adjective", "fresh", None),
    "verscheidene": ("adjective", "several", None),
    "verscheidenheid": ("noun", "diversity", "de"),
    "verscheuren": ("verb", "to tear apart", None),
    "verschillende": ("adjective", "various", None),
    "verschrikkelijk": ("adjective", "terrible", None),
    "verschrikken": ("verb", "to frighten", None),
    "verschuiven": ("verb", "to shift", None),
    "verschuiving": ("noun", "shift", "de"),
    "versie": ("noun", "version", "de"),
    "versieren": ("verb", "to decorate", None),
    "verslaan": ("verb", "to defeat", None),
    "verstandelijk": ("adjective", "intellectual", None),
    "versterking": ("noun", "reinforcement", "de"),
    "verstoppen": ("verb", "to hide", None),
    "verstrekken": ("verb", "to provide", None),
    "verstrijken": ("verb", "to elapse", None),
    "vertalen": ("verb", "to translate", None),
    "vertaling": ("noun", "translation", "de"),
    "verte": ("noun", "distance", "de"),
    "verteren": ("verb", "to digest", None),
    "verticaal": ("adjective", "vertical", None),
    "vertrek": ("noun", "departure", "het"),
    "vertrouwd": ("adjective", "familiar", None),
    "vertrouwelijk": ("adjective", "confidential", None),
    "vervaardigen": ("verb", "to manufacture", None),
    "vervallen": ("verb", "to expire", None),
    "vervangen": ("verb", "to replace", None),
    "vervelen": ("verb", "to bore", None),
    "vervelend": ("adjective", "annoying", None),
    "verveling": ("noun", "boredom", "de"),
    "verven": ("verb", "to paint", None),
    "vervoeren": ("verb", "to transport", None),
    "vervolg": ("noun", "sequel", "het"),
    "vervuld": ("adjective", "fulfilled", None),
    "vervullen": ("verb", "to fulfill", None),
    "verwaarlozen": ("verb", "to neglect", None),
    "verwantschap": ("noun", "kinship", "de"),
    "verward": ("adjective", "confused", None),
    "verwarmen": ("verb", "to heat", None),
    "verwarring": ("noun", "confusion", "de"),
    "verwekken": ("verb", "to beget", None),
    "verwezenlijken": ("verb", "to realize", None),
    "verwijt": ("noun", "reproach", "het"),
    "verwisselen": ("verb", "to exchange", None),
    "verwonderen": ("verb", "to astonish", None),
    "verwondering": ("noun", "astonishment", "de"),
    "verzinken": ("verb", "to sink", None),
    "verzinnen": ("verb", "to invent", None),
    "verzoenen": ("verb", "to reconcile", None),
    "verzwakken": ("verb", "to weaken", None),
    "verzwijgen": ("verb", "to conceal", None),
    "vestiging": ("noun", "establishment", "de"),
    "vierkant": ("adjective", "square", None),
    "vies": ("adjective", "dirty", None),
    "vijver": ("noun", "pond", "de"),
    "villa": ("noun", "villa", "de"),
    "vingertop": ("noun", "fingertip", "de"),
    "viool": ("noun", "violin", "de"),
    "vis": ("noun", "fish", "de"),
    "visie": ("noun", "vision", "de"),
    "visioen": ("noun", "vision", "het"),
    "vissen": ("verb", "to fish", None),
    "visser": ("noun", "fisherman", "de"),
    "vitaal": ("adjective", "vital", None),
    "vitamine": ("noun", "vitamin", "de"),
    "vlaams": ("adjective", "Flemish", None),
    "vlag": ("noun", "flag", "de"),
    "vlakte": ("noun", "plain", "de"),
    "vlek": ("noun", "stain", "de"),
    "vleugel": ("noun", "wing", "de"),
    "vlieg": ("noun", "fly", "de"),
    "vliegveld": ("noun", "airfield", "het"),
    "vloeistof": ("noun", "liquid", "de"),
    "vloeken": ("verb", "to curse", None),
    "vlot": ("adjective", "fluent", None),
    "vluchtig": ("adjective", "fleeting", None),
    "vocht": ("noun", "moisture", "het"),
    "vochtig": ("adjective", "damp", None),
    "voeding": ("noun", "nutrition", "de"),
    "voegen": ("verb", "to join", None),
    "voertuig": ("noun", "vehicle", "het"),
    "voetstap": ("noun", "footstep", "de"),
    "voldoening": ("noun", "satisfaction", "de"),
    "volgorde": ("noun", "order", "de"),
    "volhouden": ("verb", "to persist", None),
    "volmaakt": ("adjective", "perfect", None),
    "volmaken": ("verb", "to perfect", None),
    "volslagen": ("adjective", "complete", None),
    "volstrekt": ("adjective", "absolute", None),
    "voltooien": ("verb", "to complete", None),
    "voltrekken": ("verb", "to execute", None),
    "volwassene": ("noun", "adult", "de"),
    "vondst": ("noun", "find", "de"),
    "vonk": ("noun", "spark", "de"),
    "voogd": ("noun", "guardian", "de"),
    "voogdij": ("noun", "guardianship", "de"),
    "vooraanstaand": ("adjective", "prominent", None),
    "voorafgaan": ("verb", "to precede", None),
    "voorbereiden": ("verb", "to prepare", None),
    "voorbereiding": ("noun", "preparation", "de"),
    "voorbijgaan": ("verb", "to pass by", None),
    "voordeur": ("noun", "front door", "de"),
    "voordoen": ("verb", "to occur", None),
    "voorgaan": ("verb", "to go ahead", None),
    "voorgaande": ("adjective", "preceding", None),
    "voorganger": ("noun", "predecessor", "de"),
    "voorhoofd": ("noun", "forehead", "het"),
    "voorjaar": ("noun", "spring", "het"),
    "voorkeur": ("noun", "preference", "de"),
    "voorkomend": ("adjective", "courteous", None),
    "voorleggen": ("verb", "to present", None),
    "voorlezen": ("verb", "to read aloud", None),
    "voorlichting": ("noun", "information", "de"),
    "voormalig": ("adjective", "former", None),
    "vooroordeel": ("noun", "prejudice", "het"),
    "voorouder": ("noun", "ancestor", "de"),
    "voorouders": ("noun", "ancestors", "de"),
    "voorraad": ("noun", "supply", "de"),
    "voorschrift": ("noun", "regulation", "het"),
    "voorschrijven": ("verb", "to prescribe", None),
    "voorspellen": ("verb", "to predict", None),
    "voorspelling": ("noun", "prediction", "de"),
    "voortbestaan": ("noun", "survival", "het"),
    "voortgaan": ("verb", "to continue", None),
    "voortkomen": ("verb", "to arise from", None),
    "voortreffelijk": ("adjective", "excellent", None),
    "voortvloeien": ("verb", "to result from", None),
    "voortzetten": ("verb", "to continue", None),
    "vooruitzicht": ("noun", "prospect", "het"),
    "voorval": ("noun", "incident", "het"),
    "voorziening": ("noun", "provision", "de"),
    "vorig": ("adjective", "previous", None),
    "vork": ("noun", "fork", "de"),
    "vormgeving": ("noun", "design", "de"),
    "vorming": ("noun", "formation", "de"),
    "vouwen": ("verb", "to fold", None),
    "vraagstuk": ("noun", "problem", "het"),
    "vrachtwagen": ("noun", "truck", "de"),
    "vredig": ("adjective", "peaceful", None),
    "vreedzaam": ("adjective", "peaceful", None),
    "vreemdeling": ("noun", "stranger", "de"),
    "vreselijk": ("adjective", "terrible", None),
    "vreten": ("verb", "to devour", None),
    "vreugde": ("noun", "joy", "de"),
    "vriendin": ("noun", "girlfriend", "de"),
    "vriezen": ("verb", "to freeze", None),
    "vrijen": ("verb", "to make love", None),
    "vrijwillig": ("adjective", "voluntary", None),
    "vrijwilliger": ("noun", "volunteer", "de"),
    "vruchtbaar": ("adjective", "fertile", None),
    "vuist": ("noun", "fist", "de"),
    "vurig": ("adjective", "fervent", None),
    "waanzin": ("noun", "madness", "de"),
    "waardevol": ("adjective", "valuable", None),
    "waardigheid": ("noun", "dignity", "de"),
    "waarnemer": ("noun", "observer", "de"),
    "wacht": ("noun", "guard", "de"),
    "waken": ("verb", "to watch over", None),
    "wakker": ("adjective", "awake", None),
    "wal": ("noun", "embankment", "de"),
    "wandeling": ("noun", "walk", "de"),
    "wang": ("noun", "cheek", "de"),
    "wanhoop": ("noun", "despair", "de"),
    "wanhopig": ("adjective", "desperate", None),
    "wankelen": ("verb", "to stagger", None),
    "wantrouwen": ("verb", "to distrust", None),
    "wapenen": ("verb", "to arm", None),
    "wapperen": ("verb", "to flutter", None),
    "wederzijds": ("adjective", "mutual", None),
    "weduwe": ("noun", "widow", "de"),
    "weefsel": ("noun", "tissue", "het"),
    "weekblad": ("noun", "weekly magazine", "het"),
    "weekend": ("noun", "weekend", "het"),
    "weergeven": ("verb", "to represent", None),
    "weerhouden": ("verb", "to restrain", None),
    "weerklinken": ("verb", "to resound", None),
    "weerloos": ("adjective", "defenseless", None),
    "weerspiegelen": ("verb", "to reflect", None),
    "weggaan": ("verb", "to leave", None),
    "weghalen": ("verb", "to remove", None),
    "weglopen": ("verb", "to walk away", None),
    "wegnemen": ("verb", "to take away", None),
    "weigering": ("noun", "refusal", "de"),
    "weiland": ("noun", "pasture", "het"),
    "welkom": ("adjective", "welcome", None),
    "welvaart": ("noun", "prosperity", "de"),
    "welzijn": ("noun", "welfare", "het"),
    "wenden": ("verb", "to turn", None),
    "wenen": ("verb", "to weep", None),
    "wenkbrauw": ("noun", "eyebrow", "de"),
    "wenken": ("verb", "to beckon", None),
    "wennen": ("verb", "to get used to", None),
    "wenselijk": ("adjective", "desirable", None),
    "weren": ("verb", "to keep out", None),
    "werkgelegenheid": ("noun", "employment", "de"),
    "werkgroep": ("noun", "working group", "de"),
    "werkloosheid": ("noun", "unemployment", "de"),
    "werkloze": ("noun", "unemployed person", "de"),
    "werkwijze": ("noun", "method", "de"),
    "werkzaam": ("adjective", "active", None),
    "west": ("noun", "west", "het"),
    "westelijk": ("adjective", "western", None),
    "westen": ("noun", "west", "het"),
    "westers": ("adjective", "western", None),
    "wetboek": ("noun", "code of law", "het"),
    "wetgever": ("noun", "legislator", "de"),
    "wetsontwerp": ("noun", "bill", "het"),
    "whisky": ("noun", "whisky", "de"),
    "wiegen": ("verb", "to rock", None),
    "wiel": ("noun", "wheel", "het"),
    "wijf": ("noun", "woman", "het"),
    "wijfje": ("noun", "female animal", "het"),
    "wijken": ("verb", "to yield", None),
    "wijngaard": ("noun", "vineyard", "de"),
    "wijs": ("adjective", "wise", None),
    "wijsheid": ("noun", "wisdom", "de"),
    "wijsvinger": ("noun", "index finger", "de"),
    "wijten": ("verb", "to blame", None),
    "wikkelen": ("verb", "to wrap", None),
    "wilde": ("noun", "savage", "de"),
    "willekeurig": ("adjective", "random", None),
    "wippen": ("verb", "to hop", None),
    "wiskunde": ("noun", "mathematics", "de"),
    "woede": ("noun", "rage", "de"),
    "woeden": ("verb", "to rage", None),
    "woedend": ("adjective", "furious", None),
    "woest": ("adjective", "wild", None),
    "woestijn": ("noun", "desert", "de"),
    "wolf": ("noun", "wolf", "de"),
    "wolk": ("noun", "cloud", "de"),
    "wond": ("noun", "wound", "de"),
    "wonder": ("noun", "miracle", "het"),
    "wonderbaarlijk": ("adjective", "miraculous", None),
    "wonderlijk": ("adjective", "wondrous", None),
    "woonkamer": ("noun", "living room", "de"),
    "worstelen": ("verb", "to wrestle", None),
    "wortel": ("noun", "root", "de"),
    "wringen": ("verb", "to wring", None),
    "wuiven": ("verb", "to wave", None),
    "zaad": ("noun", "seed", "het"),
    "zaaien": ("verb", "to sow", None),
    "zadel": ("noun", "saddle", "het"),
    "zakdoek": ("noun", "handkerchief", "de"),
    "zaken": ("noun", "business", "de"),
    "zakenman": ("noun", "businessman", "de"),
    "zakken": ("verb", "to sink", None),
    "zat": ("adjective", "drunk", None),
    "zaterdag": ("noun", "Saturday", "de"),
    "zedelijk": ("adjective", "moral", None),
    "zeep": ("noun", "soap", "de"),
    "zeldzaam": ("adjective", "rare", None),
    "zelfmoord": ("noun", "suicide", "de"),
    "zelfvertrouwen": ("noun", "self-confidence", "het"),
    "zendeling": ("noun", "missionary", "de"),
    "zender": ("noun", "transmitter", "de"),
    "zending": ("noun", "mission", "de"),
    "zenuwachtig": ("adjective", "nervous", None),
    "zetel": ("noun", "seat", "de"),
    "zeuren": ("verb", "to whine", None),
    "zielig": ("adjective", "pathetic", None),
    "zijde": ("noun", "silk", "de"),
    "zijkant": ("noun", "side", "de"),
    "zilveren": ("adjective", "silver", None),
    "zingen": ("verb", "to sing", None),
    "zinken": ("verb", "to sink", None),
    "zintuig": ("noun", "sense", "het"),
    "zinvol": ("adjective", "meaningful", None),
    "zitting": ("noun", "session", "de"),
    "zoemen": ("verb", "to hum", None),
    "zoen": ("noun", "kiss", "de"),
    "zoenen": ("verb", "to kiss", None),
    "zoet": ("adjective", "sweet", None),
    "zolder": ("noun", "attic", "de"),
    "zwarte": ("adjective", "black", None),
}
