WORDS = {
    "echo": ("noun", "echo", "de"),
    "echt": ("adjective", "real", None),
    "echtpaar": ("noun", "married couple", "het"),
    "echtscheiding": ("noun", "divorce", "de"),
    "econoom": ("noun", "economist", "de"),
    "edel": ("adjective", "noble", None),
    "eenheid": ("noun", "unity", "de"),
    "eenzaam": ("adjective", "lonely", None),
    "eenzijdig": ("adjective", "one-sided", None),
    "eerbied": ("noun", "respect", "de"),
    "eetlepel": ("noun", "tablespoon", "de"),
    "eeuw": ("noun", "century", "de"),
    "eeuwig": ("adjective", "eternal", None),
    "efficiënt": ("adjective", "efficient", None),
    "ego": ("noun", "ego", "het"),
    "eigenaar": ("noun", "owner", "de"),
    "eigenschap": ("noun", "property", "de"),
    "eik": ("noun", "oak", "de"),
    "eiland": ("noun", "island", "het"),
    "eind": ("noun", "end", "het"),
    "eindeloos": ("adjective", "endless", None),
    "eindigen": ("verb", "to end", None),
    "elegant": ("adjective", "elegant", None),
    "elektronisch": ("adjective", "electronic", None),
    "elementair": ("adjective", "elementary", None),
    "elite": ("noun", "elite", "de"),
    "elleboog": ("noun", "elbow", "de"),
    "ellendig": ("adjective", "miserable", None),
    "emancipatie": ("noun", "emancipation", "de"),
    "emmer": ("noun", "bucket", "de"),
    "emotie": ("noun", "emotion", "de"),
    "emotioneel": ("adjective", "emotional", None),
    "energie": ("noun", "energy", "de"),
    "eng": ("adjective", "scary", None),
    "enkeling": ("noun", "individual", "de"),
    "enthousiasme": ("noun", "enthusiasm", "het"),
    "envelop": ("noun", "envelope", "de"),
    "erectie": ("noun", "erection", "de"),
    "erf": ("noun", "yard", "het"),
    "erfelijk": ("adjective", "hereditary", None),
    "erfenis": ("noun", "inheritance", "de"),
    "ergernis": ("noun", "annoyance", "de"),
    "erkend": ("adjective", "recognized", None),
    "erotisch": ("adjective", "erotic", None),
    "etalage": ("noun", "shop window", "de"),
    "eten": ("verb", "to eat", None),
    "ethiek": ("noun", "ethics", "de"),
    "etiket": ("noun", "label", "het"),
    "evaluatie": ("noun", "evaluation", "de"),
    "evangelie": ("noun", "gospel", "het"),
    "evenwicht": ("noun", "balance", "het"),
    "evenwichtig": ("adjective", "balanced", None),
    "evolutie": ("noun", "evolution", "de"),
    "exact": ("adjective", "exact", None),
    "examen": ("noun", "exam", "het"),
    "exclusief": ("adjective", "exclusive", None),
    "excuus": ("noun", "excuse", "het"),
    "expeditie": ("noun", "expedition", "de"),
    "experiment": ("noun", "experiment", "het"),
    "experimenteel": ("adjective", "experimental", None),
    "experimenteren": ("verb", "to experiment", None),
    "expliciet": ("adjective", "explicit", None),
    "explosie": ("noun", "explosion", "de"),
    "extern": ("adjective", "external", None),
    "extra": ("adjective", "extra", None),
    "extreem": ("adjective", "extreme", None),
    "ezel": ("noun", "donkey", "de"),
    "fabriek": ("noun", "factory", "de"),
    "fabrikant": ("noun", "manufacturer", "de"),
    "factor": ("noun", "factor", "de"),
    "faculteit": ("noun", "faculty", "de"),
    "fantastisch": ("adjective", "fantastic", None),
    "farao": ("noun", "pharaoh", "de"),
    "fascineren": ("verb", "to fascinate", None),
    "fataal": ("adjective", "fatal", None),
    "fatsoenlijk": ("adjective", "decent", None),
    "fauteuil": ("noun", "armchair", "de"),
    "feest": ("noun", "party", "het"),
    "feestelijk": ("adjective", "festive", None),
    "fel": ("adjective", "fierce", None),
    "fenomeen": ("noun", "phenomenon", "het"),
    "fiets": ("noun", "bicycle", "de"),
    "fietsen": ("verb", "to cycle", None),
    "fijn": ("adjective", "fine", None),
    "film": ("noun", "film", "de"),
    "filosofisch": ("adjective", "philosophical", None),
    "financiën": ("noun", "finances", "de"),
    "flard": ("noun", "shred", "de"),
    "fles": ("noun", "bottle", "de"),
    "flink": ("adjective", "considerable", None),
    "flitsen": ("verb", "to flash", None),
    "fluisteren": ("verb", "to whisper", None),
    "fonds": ("noun", "fund", "het"),
    "formule": ("noun", "formula", "de"),
    "formulering": ("noun", "formulation", "de"),
    "fors": ("adjective", "sturdy", None),
    "fort": ("noun", "fort", "het"),
    "fotograaf": ("noun", "photographer", "de"),
    "fotograferen": ("verb", "to photograph", None),
    "fraai": ("adjective", "beautiful", None),
    "fragment": ("noun", "fragment", "het"),
    "fronsen": ("verb", "to frown", None),
    "fruit": ("noun", "fruit", "het"),
    "frustratie": ("noun", "frustration", "de"),
    "functionaris": ("noun", "official", "de"),
    "functioneel": ("adjective", "functional", None),
    "fundamenteel": ("adjective", "fundamental", None),
    "fungeren": ("verb", "to function as", None),
    "gadeslaan": ("verb", "to observe", None),
    "gangbaar": ("adjective", "common", None),
    "gans": ("noun", "goose", "de"),
    "gapen": ("verb", "to yawn", None),
    "garage": ("noun", "garage", "de"),
    "garanderen": ("verb", "to guarantee", None),
    "garantie": ("noun", "guarantee", "de"),
    "gat": ("noun", "hole", "het"),
    "gave": ("noun", "gift", "de"),
    "gebaar": ("noun", "gesture", "het"),
    "gebaren": ("verb", "to gesture", None),
    "gebieden": ("verb", "to command", None),
    "gebit": ("noun", "teeth", "het"),
    "gebod": ("noun", "commandment", "het"),
    "geboorte": ("noun", "birth", "de"),
    "geboren": ("adjective", "born", None),
    "gebrekkig": ("adjective", "deficient", None),
    "gebroken": ("adjective", "broken", None),
    "gebruikelijk": ("adjective", "usual", None),
    "gecompliceerd": ("adjective", "complicated", None),
    "gedaante": ("noun", "figure", "de"),
    "gedeeltelijk": ("adjective", "partial", None),
    "gedicht": ("noun", "poem", "het"),
    "geding": ("noun", "dispute", "het"),
    "gedoe": ("noun", "fuss", "het"),
    "gedragen": ("verb", "to behave", None),
    "gedreven": ("adjective", "driven", None),
    "geduldig": ("adjective", "patient", None),
    "geestelijk": ("adjective", "spiritual", None),
    "geestelijke": ("noun", "clergyman", "de"),
    "geheugen": ("noun", "memory", "het"),
    "gehoor": ("noun", "hearing", "het"),
    "gehoorzamen": ("verb", "to obey", None),
    "geit": ("noun", "goat", "de"),
    "gelaat": ("noun", "face", "het"),
    "geleerd": ("adjective", "learned", None),
    "geleerde": ("noun", "scholar", "de"),
    "gelegen": ("adjective", "situated", None),
    "geliefd": ("adjective", "beloved", None),
    "gelijk": ("adjective", "equal", None),
    "gelijke": ("noun", "equal", "de"),
    "gelijken": ("verb", "to resemble", None),
    "gelijkenis": ("noun", "resemblance", "de"),
    "gelijktijdig": ("adjective", "simultaneous", None),
    "gelovige": ("noun", "believer", "de"),
    "gemak": ("noun", "comfort", "het"),
    "gemeen": ("adjective", "mean", None),
    "gemeenschap": ("noun", "community", "de"),
    "gemeenschappelijk": ("adjective", "communal", None),
    "gemeentebestuur": ("noun", "municipal government", "het"),
    "gemeentelijk": ("adjective", "municipal", None),
    "gemeenteraad": ("noun", "municipal council", "de"),
    "gemengd": ("adjective", "mixed", None),
    "gemiddelde": ("noun", "average", "het"),
    "genade": ("noun", "mercy", "de"),
    "geneeskunde": ("noun", "medicine", "de"),
    "genegenheid": ("noun", "affection", "de"),
    "geneigd": ("adjective", "inclined", None),
    "generaal": ("noun", "general", "de"),
    "genetisch": ("adjective", "genetic", None),
    "genezen": ("verb", "to heal", None),
    "genie": ("noun", "genius", "het"),
    "gepaard": ("adjective", "paired", None),
    "gereedschap": ("noun", "tools", "het"),
    "gering": ("adjective", "slight", None),
    "gerucht": ("noun", "rumor", "het"),
    "geruim": ("adjective", "considerable", None),
    "geruststellen": ("verb", "to reassure", None),
    "geschenk": ("noun", "gift", "het"),
    "geslaagd": ("adjective", "successful", None),
    "gesloten": ("adjective", "closed", None),
    "gesteld": ("adjective", "disposed", None),
    "getekend": ("adjective", "marked", None),
    "getuigenis": ("noun", "testimony", "de"),
    "geur": ("noun", "scent", "de"),
    "geuren": ("verb", "to smell", None),
    "gevangen": ("adjective", "captive", None),
    "gevel": ("noun", "facade", "de"),
    "gevestigd": ("adjective", "established", None),
    "gevoelen": ("verb", "to feel", None),
    "gewaarwording": ("noun", "sensation", "de"),
    "geweer": ("noun", "rifle", "het"),
    "gewest": ("noun", "region", "het"),
    "gewijd": ("adjective", "devoted", None),
    "gewoonlijk": ("adjective", "usual", None),
    "gezellig": ("adjective", "cozy", None),
    "gezelschap": ("noun", "company", "het"),
    "gezet": ("adjective", "stout", None),
    "gezichtspunt": ("noun", "viewpoint", "het"),
    "gezien": ("adjective", "seen", None),
    "gezocht": ("adjective", "sought-after", None),
    "gezondheidszorg": ("noun", "healthcare", "de"),
    "geïnteresseerd": ("adjective", "interested", None),
    "gids": ("noun", "guide", "de"),
    "giechelen": ("verb", "to giggle", None),
    "gieren": ("verb", "to screech", None),
    "giftig": ("adjective", "poisonous", None),
    "gigantisch": ("adjective", "gigantic", None),
    "glans": ("noun", "shine", "de"),
    "glanzen": ("verb", "to shine", None),
    "glijden": ("verb", "to slide", None),
    "glimlach": ("noun", "smile", "de"),
    "glinsteren": ("verb", "to glitter", None),
    "globaal": ("adjective", "global", None),
    "gloed": ("noun", "glow", "de"),
    "glorie": ("noun", "glory", "de"),
    "gluren": ("verb", "to peek", None),
    "godheid": ("noun", "deity", "de"),
    "godsdienst": ("noun", "religion", "de"),
    "goederen": ("noun", "goods", "de"),
    "goedheid": ("noun", "goodness", "de"),
    "goedkeuren": ("verb", "to approve", None),
    "goedkeuring": ("noun", "approval", "de"),
    "golf": ("noun", "wave", "de"),
    "golven": ("verb", "to wave", None),
    "gooien": ("verb", "to throw", None),
    "gordijn": ("noun", "curtain", "het"),
    "gouden": ("adjective", "golden", None),
    "gouverneur": ("noun", "governor", "de"),
    "graan": ("noun", "grain", "het"),
    "gracht": ("noun", "canal", "de"),
    "gram": ("noun", "gram", "het"),
    "grappig": ("adjective", "funny", None),
    "gras": ("noun", "grass", "het"),
    "gratie": ("noun", "grace", "de"),
    "gratis": ("adjective", "free", None),
    "greep": ("noun", "grip", "de"),
    "grenzen": ("verb", "to border", None),
    "gretig": ("adjective", "eager", None),
    "griezelig": ("adjective", "creepy", None),
    "grijns": ("noun", "grin", "de"),
    "grijpen": ("verb", "to grab", None),
    "grijs": ("adjective", "grey", None),
    "grillig": ("adjective", "capricious", None),
    "grimmig": ("adjective", "grim", None),
    "groen": ("adjective", "green", None),
    "groepering": ("noun", "grouping", "de"),
    "groet": ("noun", "greeting", "de"),
    "grondslag": ("noun", "foundation", "de"),
    "grondstof": ("noun", "raw material", "de"),
    "grondwet": ("noun", "constitution", "de"),
    "groots": ("adjective", "grand", None),
    "grot": ("noun", "cave", "de"),
    "gruwelijk": ("adjective", "gruesome", None),
    "gunstig": ("adjective", "favorable", None),
    "haak": ("noun", "hook", "de"),
    "haan": ("noun", "rooster", "de"),
    "haard": ("noun", "fireplace", "de"),
    "haast": ("noun", "haste", "de"),
    "hak": ("noun", "heel", "de"),
    "haken": ("verb", "to hook", None),
    "hakken": ("verb", "to chop", None),
    "hals": ("noun", "neck", "de"),
    "ham": ("noun", "ham", "de"),
    "handdoek": ("noun", "towel", "de"),
    "handel": ("noun", "trade", "de"),
    "handelaar": ("noun", "trader", "de"),
    "handhaven": ("verb", "to maintain", None),
    "handpalm": ("noun", "palm of the hand", "de"),
    "handschoen": ("noun", "glove", "de"),
    "handschrift": ("noun", "handwriting", "het"),
    "hardnekkig": ("adjective", "stubborn", None),
    "harmonie": ("noun", "harmony", "de"),
    "hartstocht": ("noun", "passion", "de"),
    "hartstochtelijk": ("adjective", "passionate", None),
    "hebben": ("verb", "to have", None),
    "hecht": ("adjective", "close-knit", None),
    "heden": ("noun", "present", "het"),
    "hedendaags": ("adjective", "contemporary", None),
    "heel": ("adjective", "whole", None),
    "heelal": ("noun", "universe", "het"),
    "heengaan": ("verb", "to pass away", None),
    "heer": ("noun", "gentleman", "de"),
    "heerlijk": ("adjective", "delightful", None),
    "heersen": ("verb", "to rule", None),
    "heet": ("adjective", "hot", None),
    "heil": ("noun", "salvation", "het"),
    "heilig": ("adjective", "holy", None),
    "heilige": ("noun", "saint", "de"),
    "heimelijk": ("adjective", "secret", None),
    "heimwee": ("noun", "homesickness", "het"),
    "hekel": ("noun", "dislike", "de"),
    "heks": ("noun", "witch", "de"),
    "hel": ("noun", "hell", "de"),
    "helder": ("adjective", "clear", None),
    "heleboel": ("noun", "whole lot", "de"),
    "helm": ("noun", "helmet", "de"),
    "hemels": ("adjective", "heavenly", None),
    "herfst": ("noun", "autumn", "de"),
    "herhaling": ("noun", "repetition", "de"),
    "herkomst": ("noun", "origin", "de"),
    "hersens": ("noun", "brains", "de"),
    "hervorming": ("noun", "reform", "de"),
    "heten": ("verb", "to be called", None),
    "heuvel": ("noun", "hill", "de"),
    "hevig": ("adjective", "fierce", None),
    "hiel": ("noun", "heel", "de"),
    "hijsen": ("verb", "to hoist", None),
    "hinderen": ("verb", "to hinder", None),
    "hinderlijk": ("adjective", "annoying", None),
    "historicus": ("noun", "historian", "de"),
    "hiërarchie": ("noun", "hierarchy", "de"),
    "hiërarchisch": ("adjective", "hierarchical", None),
    "hoed": ("noun", "hat", "de"),
    "hoede": ("noun", "guard", "de"),
    "hoer": ("noun", "prostitute", "de"),
    "hoesten": ("verb", "to cough", None),
    "hoeve": ("noun", "farm", "de"),
    "hoeveelheid": ("noun", "quantity", "de"),
    "hoeven": ("verb", "to need to", None),
    "hok": ("noun", "cage", "het"),
    "homoseksualiteit": ("noun", "homosexuality", "de"),
    "homoseksueel": ("adjective", "homosexual", None),
    "honing": ("noun", "honey", "de"),
    "hoofdkwartier": ("noun", "headquarters", "het"),
    "hoofdpijn": ("noun", "headache", "de"),
    "hoofdzakelijk": ("adjective", "mainly", None),
    "hoogleraar": ("noun", "professor", "de"),
    "hoogtepunt": ("noun", "highlight", "het"),
    "hoorn": ("noun", "horn", "de"),
    "hopeloos": ("adjective", "hopeless", None),
    "hopen": ("verb", "to hope", None),
    "horizontaal": ("adjective", "horizontal", None),
    "houvast": ("noun", "hold", "het"),
    "huid": ("noun", "skin", "de"),
    "huidig": ("adjective", "current", None),
    "huilen": ("verb", "to cry", None),
    "huisarts": ("noun", "family doctor", "de"),
    "huiskamer": ("noun", "living room", "de"),
    "huiveren": ("verb", "to shiver", None),
    "hullen": ("verb", "to wrap", None),
    "hulpeloos": ("adjective", "helpless", None),
    "hulpmiddel": ("noun", "aid", "het"),
    "hulpverlener": ("noun", "aid worker", "de"),
    "humanistisch": ("adjective", "humanistic", None),
    "humor": ("noun", "humor", "de"),
    "hurken": ("verb", "to squat", None),
    "huur": ("noun", "rent", "de"),
    "hypothese": ("noun", "hypothesis", "de"),
    "identiek": ("adjective", "identical", None),
    "identificeren": ("verb", "to identify", None),
    "ideologie": ("noun", "ideology", "de"),
    "idioot": ("noun", "idiot", "de"),
    "ijl": ("adjective", "thin", None),
    "ijskoud": ("adjective", "ice-cold", None),
    "ijverig": ("adjective", "diligent", None),
    "ijzer": ("noun", "iron", "het"),
    "illegaal": ("adjective", "illegal", None),
    "illustratie": ("noun", "illustration", "de"),
    "illustreren": ("verb", "to illustrate", None),
    "impliceren": ("verb", "to imply", None),
    "impuls": ("noun", "impulse", "de"),
    "inbrengen": ("verb", "to bring in", None),
    "incident": ("noun", "incident", "het"),
    "inclusief": ("adjective", "inclusive", None),
    "indelen": ("verb", "to classify", None),
    "indiaan": ("noun", "Native American", "de"),
    "indienen": ("verb", "to submit", None),
    "indirect": ("adjective", "indirect", None),
    "individu": ("noun", "individual", "het"),
    "individueel": ("adjective", "individual", None),
    "infectie": ("noun", "infection", "de"),
    "ingaan": ("verb", "to enter", None),
    "ingenieur": ("noun", "engineer", "de"),
    "ingewikkeld": ("adjective", "complex", None),
    "ingreep": ("noun", "intervention", "de"),
    "inheems": ("adjective", "indigenous", None),
    "inhoudelijk": ("adjective", "substantive", None),
    "inhouden": ("verb", "to contain", None),
    "initiatief": ("noun", "initiative", "het"),
    "inkomsten": ("noun", "income", "de"),
    "inlichten": ("verb", "to inform", None),
    "inlichting": ("noun", "information", "de"),
    "innemen": ("verb", "to take in", None),
    "innerlijk": ("adjective", "inner", None),
    "innig": ("adjective", "intimate", None),
    "inrichting": ("noun", "arrangement", "de"),
    "inschakelen": ("verb", "to engage", None),
    "insect": ("noun", "insect", "het"),
    "inslaan": ("verb", "to stock up", None),
    "inspecteur": ("noun", "inspector", "de"),
    "inspiratie": ("noun", "inspiration", "de"),
    "inspireren": ("verb", "to inspire", None),
    "inspraak": ("noun", "say", "de"),
    "installeren": ("verb", "to install", None),
    "instantie": ("noun", "authority", "de"),
    "instemming": ("noun", "consent", "de"),
    "instinct": ("noun", "instinct", "het"),
    "instinctief": ("adjective", "instinctive", None),
    "instrument": ("noun", "instrument", "het"),
    "integraal": ("adjective", "integral", None),
    "integratie": ("noun", "integration", "de"),
    "integreren": ("verb", "to integrate", None),
    "intensiteit": ("noun", "intensity", "de"),
    "interactie": ("noun", "interaction", "de"),
    "interesseren": ("verb", "to interest", None),
    "intern": ("adjective", "internal", None),
    "intiem": ("adjective", "intimate", None),
    "intrekken": ("verb", "to withdraw", None),
    "introduceren": ("verb", "to introduce", None),
    "intuïtie": ("noun", "intuition", "de"),
    "inval": ("noun", "raid", "de"),
    "investering": ("noun", "investment", "de"),
    "invullen": ("verb", "to fill in", None),
    "inwendig": ("adjective", "internal", None),
    "inzetten": ("verb", "to deploy", None),
    "ironie": ("noun", "irony", "de"),
    "ironisch": ("adjective", "ironic", None),
    "irriteren": ("verb", "to irritate", None),
    "islam": ("noun", "Islam", "de"),
    "isoleren": ("verb", "to isolate", None),
    "jack": ("noun", "jacket", "het"),
    "jager": ("noun", "hunter", "de"),
    "jaguar": ("noun", "jaguar", "de"),
    "jaloezie": ("noun", "jealousy", "de"),
    "janken": ("verb", "to whine", None),
    "japon": ("noun", "dress", "de"),
    "jas": ("noun", "coat", "de"),
    "jeugdig": ("adjective", "youthful", None),
    "jongeman": ("noun", "young man", "de"),
    "jood": ("noun", "Jew", "de"),
    "juichen": ("verb", "to cheer", None),
    "jurk": ("noun", "dress", "de"),
    "juweel": ("noun", "jewel", "het"),
    "kaak": ("noun", "jaw", "de"),
    "kaars": ("noun", "candle", "de"),
    "kaas": ("noun", "cheese", "de"),
    "kabel": ("noun", "cable", "de"),
    "kachel": ("noun", "stove", "de"),
    "kade": ("noun", "quay", "de"),
    "kader": ("noun", "framework", "het"),
    "kalk": ("noun", "lime", "de"),
    "kalm": ("adjective", "calm", None),
    "kalmeren": ("verb", "to calm down", None),
    "kandidaat": ("noun", "candidate", "de"),
    "kanker": ("noun", "cancer", "de"),
    "kanon": ("noun", "cannon", "het"),
    "kapel": ("noun", "chapel", "de"),
    "kapitalisme": ("noun", "capitalism", "het"),
    "kapitalistisch": ("adjective", "capitalist", None),
    "kapitein": ("noun", "captain", "de"),
    "kapot": ("adjective", "broken", None),
    "kar": ("noun", "cart", "de"),
    "karakteristiek": ("adjective", "characteristic", None),
    "karwei": ("noun", "chore", "het"),
    "kas": ("noun", "greenhouse", "de"),
    "kast": ("noun", "cupboard", "de"),
    "kater": ("noun", "hangover", "de"),
    "kathedraal": ("noun", "cathedral", "de"),
    "katholiek": ("adjective", "Catholic", None),
    "kauwen": ("verb", "to chew", None),
    "keel": ("noun", "throat", "de"),
    "keer": ("noun", "time", "de"),
    "kei": ("noun", "boulder", "de"),
    "kelner": ("noun", "waiter", "de"),
    "kenbaar": ("adjective", "recognizable", None),
    "kenmerk": ("noun", "characteristic", "het"),
    "kenmerkend": ("adjective", "characteristic", None),
    "kennelijk": ("adjective", "apparent", None),
    "kerel": ("noun", "fellow", "de"),
    "kerkhof": ("noun", "cemetery", "het"),
    "kerstmis": ("noun", "Christmas", "het"),
    "keten": ("noun", "chain", "de"),
    "ketter": ("noun", "heretic", "de"),
    "ketting": ("noun", "necklace", "de"),
    "keuren": ("verb", "to inspect", None),
    "keurig": ("adjective", "neat", None),
    "keus": ("noun", "choice", "de"),
    "kier": ("noun", "crack", "de"),
    "kiezen": ("verb", "to choose", None),
    "kiezer": ("noun", "voter", "de"),
    "kijk": ("noun", "view", "de"),
    "kijker": ("noun", "viewer", "de"),
    "kil": ("adjective", "chilly", None),
    "kilo": ("noun", "kilo", "de"),
    "kilometer": ("noun", "kilometer", "de"),
    "kin": ("noun", "chin", "de"),
    "kinderlijk": ("adjective", "childlike", None),
    "kip": ("noun", "chicken", "de"),
    "kist": ("noun", "chest", "de"),
    "klaar": ("adjective", "ready", None),
    "klaarblijkelijk": ("adjective", "obvious", None),
    "klaarmaken": ("verb", "to prepare", None),
    "klagen": ("verb", "to complain", None),
    "klappen": ("verb", "to clap", None),
    "klassiek": ("adjective", "classical", None),
    "kleine": ("adjective", "small", None),
    "klemmen": ("verb", "to clamp", None),
    "kleren": ("noun", "clothes", "de"),
    "kletsen": ("verb", "to chat", None),
    "kleuren": ("verb", "to color", None),
    "kleurig": ("adjective", "colorful", None),
    "kleuter": ("noun", "toddler", "de"),
    "kleven": ("verb", "to stick", None),
    "kliniek": ("noun", "clinic", "de"),
    "klok": ("noun", "clock", "de"),
    "kloof": ("noun", "gap", "de"),
    "knaap": ("noun", "boy", "de"),
    "knap": ("adjective", "handsome", None),
    "knecht": ("noun", "servant", "de"),
    "knielen": ("verb", "to kneel", None),
    "knijpen": ("verb", "to pinch", None),
    "knikken": ("verb", "to nod", None),
    "knippen": ("verb", "to cut", None),
    "knipperen": ("verb", "to blink", None),
    "knoflook": ("noun", "garlic", "het"),
    "knop": ("noun", "button", "de"),
    "knopen": ("verb", "to tie", None),
    "koe": ("noun", "cow", "de"),
    "koel": ("adjective", "cool", None),
    "koepel": ("noun", "dome", "de"),
    "koesteren": ("verb", "to cherish", None),
    "koffer": ("noun", "suitcase", "de"),
    "koffie": ("noun", "coffee", "de"),
    "kogel": ("noun", "bullet", "de"),
    "kolonel": ("noun", "colonel", "de"),
    "kom": ("noun", "bowl", "de"),
    "komst": ("noun", "arrival", "de"),
    "konijn": ("noun", "rabbit", "het"),
    "koningin": ("noun", "queen", "de"),
    "kooi": ("noun", "cage", "de"),
    "koop": ("noun", "purchase", "de"),
    "koopman": ("noun", "merchant", "de"),
    "koor": ("noun", "choir", "het"),
    "koorts": ("noun", "fever", "de"),
    "koper": ("noun", "copper", "het"),
    "koperen": ("adjective", "copper", None),
    "kopie": ("noun", "copy", "de"),
    "koppelen": ("verb", "to connect", None),
    "koppig": ("adjective", "stubborn", None),
    "korporaal": ("noun", "corporal", "de"),
    "korst": ("noun", "crust", "de"),
    "kosmisch": ("adjective", "cosmic", None),
    "kost": ("noun", "cost", "de"),
    "kostbaar": ("adjective", "precious", None),
    "kostuum": ("noun", "costume", "het"),
    "kou": ("noun", "cold", "de"),
    "kous": ("noun", "stocking", "de"),
    "kraag": ("noun", "collar", "de"),
    "kraan": ("noun", "tap", "de"),
    "krabben": ("verb", "to scratch", None),
    "kraken": ("verb", "to crack", None),
    "krampachtig": ("adjective", "convulsive", None),
    "krankzinnig": ("adjective", "insane", None),
    "kreet": ("noun", "cry", "de"),
    "kreunen": ("verb", "to groan", None),
    "krijger": ("noun", "warrior", "de"),
    "krijsen": ("verb", "to shriek", None),
    "krimpen": ("verb", "to shrink", None),
    "kring": ("noun", "circle", "de"),
    "kroeg": ("noun", "pub", "de"),
    "kronkelen": ("verb", "to wind", None),
    "kruid": ("noun", "herb", "het"),
    "kruisen": ("verb", "to cross", None),
    "krul": ("noun", "curl", "de"),
    "kudde": ("noun", "herd", "de"),
    "kuil": ("noun", "pit", "de"),
    "kunnen": ("verb", "to be able to", None),
    "kunstwerk": ("noun", "work of art", "het"),
    "kus": ("noun", "kiss", "de"),
    "kussen": ("noun", "pillow", "het"),
    "kwaal": ("noun", "ailment", "de"),
    "kwalijk": ("adjective", "wrong", None),
    "kweken": ("verb", "to cultivate", None),
    "kwellen": ("verb", "to torment", None),
    "kwetsbaar": ("adjective", "vulnerable", None),
    "kwetsen": ("verb", "to hurt", None),
    "kwijt": ("adjective", "lost", None),
    "kwijtraken": ("verb", "to lose", None),
}
