WORDS = {
    "saai": ("adjective", "boring", None),
    "salaris": ("noun", "salary", "het"),
    "salon": ("noun", "salon, living room", "de"),
    "samen": ("adjective", "together", None),
    "samenhang": ("noun", "coherence, connection", "de"),
    "samenhangen": ("verb", "to be connected", None),
    "samenvatten": ("verb", "to summarize", None),
    "sanctie": ("noun", "sanction", "de"),
    "saus": ("noun", "sauce", "de"),
    "schaal": ("noun", "scale; bowl", "de"),
    "schaamte": ("noun", "shame", "de"),
    "schaap": ("noun", "sheep", "het"),
    "schaars": ("adjective", "scarce", None),
    "schade": ("noun", "damage", "de"),
    "schakelen": ("verb", "to switch; to shift", None),
    "schatting": ("noun", "estimate", "de"),
    "schedel": ("noun", "skull", "de"),
    "scheef": ("adjective", "crooked, slanted", None),
    "scheiden": ("verb", "to separate; to divorce", None),
    "schelen": ("verb", "to matter; to differ", None),
    "schema": ("noun", "scheme, schedule", "het"),
    "schemering": ("noun", "twilight, dusk", "de"),
    "schepping": ("noun", "creation", "de"),
    "scheren": ("verb", "to shave", None),
    "scherm": ("noun", "screen", "het"),
    "schets": ("noun", "sketch", "de"),
    "schetsen": ("verb", "to sketch; to outline", None),
    "scheuren": ("verb", "to tear", None),
    "schijn": ("noun", "appearance; shine", "de"),
    "schijnbaar": ("adjective", "apparently", None),
    "schijnen": ("verb", "to seem; to shine", None),
    "schikken": ("verb", "to arrange; to settle", None),
    "schilder": ("noun", "painter", "de"),
    "schildering": ("noun", "painting, depiction", "de"),
    "schitteren": ("verb", "to sparkle, to shine", None),
    "schitterend": ("adjective", "splendid, brilliant", None),
    "schoen": ("noun", "shoe", "de"),
    "schok": ("noun", "shock", "de"),
    "schokken": ("verb", "to shock; to shake", None),
    "schommelen": ("verb", "to swing; to fluctuate", None),
    "schoonmaken": ("verb", "to clean", None),
    "schoot": ("noun", "lap", "de"),
    "schoppen": ("verb", "to kick", None),
    "schot": ("noun", "shot; partition", "het"),
    "schotel": ("noun", "dish, saucer", "de"),
    "schreien": ("verb", "to cry, to weep", None),
    "schriftelijk": ("adjective", "written", None),
    "schrik": ("noun", "fright", "de"),
    "schudden": ("verb", "to shake", None),
    "schuilen": ("verb", "to shelter, to hide", None),
    "schuilplaats": ("noun", "shelter", "de"),
    "schuin": ("adjective", "slanted, diagonal", None),
    "schuiven": ("verb", "to slide, to push", None),
    "schuur": ("noun", "barn, shed", "de"),
    "seconde": ("noun", "second", "de"),
    "secretaresse": ("noun", "secretary (female)", "de"),
    "secretaris": ("noun", "secretary", "de"),
    "sectie": ("noun", "section", "de"),
    "seizoen": ("noun", "season", "het"),
    "seks": ("noun", "sex", "de"),
    "seksueel": ("adjective", "sexual", None),
    "selecteren": ("verb", "to select", None),
    "selectie": ("noun", "selection", "de"),
    "sensatie": ("noun", "sensation", "de"),
    "serie": ("noun", "series", "de"),
    "serieus": ("adjective", "serious", None),
    "serveren": ("verb", "to serve", None),
    "sierlijk": ("adjective", "graceful, elegant", None),
    "sigaar": ("noun", "cigar", "de"),
    "sigaret": ("noun", "cigarette", "de"),
    "signaleren": ("verb", "to signal; to notice", None),
    "simpel": ("adjective", "simple", None),
    "slaaf": ("noun", "slave", "de"),
    "slaapkamer": ("noun", "bedroom", "de"),
    "slang": ("noun", "snake; hose", "de"),
    "slank": ("adjective", "slim, slender", None),
    "slap": ("adjective", "weak; limp", None),
    "slaperig": ("adjective", "sleepy", None),
    "slavernij": ("noun", "slavery", "de"),
    "slepen": ("verb", "to drag", None),
    "slikken": ("verb", "to swallow", None),
    "slingeren": ("verb", "to swing; to wind", None),
    "slok": ("noun", "sip, gulp", "de"),
    "sloot": ("noun", "ditch", "de"),
    "slordig": ("adjective", "sloppy, messy", None),
    "sluipen": ("verb", "to sneak", None),
    "smaken": ("verb", "to taste", None),
    "smeken": ("verb", "to beg, to plead", None),
    "smeren": ("verb", "to spread; to lubricate", None),
    "smerig": ("adjective", "dirty, filthy", None),
    "snappen": ("verb", "to understand; to catch", None),
    "sneeuw": ("noun", "snow", "de"),
    "sneuvelen": ("verb", "to be killed (in battle)", None),
    "socialisme": ("noun", "socialism", "het"),
    "socialist": ("noun", "socialist", "de"),
    "socialistisch": ("adjective", "socialist", None),
    "soep": ("noun", "soup", "de"),
    "solidariteit": ("noun", "solidarity", "de"),
    "som": ("noun", "sum", "de"),
    "somber": ("adjective", "gloomy, somber", None),
    "spannen": ("verb", "to stretch; to tense", None),
    "specialist": ("noun", "specialist", "de"),
    "specifiek": ("adjective", "specific", None),
    "speelgoed": ("noun", "toys", "het"),
    "speels": ("adjective", "playful", None),
    "spoedig": ("adjective", "soon, speedy", None),
    "spontaan": ("adjective", "spontaneous", None),
    "spook": ("noun", "ghost", "het"),
    "sporen": ("verb", "to trace; to spur", None),
    "spot": ("noun", "mockery", "de"),
    "spotten": ("verb", "to mock", None),
    "spreiden": ("verb", "to spread", None),
    "sprong": ("noun", "jump, leap", "de"),
    "sprookje": ("noun", "fairy tale", "het"),
    "spuiten": ("verb", "to spray; to inject", None),
    "staal": ("noun", "steel", "het"),
    "staatssecretaris": ("noun", "state secretary", "de"),
    "stal": ("noun", "stable", "de"),
    "stammen": ("verb", "to originate, to stem from", None),
    "stand": ("noun", "position; score", "de"),
    "stank": ("noun", "stench", "de"),
    "stapel": ("noun", "pile, stack", "de"),
    "star": ("adjective", "rigid, stiff", None),
    "staren": ("verb", "to stare", None),
    "start": ("noun", "start", "de"),
    "starten": ("verb", "to start", None),
    "station": ("noun", "station", "het"),
    "status": ("noun", "status", "de"),
    "stedelijk": ("adjective", "urban", None),
    "steek": ("noun", "stitch; stab", "de"),
    "steil": ("adjective", "steep", None),
    "stel": ("noun", "couple; set", "het"),
    "stellig": ("adjective", "definite, emphatic", None),
    "stempel": ("noun", "stamp", "de"),
    "sterkte": ("noun", "strength", "de"),
    "stevig": ("adjective", "firm, sturdy", None),
    "stiekem": ("adjective", "sneaky, secretly", None),
    "stier": ("noun", "bull", "de"),
    "stijf": ("adjective", "stiff", None),
    "stikken": ("verb", "to choke; to stitch", None),
    "stilstaan": ("verb", "to stand still", None),
    "stilstand": ("noun", "standstill", "de"),
    "stimuleren": ("verb", "to stimulate", None),
    "stinken": ("verb", "to stink", None),
    "stoep": ("noun", "sidewalk; doorstep", "de"),
    "stoornis": ("noun", "disorder", "de"),
    "stormen": ("verb", "to storm", None),
    "storten": ("verb", "to pour; to deposit; to crash", None),
    "stoten": ("verb", "to bump, to push", None),
    "straal": ("noun", "ray; beam; jet", "de"),
    "strak": ("adjective", "tight; taut", None),
    "stralend": ("adjective", "radiant, beaming", None),
    "straling": ("noun", "radiation", "de"),
    "strand": ("noun", "beach", "het"),
    "strategisch": ("adjective", "strategic", None),
    "streep": ("noun", "stripe; line", "de"),
    "strekking": ("noun", "purport, meaning", "de"),
    "strelen": ("verb", "to caress, to stroke", None),
    "streng": ("adjective", "strict, severe", None),
    "strijken": ("verb", "to iron; to stroke", None),
    "stromen": ("verb", "to flow, to stream", None),
    "stroming": ("noun", "current; movement", "de"),
    "structureel": ("adjective", "structural", None),
    "struik": ("noun", "bush, shrub", "de"),
    "struikelen": ("verb", "to stumble", None),
    "stuur": ("noun", "steering wheel", "het"),
    "subjectief": ("adjective", "subjective", None),
    "subsidie": ("noun", "subsidy", "de"),
    "subtiel": ("adjective", "subtle", None),
    "succesvol": ("adjective", "successful", None),
    "suggestie": ("noun", "suggestion", "de"),
    "suiker": ("noun", "sugar", "de"),
    "symbolisch": ("adjective", "symbolic", None),
    "sympathiek": ("adjective", "likeable, nice", None),
    "symptoom": ("noun", "symptom", "het"),
    "systematisch": ("adjective", "systematic", None),
    "taai": ("adjective", "tough", None),
    "tabak": ("noun", "tobacco", "de"),
    "tabel": ("noun", "table, chart", "de"),
    "tafereel": ("noun", "scene", "het"),
    "tal": ("noun", "number (of)", "het"),
    "talent": ("noun", "talent", "het"),
    "talloos": ("adjective", "countless", None),
    "talrijk": ("adjective", "numerous", None),
    "tandarts": ("noun", "dentist", "de"),
    "tapijt": ("noun", "carpet", "het"),
    "tas": ("noun", "bag", "de"),
    "tasten": ("verb", "to feel, to grope", None),
    "taxi": ("noun", "taxi", "de"),
    "team": ("noun", "team", "het"),
    "teder": ("adjective", "tender", None),
    "tegendeel": ("noun", "opposite", "het"),
    "tegenhouden": ("verb", "to stop, to hold back", None),
    "tegenkomen": ("verb", "to encounter, to meet", None),
    "tegenzin": ("noun", "reluctance", "de"),
    "teleurstellen": ("verb", "to disappoint", None),
    "televisie": ("noun", "television", "de"),
    "tempo": ("noun", "pace, tempo", "het"),
    "tendens": ("noun", "tendency, trend", "de"),
    "terecht": ("adjective", "justified; rightly", None),
    "terechtkomen": ("verb", "to end up", None),
    "term": ("noun", "term", "de"),
    "termijn": ("noun", "term, period", "de"),
    "terras": ("noun", "terrace", "het"),
    "terugbrengen": ("verb", "to bring back", None),
    "teruggaan": ("verb", "to go back", None),
    "terugkeer": ("noun", "return", "de"),
    "terugkomen": ("verb", "to come back", None),
    "terugvinden": ("verb", "to find back", None),
    "test": ("noun", "test", "de"),
    "testament": ("noun", "testament, will", "het"),
    "teweegbrengen": ("verb", "to bring about, to cause", None),
    "thee": ("noun", "tea", "de"),
    "theologie": ("noun", "theology", "de"),
    "theologisch": ("adjective", "theological", None),
    "theoretisch": ("adjective", "theoretical", None),
    "therapeut": ("noun", "therapist", "de"),
    "therapie": ("noun", "therapy", "de"),
    "thuiskomen": ("verb", "to come home", None),
    "tijdig": ("adjective", "timely", None),
    "tijdstip": ("noun", "moment, point in time", "het"),
    "tikken": ("verb", "to tap; to type", None),
    "tillen": ("verb", "to lift", None),
    "timmeren": ("verb", "to build (with wood); to hammer", None),
    "tint": ("noun", "tint, shade", "de"),
    "titel": ("noun", "title", "de"),
    "toegankelijk": ("adjective", "accessible", None),
    "toegeven": ("verb", "to admit; to give in", None),
    "toekennen": ("verb", "to award, to grant", None),
    "toelichting": ("noun", "explanation", "de"),
    "toename": ("noun", "increase", "de"),
    "toenmalig": ("adjective", "then, at that time", None),
    "toerist": ("noun", "tourist", "de"),
    "toeschouwer": ("noun", "spectator", "de"),
    "toespraak": ("noun", "speech", "de"),
    "toestaan": ("verb", "to allow, to permit", None),
    "toestel": ("noun", "device; phone", "het"),
    "toetsen": ("verb", "to test", None),
    "toeval": ("noun", "coincidence, chance", "het"),
    "toevallig": ("adjective", "coincidental; by chance", None),
    "toevertrouwen": ("verb", "to entrust", None),
    "toevoegen": ("verb", "to add", None),
    "toewijzen": ("verb", "to assign, to allocate", None),
    "toezicht": ("noun", "supervision", "het"),
    "toilet": ("noun", "toilet", "het"),
    "totaal": ("adjective", "total", None),
    "touw": ("noun", "rope", "het"),
    "traag": ("adjective", "slow, sluggish", None),
    "tragisch": ("adjective", "tragic", None),
    "training": ("noun", "training", "de"),
    "tram": ("noun", "tram", "de"),
    "transport": ("noun", "transport", "het"),
    "trap": ("noun", "stairs; kick", "de"),
    "trappen": ("verb", "to kick; to step", None),
    "treden": ("verb", "to step; to enter", None),
    "treffen": ("verb", "to hit; to meet; to affect", None),
    "trein": ("noun", "train", "de"),
    "trek": ("noun", "appetite; trait", "de"),
    "treurig": ("adjective", "sad, sorrowful", None),
    "triest": ("adjective", "sad, dreary", None),
    "trillen": ("verb", "to tremble, to vibrate", None),
    "triomf": ("noun", "triumph", "de"),
    "troep": ("noun", "mess; troop", "de"),
    "troost": ("noun", "comfort, consolation", "de"),
    "troosten": ("verb", "to comfort, to console", None),
    "tropisch": ("adjective", "tropical", None),
    "trottoir": ("noun", "sidewalk", "het"),
    "trouwens": ("adjective", "by the way; besides", None),
    "trui": ("noun", "sweater", "de"),
    "typeren": ("verb", "to typify, to characterize", None),
    "uitbreken": ("verb", "to break out", None),
    "uitbrengen": ("verb", "to bring out; to express", None),
    "uitbundig": ("adjective", "exuberant", None),
    "uitdagen": ("verb", "to challenge", None),
    "uitdrukkelijk": ("adjective", "explicit", None),
    "uiteenlopen": ("verb", "to diverge", None),
    "uiteenzetting": ("noun", "explanation, exposition", "de"),
    "uiten": ("verb", "to express", None),
    "uitgang": ("noun", "exit", "de"),
    "uitgeput": ("adjective", "exhausted", None),
    "uitgesproken": ("adjective", "outspoken", None),
    "uitgestrekt": ("adjective", "vast, extensive", None),
    "uitgever": ("noun", "publisher", "de"),
    "uitgroeien": ("verb", "to grow into", None),
    "uiting": ("noun", "expression", "de"),
    "uitkijken": ("verb", "to watch out; to look forward", None),
    "uitkomst": ("noun", "outcome, result", "de"),
    "uitleg": ("noun", "explanation", "de"),
    "uitnodigen": ("verb", "to invite", None),
    "uitnodiging": ("noun", "invitation", "de"),
    "uitroepen": ("verb", "to exclaim; to proclaim", None),
    "uitrusten": ("verb", "to rest; to equip", None),
    "uitsluiten": ("verb", "to exclude", None),
    "uitstekend": ("adjective", "excellent", None),
    "uitstrekken": ("verb", "to stretch out", None),
    "uitvallen": ("verb", "to fall out; to fail", None),
    "uitvinden": ("verb", "to invent; to find out", None),
    "uitvinding": ("noun", "invention", "de"),
    "uitvoerig": ("adjective", "detailed, thorough", None),
    "uitweg": ("noun", "way out", "de"),
    "uitzenden": ("verb", "to broadcast; to send out", None),
    "uitzending": ("noun", "broadcast", "de"),
    "uitzoeken": ("verb", "to sort out; to choose", None),
    "uitzonderlijk": ("adjective", "exceptional", None),
    "unie": ("noun", "union", "de"),
    "uniek": ("adjective", "unique", None),
    "uniform": ("noun", "uniform", "het"),
    "universeel": ("adjective", "universal", None),
    "universitair": ("adjective", "university (adj.)", None),
    "vaart": ("noun", "speed; canal", "de"),
    "vaas": ("noun", "vase", "de"),
    "vaderland": ("noun", "fatherland", "het"),
    "vak": ("noun", "subject; profession; compartment", "het"),
    "val": ("noun", "fall; trap", "de"),
    "varen": ("verb", "to sail", None),
    "variant": ("noun", "variant", "de"),
    "variatie": ("noun", "variation", "de"),
    "variëren": ("verb", "to vary", None),
    "varken": ("noun", "pig", "het"),
    "vastbesloten": ("adjective", "determined", None),
    "vasthouden": ("verb", "to hold on to", None),
    "vastleggen": ("verb", "to record; to fix", None),
    "vat": ("noun", "barrel; grip", "het"),
    "vatten": ("verb", "to catch; to understand", None),
    "vechten": ("verb", "to fight", None),
    "vee": ("noun", "cattle, livestock", "het"),
    "veelvuldig": ("adjective", "frequent", None),
    "veer": ("noun", "feather; spring; ferry", "de"),
    "vegen": ("verb", "to sweep", None),
    "vel": ("noun", "skin; sheet", "het"),
    "velen": ("verb", "to bear, to endure", None),
    "vellen": ("verb", "to fell; to pass (judgment)", None),
    "venster": ("noun", "window", "het"),
    "vent": ("noun", "guy, fellow", "de"),
    "verantwoorden": ("verb", "to account for", None),
    "verantwoording": ("noun", "accountability", "de"),
    "verbaal": ("adjective", "verbal", None),
    "verbaasd": ("adjective", "surprised", None),
    "verbazen": ("verb", "to surprise, to amaze", None),
    "verbazing": ("noun", "amazement", "de"),
    "verbeelden": ("verb", "to imagine; to depict", None),
    "verblijven": ("verb", "to stay, to reside", None),
    "verbod": ("noun", "ban, prohibition", "het"),
    "verboden": ("adjective", "forbidden", None),
    "verbond": ("noun", "alliance, covenant", "het"),
    "verbouwen": ("verb", "to renovate; to grow", None),
    "verbranden": ("verb", "to burn", None),
    "verdacht": ("adjective", "suspicious", None),
    "verdenken": ("verb", "to suspect", None),
    "verdienste": ("noun", "merit; earnings", "de"),
    "verdiepen": ("verb", "to deepen; to immerse", None),
    "verdoven": ("verb", "to numb; to anesthetize", None),
    "verdriet": ("noun", "sorrow, grief", "het"),
    "verdrietig": ("adjective", "sad", None),
    "verdrijven": ("verb", "to drive away", None),
    "verdrinken": ("verb", "to drown", None),
    "verduidelijken": ("verb", "to clarify", None),
    "vereiste": ("noun", "requirement", "de"),
    "verf": ("noun", "paint", "de"),
    "vergaan": ("verb", "to perish; to decay", None),
    "vergeefs": ("adjective", "in vain", None),
    "vergen": ("verb", "to require, to demand", None),
    "vergeven": ("verb", "to forgive", None),
    "vergissing": ("noun", "mistake", "de"),
    "verheffen": ("verb", "to raise, to elevate", None),
    "verheugen": ("verb", "to please; to look forward to", None),
    "verhinderen": ("verb", "to prevent", None),
    "verhogen": ("verb", "to increase, to raise", None),
    "verhoging": ("noun", "increase; platform", "de"),
    "verhoor": ("noun", "interrogation", "het"),
    "verhuizen": ("verb", "to move (house)", None),
    "verjaardag": ("noun", "birthday", "de"),
    "verkennen": ("verb", "to explore, to scout", None),
    "verkeren": ("verb", "to be (in a state)", None),
    "verkondigen": ("verb", "to proclaim", None),
    "verkoop": ("noun", "sale", "de"),
    "verkoper": ("noun", "seller, salesperson", "de"),
    "verlegen": ("adjective", "shy; embarrassed", None),
    "verleiden": ("verb", "to seduce; to tempt", None),
    "verleiding": ("noun", "temptation", "de"),
    "verlenen": ("verb", "to grant, to provide", None),
    "verlengen": ("verb", "to extend, to renew", None),
    "verlichten": ("verb", "to lighten; to illuminate", None),
    "verliefd": ("adjective", "in love", None),
    "verlof": ("noun", "leave, permission", "het"),
    "verloop": ("noun", "course; turnover", "het"),
    "verloren": ("adjective", "lost", None),
    "verlossen": ("verb", "to deliver; to redeem", None),
    "vermelden": ("verb", "to mention", None),
    "vermindering": ("noun", "reduction", "de"),
    "vermoedelijk": ("adjective", "presumably", None),
    "vermoeden": ("verb", "to suspect; to presume", None),
    "vermoeien": ("verb", "to tire", None),
    "vernederen": ("verb", "to humiliate", None),
    "vernemen": ("verb", "to hear, to learn", None),
    "vernielen": ("verb", "to destroy, to vandalize", None),
    "vernieuwen": ("verb", "to renew, to innovate", None),
    "vernieuwing": ("noun", "renewal, innovation", "de"),
    "veronderstellen": ("verb", "to assume, to suppose", None),
    "verontwaardiging": ("noun", "indignation", "de"),
    "veroordelen": ("verb", "to condemn; to convict", None),
    "veroveren": ("verb", "to conquer", None),
    "verovering": ("noun", "conquest", "de"),
    "verplaatsen": ("verb", "to move, to relocate", None),
    "verraad": ("noun", "betrayal, treason", "het"),
    "verraden": ("verb", "to betray", None),
    "verrichten": ("verb", "to perform, to carry out", None),
    "vers": ("adjective", "fresh", None),
    "verscheidenheid": ("noun", "variety, diversity", "de"),
    "verschrikkelijk": ("adjective", "terrible, horrible", None),
    "verschuiven": ("verb", "to shift", None),
    "verschuiving": ("noun", "shift", "de"),
    "versie": ("noun", "version", "de"),
    "verslaan": ("verb", "to defeat", None),
    "versterking": ("noun", "reinforcement", "de"),
    "verstoppen": ("verb", "to hide", None),
    "verstrekken": ("verb", "to provide, to supply", None),
    "vertalen": ("verb", "to translate", None),
    "vertaling": ("noun", "translation", "de"),
    "verte": ("noun", "distance", "de"),
    "verticaal": ("adjective", "vertical", None),
    "vertrek": ("noun", "departure; room", "het"),
    "vertrouwd": ("adjective", "trusted; familiar", None),
    "vertrouwelijk": ("adjective", "confidential", None),
    "vervallen": ("verb", "to expire; to decay", None),
    "vervangen": ("verb", "to replace", None),
    "vervelen": ("verb", "to bore", None),
    "vervelend": ("adjective", "annoying; boring", None),
    "verven": ("verb", "to paint", None),
    "vervoeren": ("verb", "to transport", None),
    "vervolg": ("noun", "continuation; sequel", "het"),
    "vervullen": ("verb", "to fulfill", None),
    "verwaarlozen": ("verb", "to neglect", None),
    "verwantschap": ("noun", "kinship, affinity", "de"),
    "verward": ("adjective", "confused", None),
    "verwarmen": ("verb", "to heat", None),
    "verwarring": ("noun", "confusion", "de"),
    "verwezenlijken": ("verb", "to realize, to achieve", None),
    "verwijt": ("noun", "reproach", "het"),
    "verwisselen": ("verb", "to exchange, to swap", None),
    "verwonderen": ("verb", "to surprise", None),
    "verwondering": ("noun", "wonder, surprise", "de"),
    "verzinnen": ("verb", "to invent, to make up", None),
    "verzoenen": ("verb", "to reconcile", None),
    "verzwakken": ("verb", "to weaken", None),
    "verzwijgen": ("verb", "to conceal, to keep silent about", None),
    "vestiging": ("noun", "establishment; branch", "de"),
    "vierkant": ("adjective", "square", None),
    "vies": ("adjective", "dirty; disgusting", None),
    "vijver": ("noun", "pond", "de"),
    "villa": ("noun", "villa", "de"),
    "viool": ("noun", "violin", "de"),
    "vis": ("noun", "fish", "de"),
    "visie": ("noun", "vision, view", "de"),
    "vissen": ("verb", "to fish", None),
    "visser": ("noun", "fisherman", "de"),
    "vitaal": ("adjective", "vital", None),
    "vlag": ("noun", "flag", "de"),
    "vlakte": ("noun", "plain", "de"),
    "vlek": ("noun", "stain, spot", "de"),
    "vleugel": ("noun", "wing", "de"),
    "vliegveld": ("noun", "airport", "het"),
    "vloeistof": ("noun", "liquid", "de"),
    "vloeken": ("verb", "to curse, to swear", None),
    "vlot": ("adjective", "fluent; smooth", None),
    "vluchtig": ("adjective", "brief; volatile", None),
    "vocht": ("noun", "moisture", "het"),
    "vochtig": ("adjective", "moist, damp", None),
    "voeding": ("noun", "food, nutrition", "de"),
    "voegen": ("verb", "to add; to join", None),
    "voertuig": ("noun", "vehicle", "het"),
    "voldoening": ("noun", "satisfaction", "de"),
    "volgorde": ("noun", "order, sequence", "de"),
    "volhouden": ("verb", "to persist; to maintain", None),
    "volmaakt": ("adjective", "perfect", None),
    "volstrekt": ("adjective", "absolute, utter", None),
    "voltooien": ("verb", "to complete, to finish", None),
    "volwassene": ("noun", "adult", "de"),
    "vondst": ("noun", "find, discovery", "de"),
    "vonk": ("noun", "spark", "de"),
    "vooraf": ("adjective", "beforehand", None),
    "voorafgaan": ("verb", "to precede", None),
    "voorbereiden": ("verb", "to prepare", None),
    "voorbereiding": ("noun", "preparation", "de"),
    "voorbijgaan": ("verb", "to pass by", None),
    "voordeur": ("noun", "front door", "de"),
    "voordoen": ("verb", "to occur; to demonstrate", None),
    "voorgaan": ("verb", "to precede; to lead", None),
    "voorganger": ("noun", "predecessor", "de"),
    "voorhoofd": ("noun", "forehead", "het"),
    "voorjaar": ("noun", "spring (season)", "het"),
    "voorkeur": ("noun", "preference", "de"),
    "voorleggen": ("verb", "to present, to submit", None),
    "voorlezen": ("verb", "to read aloud", None),
    "voorlichting": ("noun", "information; education", "de"),
    "voormalig": ("adjective", "former", None),
    "vooroordeel": ("noun", "prejudice", "het"),
    "voorraad": ("noun", "stock, supply", "de"),
    "voorschrift": ("noun", "regulation, prescription", "het"),
    "voorschrijven": ("verb", "to prescribe", None),
    "voorspellen": ("verb", "to predict", None),
    "voorspelling": ("noun", "prediction", "de"),
    "voortbestaan": ("noun", "continued existence", "het"),
    "voortgaan": ("verb", "to continue", None),
    "voortkomen": ("verb", "to come from, to result from", None),
    "voortreffelijk": ("adjective", "excellent", None),
    "voortzetten": ("verb", "to continue", None),
    "vooruitzicht": ("noun", "prospect", "het"),
    "voorval": ("noun", "incident", "het"),
    "voorziening": ("noun", "facility; provision", "de"),
    "vorig": ("adjective", "previous, last", None),
    "vork": ("noun", "fork", "de"),
    "vormgeving": ("noun", "design", "de"),
    "vorming": ("noun", "formation; education", "de"),
    "vouwen": ("verb", "to fold", None),
    "vraagstuk": ("noun", "problem, issue", "het"),
    "vrachtwagen": ("noun", "truck", "de"),
    "vredig": ("adjective", "peaceful", None),
    "vreedzaam": ("adjective", "peaceful", None),
    "vreemdeling": ("noun", "stranger, foreigner", "de"),
    "vreselijk": ("adjective", "terrible, awful", None),
    "vreten": ("verb", "to eat (animals); to gorge", None),
    "vreugde": ("noun", "joy", "de"),
    "vriendin": ("noun", "girlfriend; female friend", "de"),
    "vriezen": ("verb", "to freeze", None),
    "vrijwillig": ("adjective", "voluntary", None),
    "vrijwilliger": ("noun", "volunteer", "de"),
    "vruchtbaar": ("adjective", "fertile; fruitful", None),
    "vuist": ("noun", "fist", "de"),
    "vurig": ("adjective", "fervent, ardent", None),
    "waanzin": ("noun", "madness", "de"),
    "waar": ("adjective", "true; where", None),
    "waardevol": ("adjective", "valuable", None),
    "waardigheid": ("noun", "dignity", "de"),
    "wacht": ("noun", "guard; wait", "de"),
    "waken": ("verb", "to watch, to guard", None),
    "wakker": ("adjective", "awake", None),
    "wal": ("noun", "embankment; shore", "de"),
    "wandeling": ("noun", "walk, stroll", "de"),
    "wang": ("noun", "cheek", "de"),
    "wanhoop": ("noun", "despair", "de"),
    "wanhopig": ("adjective", "desperate", None),
    "wankelen": ("verb", "to totter, to waver", None),
    "wantrouwen": ("noun", "distrust", "het"),
    "wapenen": ("verb", "to arm", None),
    "wederzijds": ("adjective", "mutual", None),
    "weduwe": ("noun", "widow", "de"),
    "weefsel": ("noun", "tissue; fabric", "het"),
    "weekblad": ("noun", "weekly magazine", "het"),
    "weekend": ("noun", "weekend", "het"),
    "weergeven": ("verb", "to reproduce; to render", None),
    "weerhouden": ("verb", "to restrain; to prevent", None),
    "weerspiegelen": ("verb", "to reflect", None),
    "weggaan": ("verb", "to leave, to go away", None),
    "wegnemen": ("verb", "to take away", None),
    "weigering": ("noun", "refusal", "de"),
    "weiland": ("noun", "meadow, pasture", "het"),
    "welkom": ("adjective", "welcome", None),
    "welvaart": ("noun", "prosperity", "de"),
    "welzijn": ("noun", "well-being, welfare", "het"),
    "wenden": ("verb", "to turn", None),
    "wenen": ("verb", "to weep", None),
    "wennen": ("verb", "to get used to", None),
    "wenselijk": ("adjective", "desirable", None),
    "weren": ("verb", "to keep out; to defend", None),
    "werkgelegenheid": ("noun", "employment", "de"),
    "werkloosheid": ("noun", "unemployment", "de"),
    "werkwijze": ("noun", "method, approach", "de"),
    "werkzaam": ("adjective", "working; active", None),
    "westelijk": ("adjective", "western", None),
    "westen": ("noun", "west", "het"),
    "westers": ("adjective", "Western", None),
    "wetgeving": ("noun", "legislation", "de"),
    "wiegen": ("verb", "to rock; to cradle", None),
    "wiel": ("noun", "wheel", "het"),
    "wijken": ("verb", "to yield; to retreat", None),
    "wijs": ("adjective", "wise", None),
    "wijsheid": ("noun", "wisdom", "de"),
    "willekeurig": ("adjective", "random; arbitrary", None),
    "wiskunde": ("noun", "mathematics", "de"),
    "woede": ("noun", "rage, fury", "de"),
    "woedend": ("adjective", "furious", None),
    "woest": ("adjective", "wild; furious", None),
    "woestijn": ("noun", "desert", "de"),
    "wolf": ("noun", "wolf", "de"),
    "wolk": ("noun", "cloud", "de"),
    "wond": ("noun", "wound", "de"),
    "wonder": ("noun", "miracle, wonder", "het"),
    "wonderlijk": ("adjective", "strange, wonderful", None),
    "woonkamer": ("noun", "living room", "de"),
    "worstelen": ("verb", "to wrestle; to struggle", None),
    "wortel": ("noun", "root; carrot", "de"),
    "zaad": ("noun", "seed", "het"),
    "zaaien": ("verb", "to sow", None),
    "zadel": ("noun", "saddle", "het"),
    "zakdoek": ("noun", "handkerchief", "de"),
    "zakenman": ("noun", "businessman", "de"),
    "zakken": ("verb", "to sink; to fail", None),
    "zaterdag": ("noun", "Saturday", "de"),
    "zedelijk": ("adjective", "moral", None),
    "zeep": ("noun", "soap", "de"),
    "zeer": ("adjective", "very; sore", None),
    "zeldzaam": ("adjective", "rare", None),
    "zelfmoord": ("noun", "suicide", "de"),
    "zelfvertrouwen": ("noun", "self-confidence", "het"),
    "zendeling": ("noun", "missionary", "de"),
    "zender": ("noun", "sender; transmitter", "de"),
    "zending": ("noun", "shipment; mission", "de"),
    "zenuwachtig": ("adjective", "nervous", None),
    "zetel": ("noun", "seat", "de"),
    "zeuren": ("verb", "to nag, to whine", None),
    "zielig": ("adjective", "pitiful", None),
    "zijde": ("noun", "silk; side", "de"),
    "zilveren": ("adjective", "silver", None),
    "zingen": ("verb", "to sing", None),
    "zinken": ("verb", "to sink", None),
    "zintuig": ("noun", "sense (organ)", "het"),
    "zinvol": ("adjective", "meaningful", None),
    "zitting": ("noun", "session; seat", "de"),
    "zoemen": ("verb", "to buzz, to hum", None),
    "zoenen": ("verb", "to kiss", None),
    "zoet": ("adjective", "sweet", None),
    "zolder": ("noun", "attic", "de"),
}
