WORDS = {
    # L
    "laag": ("adjective", "low", None),
    "laan": ("noun", "avenue", "de"),
    "laat": ("adjective", "late", None),
    "laatst": ("adjective", "last, latest", None),
    "lach": ("noun", "laugh, smile", "de"),
    "lachen": ("verb", "to laugh", None),
    "laden": ("verb", "to load", None),
    "land": ("noun", "country; land", "het"),
    "landelijk": ("adjective", "national; rural", None),
    "landen": ("verb", "to land", None),
    "lang": ("adjective", "long; tall", None),
    "langs": ("adjective", "along", None),
    "langzaam": ("adjective", "slow", None),
    "langzamerhand": ("adjective", "gradually", None),
    "lap": ("noun", "patch, piece of cloth", "de"),
    "last": ("noun", "burden; trouble", "de"),
    "laten": ("verb", "to let; to leave", None),
    "leed": ("noun", "suffering, sorrow", "het"),
    "leeftijd": ("noun", "age", "de"),
    "leer": ("noun", "leather; doctrine", "het"),
    "leerling": ("noun", "pupil, student", "de"),
    "leeuw": ("noun", "lion", "de"),
    "leggen": ("verb", "to lay, to put", None),
    "leger": ("noun", "army", "het"),
    "leiden": ("verb", "to lead; to suffer", None),
    "leider": ("noun", "leader", "de"),
    "leiding": ("noun", "leadership; pipe", "de"),
    "lelijk": ("adjective", "ugly", None),
    "lengte": ("noun", "length", "de"),
    "leren": ("verb", "to learn; to teach", None),
    "les": ("noun", "lesson", "de"),
    "letter": ("noun", "letter (alphabet)", "de"),
    "letterlijk": ("adjective", "literal", None),
    "leuk": ("adjective", "fun, nice", None),
    "leunen": ("verb", "to lean", None),
    "leven": ("noun", "life", "het"),
    "levend": ("adjective", "alive, living", None),
    "leveren": ("verb", "to deliver; to provide", None),
    "lezen": ("verb", "to read", None),
    "lezer": ("noun", "reader", "de"),
    "liberaal": ("adjective", "liberal", None),
    "lichaam": ("noun", "body", "het"),
    "lichamelijk": ("adjective", "physical, bodily", None),
    "licht": ("noun", "light", "het"),
    "lid": ("noun", "member", "het"),
    "lief": ("adjective", "sweet, dear", None),
    "liefde": ("noun", "love", "de"),
    "liefhebber": ("noun", "lover, enthusiast", "de"),
    "liefst": ("adjective", "preferably; dearest", None),
    "liggen": ("verb", "to lie (position)", None),
    "lijden": ("verb", "to suffer", None),
    "lijf": ("noun", "body", "het"),
    "lijk": ("noun", "corpse", "het"),
    "lijken": ("verb", "to seem; to resemble", None),
    "lijn": ("noun", "line", "de"),
    "lijst": ("noun", "list; frame", "de"),
    "link": ("adjective", "risky, dangerous", None),
    "links": ("adjective", "left", None),
    "lip": ("noun", "lip", "de"),
    "literatuur": ("noun", "literature", "de"),
    "lof": ("noun", "praise", "de"),
    "logisch": ("adjective", "logical", None),
    "lokaal": ("adjective", "local", None),
    "lonen": ("verb", "to be worthwhile", None),
    "lood": ("noun", "lead (metal)", "het"),
    "loon": ("noun", "wage", "het"),
    "loop": ("noun", "course; walk", "de"),
    "lopen": ("verb", "to walk; to run", None),
    "los": ("adjective", "loose", None),
    "loslaten": ("verb", "to let go", None),
    "lot": ("noun", "fate; lottery ticket", "het"),
    "lucht": ("noun", "air; sky", "de"),
    "luchtvaart": ("noun", "aviation", "de"),
    "lui": ("adjective", "lazy", None),
    "luiden": ("verb", "to ring; to read (text)", None),
    "luisteren": ("verb", "to listen", None),
    "lukken": ("verb", "to succeed", None),
    "lust": ("noun", "desire; pleasure", "de"),
    # M
    "maal": ("noun", "time (occasion); meal", "het"),
    "maand": ("noun", "month", "de"),
    "maandag": ("noun", "Monday", "de"),
    "maar": ("adjective", "but; only", None),
    "maatregel": ("noun", "measure", "de"),
    "macht": ("noun", "power", "de"),
    "machtig": ("adjective", "powerful", None),
    "mager": ("adjective", "thin, lean", None),
    "maken": ("verb", "to make", None),
    "manier": ("noun", "way, manner", "de"),
    "man": ("noun", "man; husband", "de"),
    "manifestatie": ("noun", "manifestation", "de"),
    "massa": ("noun", "mass, crowd", "de"),
    "materiaal": ("noun", "material", "het"),
    "matig": ("adjective", "moderate", None),
    "mechanisme": ("noun", "mechanism", "het"),
    "medaille": ("noun", "medal", "de"),
    "mede": ("adjective", "also, co-", None),
    "mededeling": ("noun", "announcement", "de"),
    "medewerker": ("noun", "employee, colleague", "de"),
    "medewerking": ("noun", "cooperation", "de"),
    "medicijn": ("noun", "medicine", "het"),
    "meedoen": ("verb", "to participate", None),
    "meenemen": ("verb", "to take along", None),
    "meerderheid": ("noun", "majority", "de"),
    "meester": ("noun", "master; teacher", "de"),
    "meisje": ("noun", "girl", "het"),
    "melden": ("verb", "to report", None),
    "melk": ("noun", "milk", "de"),
    "mengen": ("verb", "to mix", None),
    "mening": ("noun", "opinion", "de"),
    "mens": ("noun", "human, person", "de"),
    "menselijk": ("adjective", "human", None),
    "mensenrecht": ("noun", "human right", "het"),
    "merken": ("verb", "to notice", None),
    "mes": ("noun", "knife", "het"),
    "methode": ("noun", "method", "de"),
    "meten": ("verb", "to measure", None),
    "middag": ("noun", "afternoon", "de"),
    "middel": ("noun", "means; waist", "het"),
    "midden": ("noun", "middle, center", "het"),
    "miljoen": ("noun", "million", "het"),
    "milieu": ("noun", "environment", "het"),
    "militair": ("adjective", "military", None),
    "minachting": ("noun", "contempt", "de"),
    "mineraal": ("noun", "mineral", "het"),
    "minister": ("noun", "minister", "de"),
    "ministerie": ("noun", "ministry", "het"),
    "minst": ("adjective", "least", None),
    "misschien": ("adjective", "perhaps, maybe", None),
    "modern": ("adjective", "modern", None),
    "moeder": ("noun", "mother", "de"),
    "moeilijk": ("adjective", "difficult", None),
    "moeilijkheid": ("noun", "difficulty", "de"),
    "moeilijkheden": ("noun", "difficulties", "de"),
    "moeite": ("noun", "effort, trouble", "de"),
    "moeten": ("verb", "to have to, must", None),
    "mogelijk": ("adjective", "possible", None),
    "mogelijkheid": ("noun", "possibility", "de"),
    "mogen": ("verb", "to be allowed to; to like", None),
    "moment": ("noun", "moment", "het"),
    "mond": ("noun", "mouth", "de"),
    "monniken": ("noun", "monks", "de"),
    "mooi": ("adjective", "beautiful", None),
    "moord": ("noun", "murder", "de"),
    "moraal": ("noun", "morality; moral", "de"),
    "moreel": ("adjective", "moral", None),
    "morgen": ("noun", "morning; tomorrow", "de"),
    "moslim": ("noun", "Muslim", "de"),
    "motor": ("noun", "engine; motorcycle", "de"),
    "mouw": ("noun", "sleeve", "de"),
    "munt": ("noun", "coin; currency", "de"),
    "muur": ("noun", "wall", "de"),
    "muziek": ("noun", "music", "de"),
    # N
    "naam": ("noun", "name", "de"),
    "nacht": ("noun", "night", "de"),
    "nader": ("adjective", "further, closer", None),
    "nadruk": ("noun", "emphasis", "de"),
    "nagaan": ("verb", "to check; to trace", None),
    "nalaten": ("verb", "to leave behind; to fail to do", None),
    "namelijk": ("adjective", "namely", None),
    "nare": ("adjective", "unpleasant, nasty", None),
    "natuur": ("noun", "nature", "de"),
    "natuurlijk": ("adjective", "natural; of course", None),
    "nauw": ("adjective", "narrow; close", None),
    "nauwelijks": ("adjective", "hardly, barely", None),
    "nauwkeurig": ("adjective", "precise, accurate", None),
    "neer": ("adjective", "down", None),
    "neerleggen": ("verb", "to put down", None),
    "negatief": ("adjective", "negative", None),
    "neiging": ("noun", "tendency, inclination", "de"),
    "nemen": ("verb", "to take", None),
    "nergens": ("adjective", "nowhere", None),
    "net": ("adjective", "neat; just", None),
    "neus": ("noun", "nose", "de"),
    "neutraal": ("adjective", "neutral", None),
    "nieuw": ("adjective", "new", None),
    "nieuws": ("noun", "news", "het"),
    "niveau": ("noun", "level", "het"),
    "noden": ("verb", "to need; to urge", None),
    "nodig": ("adjective", "necessary", None),
    "noemen": ("verb", "to call, to name", None),
    "nood": ("noun", "need, emergency", "de"),
    "noodzaak": ("noun", "necessity", "de"),
    "noodzakelijk": ("adjective", "necessary", None),
    "norm": ("noun", "norm, standard", "de"),
    "normaal": ("adjective", "normal", None),
    "nota": ("noun", "note; bill", "de"),
    "nummer": ("noun", "number", "het"),
    "nut": ("noun", "use, benefit", "het"),
    "nuttig": ("adjective", "useful", None),
    # O
    "ochtend": ("noun", "morning", "de"),
    "oefenen": ("verb", "to practice", None),
    "oefening": ("noun", "exercise", "de"),
    "oever": ("noun", "bank (river)", "de"),
    "offer": ("noun", "sacrifice", "het"),
    "officieel": ("adjective", "official", None),
    "officier": ("noun", "officer", "de"),
    "omgang": ("noun", "interaction", "de"),
    "omgeving": ("noun", "surroundings, environment", "de"),
    "omstandigheid": ("noun", "circumstance", "de"),
    "omvang": ("noun", "size, extent", "de"),
    "omvatten": ("verb", "to comprise, to encompass", None),
    "omzetten": ("verb", "to convert; to turn over", None),
    "onafhankelijk": ("adjective", "independent", None),
    "onbekend": ("adjective", "unknown", None),
    "ondanks": ("adjective", "despite", None),
    "onderdeel": ("noun", "part, component", "het"),
    "ondergang": ("noun", "downfall", "de"),
    "onderhouden": ("verb", "to maintain", None),
    "ondernemen": ("verb", "to undertake", None),
    "ondernemer": ("noun", "entrepreneur", "de"),
    "onderneming": ("noun", "enterprise, company", "de"),
    "onderscheid": ("noun", "distinction", "het"),
    "onderscheiden": ("verb", "to distinguish", None),
    "ondersteunen": ("verb", "to support", None),
    "ondersteuning": ("noun", "support", "de"),
    "ondertussen": ("adjective", "meanwhile", None),
    "onderwerp": ("noun", "subject, topic", "het"),
    "onderwijs": ("noun", "education", "het"),
    "onderwijzer": ("noun", "teacher", "de"),
    "onderzoek": ("noun", "research, investigation", "het"),
    "onderzoeken": ("verb", "to investigate; to examine", None),
    "onderzoeker": ("noun", "researcher", "de"),
    "ongelooflijk": ("adjective", "incredible", None),
    "ongeluk": ("noun", "accident; misfortune", "het"),
    "ongerust": ("adjective", "worried", None),
    "ongetwijfeld": ("adjective", "undoubtedly", None),
    "ongeveer": ("adjective", "approximately", None),
    "onmiddellijk": ("adjective", "immediate", None),
    "onmogelijk": ("adjective", "impossible", None),
    "onrecht": ("noun", "injustice", "het"),
    "onrust": ("noun", "unrest", "de"),
    "onschuld": ("noun", "innocence", "de"),
    "onschuldig": ("adjective", "innocent", None),
    "ontstaan": ("verb", "to arise, to originate", None),
    "ontbreken": ("verb", "to be missing, to lack", None),
    "ontdekken": ("verb", "to discover", None),
    "ontdekking": ("noun", "discovery", "de"),
    "ontkennen": ("verb", "to deny", None),
    "ontmoeten": ("verb", "to meet", None),
    "ontmoeting": ("noun", "meeting, encounter", "de"),
    "ontnemen": ("verb", "to take away", None),
    "ontsnappen": ("verb", "to escape", None),
    "ontslag": ("noun", "dismissal, resignation", "het"),
    "ontslaan": ("verb", "to fire, to dismiss", None),
    "ontvangen": ("verb", "to receive", None),
    "ontvangst": ("noun", "reception", "de"),
    "ontwikkelen": ("verb", "to develop", None),
    "ontwikkeling": ("noun", "development", "de"),
    "ontwerpen": ("verb", "to design", None),
    "ontwerp": ("noun", "design, plan", "het"),
    "onvoldoende": ("adjective", "insufficient", None),
    "onvoorstelbaar": ("adjective", "unimaginable", None),
    "onwaarschijnlijk": ("adjective", "unlikely", None),
    "onzeker": ("adjective", "uncertain", None),
    "onzekerheid": ("noun", "uncertainty", "de"),
    "oog": ("noun", "eye", "het"),
    "ooit": ("adjective", "ever; once", None),
    "ook": ("adjective", "also, too", None),
    "oom": ("noun", "uncle", "de"),
    "oor": ("noun", "ear", "het"),
    "oordeel": ("noun", "judgment", "het"),
    "oordelen": ("verb", "to judge", None),
    "oorlog": ("noun", "war", "de"),
    "oorzaak": ("noun", "cause", "de"),
    "oost": ("noun", "east", "het"),
    "opbouwen": ("verb", "to build up", None),
    "opdracht": ("noun", "assignment, order", "de"),
    "open": ("adjective", "open", None),
    "openbaar": ("adjective", "public", None),
    "openen": ("verb", "to open", None),
    "opening": ("noun", "opening", "de"),
    "operatie": ("noun", "operation", "de"),
    "opgang": ("noun", "rise", "de"),
    "opheffen": ("verb", "to abolish; to lift", None),
    "ophouden": ("verb", "to stop; to hold up", None),
    "opkomen": ("verb", "to come up; to stand up for", None),
    "opleggen": ("verb", "to impose", None),
    "opleiden": ("verb", "to train, to educate", None),
    "opleiding": ("noun", "education, training", "de"),
    "opletten": ("verb", "to pay attention", None),
    "oplossen": ("verb", "to solve; to dissolve", None),
    "oplossing": ("noun", "solution", "de"),
    "opmerken": ("verb", "to notice; to remark", None),
    "opmerking": ("noun", "remark", "de"),
    "opmerkelijk": ("adjective", "remarkable", None),
    "opnemen": ("verb", "to pick up; to record; to admit", None),
    "opnieuw": ("adjective", "again, anew", None),
    "oppervlak": ("noun", "surface", "het"),
    "oprichten": ("verb", "to establish, to found", None),
    "oprijzen": ("verb", "to rise up", None),
    "oproep": ("noun", "call, appeal", "de"),
    "opruimen": ("verb", "to clean up", None),
    "opstand": ("noun", "revolt, uprising", "de"),
    "opstellen": ("verb", "to draw up; to position", None),
    "optreden": ("verb", "to act; to perform; to occur", None),
    "opvallen": ("verb", "to stand out, to be noticeable", None),
    "opvallend": ("adjective", "striking, remarkable", None),
    "opvatten": ("verb", "to interpret; to conceive", None),
    "opvatting": ("noun", "view, opinion", "de"),
    "opvoeden": ("verb", "to raise, to educate", None),
    "opvoeding": ("noun", "upbringing, education", "de"),
    "opzetten": ("verb", "to set up", None),
    "opzicht": ("noun", "respect, regard", "het"),
    "opzij": ("adjective", "aside", None),
    "orde": ("noun", "order", "de"),
    "ordenen": ("verb", "to organize, to arrange", None),
    "organisatie": ("noun", "organization", "de"),
    "organiseren": ("verb", "to organize", None),
    "orgaan": ("noun", "organ; body", "het"),
    "oud": ("adjective", "old", None),
    "ouder": ("noun", "parent", "de"),
    "overal": ("adjective", "everywhere", None),
    "overheid": ("noun", "government", "de"),
    "overig": ("adjective", "remaining, other", None),
    "overige": ("adjective", "remaining", None),
    "overleggen": ("verb", "to consult; to present", None),
    "overleg": ("noun", "consultation", "het"),
    "overleven": ("verb", "to survive", None),
    "overigens": ("adjective", "by the way; moreover", None),
    "overnemen": ("verb", "to take over", None),
    "overschrijden": ("verb", "to exceed; to cross", None),
    "oversteken": ("verb", "to cross (street)", None),
    "overtuigen": ("verb", "to convince", None),
    "overtuiging": ("noun", "conviction", "de"),
    "overwegen": ("verb", "to consider", None),
    "overweging": ("noun", "consideration", "de"),
    "overwinnen": ("verb", "to overcome; to win", None),
    "overwinning": ("noun", "victory", "de"),
    "overzicht": ("noun", "overview", "het"),
    # P
    "paar": ("noun", "pair; a few", "het"),
    "paard": ("noun", "horse", "het"),
    "pad": ("noun", "path", "het"),
    "pagina": ("noun", "page", "de"),
    "pak": ("noun", "suit; package", "het"),
    "pakken": ("verb", "to grab; to pack", None),
    "paleis": ("noun", "palace", "het"),
    "pan": ("noun", "pan", "de"),
    "paniek": ("noun", "panic", "de"),
    "papier": ("noun", "paper", "het"),
    "parlement": ("noun", "parliament", "het"),
    "partij": ("noun", "party (political)", "de"),
    "partner": ("noun", "partner", "de"),
    "passen": ("verb", "to fit; to try on", None),
    "passeren": ("verb", "to pass", None),
    "patient": ("noun", "patient", "de"),
    "patroon": ("noun", "pattern; patron", "het"),
    "paus": ("noun", "pope", "de"),
    "pen": ("noun", "pen", "de"),
    "periode": ("noun", "period", "de"),
    "permanent": ("adjective", "permanent", None),
    "persoon": ("noun", "person", "de"),
    "persoonlijk": ("adjective", "personal", None),
    "persoonlijkheid": ("noun", "personality", "de"),
    "pijn": ("noun", "pain", "de"),
    "pijp": ("noun", "pipe", "de"),
    "pikken": ("verb", "to peck; to tolerate", None),
    "plaat": ("noun", "plate; picture; record", "de"),
    "plaats": ("noun", "place; city", "de"),
    "plaatsen": ("verb", "to place", None),
    "plaatselijk": ("adjective", "local", None),
    "plaatsvinden": ("verb", "to take place", None),
    "plan": ("noun", "plan", "het"),
    "plank": ("noun", "shelf; plank", "de"),
    "plant": ("noun", "plant", "de"),
    "planten": ("verb", "to plant", None),
    "plat": ("adjective", "flat", None),
    "platteland": ("noun", "countryside", "het"),
    "plegen": ("verb", "to commit; to be accustomed to", None),
    "plein": ("noun", "square (public)", "het"),
    "plezier": ("noun", "fun, pleasure", "het"),
    "plicht": ("noun", "duty", "de"),
    "ploeg": ("noun", "team; plow", "de"),
    "plek": ("noun", "spot, place", "de"),
    "plotseling": ("adjective", "sudden", None),
    "poes": ("noun", "cat (informal)", "de"),
    "poging": ("noun", "attempt", "de"),
    "politicus": ("noun", "politician", "de"),
    "politie": ("noun", "police", "de"),
    "politiek": ("noun", "politics; policy", "de"),
    "pond": ("noun", "pound", "het"),
    "pont": ("noun", "ferry", "de"),
    "pop": ("noun", "doll; puppet", "de"),
    "populair": ("adjective", "popular", None),
    "poort": ("noun", "gate", "de"),
    "positie": ("noun", "position", "de"),
    "positief": ("adjective", "positive", None),
    "post": ("noun", "mail; post", "de"),
    "pot": ("noun", "pot, jar", "de"),
    "prachtig": ("adjective", "magnificent, wonderful", None),
    "praktijk": ("noun", "practice", "de"),
    "praktisch": ("adjective", "practical", None),
    "praten": ("verb", "to talk", None),
    "precies": ("adjective", "precise, exactly", None),
    "president": ("noun", "president", "de"),
    "presteren": ("verb", "to perform, to achieve", None),
    "prestatie": ("noun", "achievement", "de"),
    "prettig": ("adjective", "pleasant", None),
    "preventief": ("adjective", "preventive", None),
    "priester": ("noun", "priest", "de"),
    "prins": ("noun", "prince", "de"),
    "prinses": ("noun", "princess", "de"),
    "principe": ("noun", "principle", "het"),
    "prive": ("adjective", "private", None),
    "probleem": ("noun", "problem", "het"),
    "procedure": ("noun", "procedure", "de"),
    "proces": ("noun", "process; trial", "het"),
    "product": ("noun", "product", "het"),
    "productie": ("noun", "production", "de"),
    "produceren": ("verb", "to produce", None),
    "professor": ("noun", "professor", "de"),
    "professioneel": ("adjective", "professional", None),
    "programma": ("noun", "program", "het"),
    "project": ("noun", "project", "het"),
    "protest": ("noun", "protest", "het"),
    "protesteren": ("verb", "to protest", None),
    "provincie": ("noun", "province", "de"),
    "publiek": ("noun", "public; audience", "het"),
    "punt": ("noun", "point; period", "het"),
    "puur": ("adjective", "pure", None),
    # R
    "raad": ("noun", "council; advice", "de"),
    "raadplegen": ("verb", "to consult", None),
    "raam": ("noun", "window", "het"),
    "raar": ("adjective", "strange", None),
    "raken": ("verb", "to hit; to touch; to become", None),
    "rand": ("noun", "edge, margin", "de"),
    "rang": ("noun", "rank", "de"),
    "reactie": ("noun", "reaction", "de"),
    "reageren": ("verb", "to react", None),
    "realiseren": ("verb", "to realize; to achieve", None),
    "recent": ("adjective", "recent", None),
    "recht": ("noun", "right; law", "het"),
    "rechter": ("noun", "judge", "de"),
    "rechtop": ("adjective", "upright", None),
    "rechts": ("adjective", "right (direction)", None),
    "rechtstreeks": ("adjective", "direct", None),
    "rechtvaardig": ("adjective", "just, fair", None),
    "rechtvaardigheid": ("noun", "justice", "de"),
    "reden": ("noun", "reason", "de"),
    "redelijk": ("adjective", "reasonable", None),
    "redeneren": ("verb", "to reason", None),
    "redden": ("verb", "to save, to rescue", None),
    "rede": ("noun", "reason; speech", "de"),
    "reeds": ("adjective", "already", None),
    "reeks": ("noun", "series", "de"),
    "regel": ("noun", "rule; line", "de"),
    "regelen": ("verb", "to arrange", None),
    "regeling": ("noun", "arrangement, regulation", "de"),
    "regelmatig": ("adjective", "regular", None),
    "regen": ("noun", "rain", "de"),
    "regering": ("noun", "government", "de"),
    "regime": ("noun", "regime", "het"),
    "regio": ("noun", "region", "de"),
    "regionaal": ("adjective", "regional", None),
    "reis": ("noun", "journey, trip", "de"),
    "reizen": ("verb", "to travel", None),
    "rekenen": ("verb", "to calculate; to count on", None),
    "rekening": ("noun", "bill; account", "de"),
    "relatie": ("noun", "relationship", "de"),
    "relatief": ("adjective", "relative", None),
    "religie": ("noun", "religion", "de"),
    "religieus": ("adjective", "religious", None),
    "rennen": ("verb", "to run", None),
    "rente": ("noun", "interest (financial)", "de"),
    "reputatie": ("noun", "reputation", "de"),
    "reserve": ("noun", "reserve", "de"),
    "respect": ("noun", "respect", "het"),
    "respecteren": ("verb", "to respect", None),
    "rest": ("noun", "rest, remainder", "de"),
    "restaurant": ("noun", "restaurant", "het"),
    "resultaat": ("noun", "result", "het"),
    "richten": ("verb", "to aim; to direct", None),
    "richting": ("noun", "direction", "de"),
    "riep": ("verb", "called (past tense of roepen)", None),
    "rijden": ("verb", "to drive; to ride", None),
    "rijk": ("adjective", "rich", None),
    "rijkdom": ("noun", "wealth", "de"),
    "ring": ("noun", "ring", "de"),
    "risico": ("noun", "risk", "het"),
    "rivier": ("noun", "river", "de"),
    "roep": ("noun", "call; reputation", "de"),
    "roepen": ("verb", "to call, to shout", None),
    "rok": ("noun", "skirt", "de"),
    "rol": ("noun", "role", "de"),
    "roman": ("noun", "novel", "de"),
    "romantisch": ("adjective", "romantic", None),
    "rond": ("adjective", "round", None),
    "rood": ("adjective", "red", None),
    "rook": ("noun", "smoke", "de"),
    "roven": ("verb", "to rob", None),
    "rug": ("noun", "back", "de"),
    "ruiken": ("verb", "to smell", None),
    "ruilen": ("verb", "to exchange", None),
    "ruim": ("adjective", "spacious; ample", None),
    "ruimte": ("noun", "space, room", "de"),
    "ruimtelijk": ("adjective", "spatial", None),
    "rust": ("noun", "rest, peace", "de"),
    "rustig": ("adjective", "calm, quiet", None),
    "rusten": ("verb", "to rest", None),
}
