WORDS = {
    # S
    "samenleving": ("noun", "society", "de"),
    "samenwerken": ("verb", "to cooperate", None),
    "samenwerking": ("noun", "cooperation", "de"),
    "samenstellen": ("verb", "to compose; to compile", None),
    "samenstelling": ("noun", "composition", "de"),
    "schadelijk": ("adjective", "harmful", None),
    "schaduw": ("noun", "shadow", "de"),
    "schaffen": ("verb", "to obtain; to abolish", None),
    "schamen": ("verb", "to be ashamed", None),
    "schande": ("noun", "shame, disgrace", "de"),
    "schat": ("noun", "treasure; darling", "de"),
    "schatten": ("verb", "to estimate", None),
    "scheiding": ("noun", "separation; divorce", "de"),
    "schelden": ("verb", "to curse, to scold", None),
    "schenken": ("verb", "to pour; to donate", None),
    "scheppen": ("verb", "to create; to scoop", None),
    "scherp": ("adjective", "sharp", None),
    "schieten": ("verb", "to shoot", None),
    "schilderen": ("verb", "to paint", None),
    "schilderij": ("noun", "painting", "het"),
    "schip": ("noun", "ship", "het"),
    "scholen": ("verb", "to school; to train", None),
    "school": ("noun", "school", "de"),
    "schoon": ("adjective", "clean; beautiful", None),
    "schoonheid": ("noun", "beauty", "de"),
    "schop": ("noun", "kick; shovel", "de"),
    "schouder": ("noun", "shoulder", "de"),
    "schreeuwen": ("verb", "to scream, to shout", None),
    "schrift": ("noun", "notebook; writing", "het"),
    "schrijven": ("verb", "to write", None),
    "schrijver": ("noun", "writer, author", "de"),
    "schrikken": ("verb", "to be frightened", None),
    "schuld": ("noun", "debt; guilt", "de"),
    "schuldig": ("adjective", "guilty", None),
    "sector": ("noun", "sector", "de"),
    "sfeer": ("noun", "atmosphere", "de"),
    "signaal": ("noun", "signal", "het"),
    "situatie": ("noun", "situation", "de"),
    "slaan": ("verb", "to hit, to strike", None),
    "slaap": ("noun", "sleep", "de"),
    "slachtoffer": ("noun", "victim", "het"),
    "slag": ("noun", "blow; battle", "de"),
    "slagen": ("verb", "to succeed; to pass (exam)", None),
    "slapen": ("verb", "to sleep", None),
    "slecht": ("adjective", "bad", None),
    "slechts": ("adjective", "only, merely", None),
    "sleutel": ("noun", "key", "de"),
    "slim": ("adjective", "clever, smart", None),
    "slot": ("noun", "lock; castle; conclusion", "het"),
    "sluiten": ("verb", "to close", None),
    "smaak": ("noun", "taste", "de"),
    "smal": ("adjective", "narrow", None),
    "smelten": ("verb", "to melt", None),
    "smijten": ("verb", "to throw, to fling", None),
    "snee": ("noun", "cut, slice", "de"),
    "snel": ("adjective", "fast, quick", None),
    "snelheid": ("noun", "speed", "de"),
    "snijden": ("verb", "to cut", None),
    "sociaal": ("adjective", "social", None),
    "soepel": ("adjective", "flexible, supple", None),
    "soldaat": ("noun", "soldier", "de"),
    "soort": ("noun", "kind, type; species", "de"),
    "spanning": ("noun", "tension; excitement", "de"),
    "sparen": ("verb", "to save (money)", None),
    "speciaal": ("adjective", "special", None),
    "spel": ("noun", "game", "het"),
    "spelen": ("verb", "to play", None),
    "speler": ("noun", "player", "de"),
    "spiegel": ("noun", "mirror", "de"),
    "spier": ("noun", "muscle", "de"),
    "spijt": ("noun", "regret", "de"),
    "spoor": ("noun", "track; trace", "het"),
    "sport": ("noun", "sport", "de"),
    "spraak": ("noun", "speech", "de"),
    "sprake": ("noun", "question (of); mention", "de"),
    "spreken": ("verb", "to speak", None),
    "spreker": ("noun", "speaker", "de"),
    "springen": ("verb", "to jump", None),
    "staat": ("noun", "state", "de"),
    "staan": ("verb", "to stand", None),
    "staart": ("noun", "tail", "de"),
    "stad": ("noun", "city", "de"),
    "stadium": ("noun", "stage; stadium", "het"),
    "staf": ("noun", "staff", "de"),
    "staken": ("verb", "to strike; to stop", None),
    "staking": ("noun", "strike", "de"),
    "stam": ("noun", "tribe; trunk", "de"),
    "standaard": ("noun", "standard", "de"),
    "standpunt": ("noun", "standpoint, viewpoint", "het"),
    "stap": ("noun", "step", "de"),
    "stappen": ("verb", "to step; to go out", None),
    "steeds": ("adjective", "always; increasingly", None),
    "steen": ("noun", "stone", "de"),
    "steiger": ("noun", "scaffold; pier", "de"),
    "steken": ("verb", "to sting; to put", None),
    "stelen": ("verb", "to steal", None),
    "stelsel": ("noun", "system", "het"),
    "stellen": ("verb", "to state; to set", None),
    "stelling": ("noun", "statement; position", "de"),
    "stem": ("noun", "voice; vote", "de"),
    "stemmen": ("verb", "to vote; to tune", None),
    "stemming": ("noun", "mood; vote", "de"),
    "ster": ("noun", "star", "de"),
    "sterk": ("adjective", "strong", None),
    "sterven": ("verb", "to die", None),
    "steun": ("noun", "support", "de"),
    "steunen": ("verb", "to support", None),
    "stichten": ("verb", "to found; to cause", None),
    "stichting": ("noun", "foundation (organization)", "de"),
    "stijgen": ("verb", "to rise, to increase", None),
    "stijging": ("noun", "rise, increase", "de"),
    "stijl": ("noun", "style", "de"),
    "stil": ("adjective", "quiet, silent", None),
    "stilte": ("noun", "silence", "de"),
    "stoel": ("noun", "chair", "de"),
    "stof": ("noun", "material; dust", "de"),
    "stok": ("noun", "stick", "de"),
    "stom": ("adjective", "stupid; mute", None),
    "stoppen": ("verb", "to stop", None),
    "storen": ("verb", "to disturb", None),
    "storm": ("noun", "storm", "de"),
    "straat": ("noun", "street", "de"),
    "straf": ("noun", "punishment", "de"),
    "straffen": ("verb", "to punish", None),
    "straks": ("adjective", "soon; later", None),
    "stralen": ("verb", "to radiate; to shine", None),
    "strategie": ("noun", "strategy", "de"),
    "streek": ("noun", "region; trick", "de"),
    "strekken": ("verb", "to stretch; to extend", None),
    "streven": ("verb", "to strive", None),
    "strijd": ("noun", "struggle, fight", "de"),
    "strijden": ("verb", "to fight, to struggle", None),
    "strikt": ("adjective", "strict", None),
    "strijdig": ("adjective", "conflicting", None),
    "stroom": ("noun", "stream; electricity", "de"),
    "structuur": ("noun", "structure", "de"),
    "student": ("noun", "student", "de"),
    "studeren": ("verb", "to study", None),
    "studie": ("noun", "study", "de"),
    "stuk": ("noun", "piece", "het"),
    "sturen": ("verb", "to send; to steer", None),
    "succes": ("noun", "success", "het"),
    "suggereren": ("verb", "to suggest", None),
    "symbool": ("noun", "symbol", "het"),
    "sympathie": ("noun", "sympathy", "de"),
    "systeem": ("noun", "system", "het"),
    # T
    "taal": ("noun", "language", "de"),
    "taak": ("noun", "task", "de"),
    "tafel": ("noun", "table", "de"),
    "tak": ("noun", "branch", "de"),
    "tamelijk": ("adjective", "fairly, rather", None),
    "tand": ("noun", "tooth", "de"),
    "tante": ("noun", "aunt", "de"),
    "techniek": ("noun", "technique; technology", "de"),
    "technisch": ("adjective", "technical", None),
    "technologie": ("noun", "technology", "de"),
    "teen": ("noun", "toe", "de"),
    "tegelijk": ("adjective", "at the same time", None),
    "tegelijkertijd": ("adjective", "at the same time", None),
    "tegemoet": ("adjective", "towards", None),
    "tegen": ("adjective", "against", None),
    "tegenstander": ("noun", "opponent", "de"),
    "tegenstelling": ("noun", "contrast", "de"),
    "tegenstand": ("noun", "resistance", "de"),
    "tegenover": ("adjective", "opposite; towards", None),
    "tegenwoordig": ("adjective", "nowadays; present", None),
    "teken": ("noun", "sign", "het"),
    "tekenen": ("verb", "to draw; to sign", None),
    "tekening": ("noun", "drawing", "de"),
    "tekort": ("noun", "shortage", "het"),
    "tekst": ("noun", "text", "de"),
    "telefoon": ("noun", "telephone", "de"),
    "teleurstelling": ("noun", "disappointment", "de"),
    "tellen": ("verb", "to count", None),
    "tempel": ("noun", "temple", "de"),
    "temperatuur": ("noun", "temperature", "de"),
    "tenminste": ("adjective", "at least", None),
    "tent": ("noun", "tent", "de"),
    "tentoonstelling": ("noun", "exhibition", "de"),
    "terrein": ("noun", "terrain; field", "het"),
    "terreur": ("noun", "terror", "de"),
    "terug": ("adjective", "back", None),
    "terugkeren": ("verb", "to return", None),
    "terugtrekken": ("verb", "to withdraw", None),
    "testen": ("verb", "to test", None),
    "tevoren": ("adjective", "beforehand", None),
    "tevreden": ("adjective", "satisfied", None),
    "tevredenheid": ("noun", "satisfaction", "de"),
    "theater": ("noun", "theater", "het"),
    "thema": ("noun", "theme", "het"),
    "theorie": ("noun", "theory", "de"),
    "thuis": ("adjective", "at home", None),
    "tien": ("adjective", "ten", None),
    "tij": ("noun", "tide", "het"),
    "tijd": ("noun", "time", "de"),
    "tijdelijk": ("adjective", "temporary", None),
    "tijdperk": ("noun", "era, period", "het"),
    "tijdschrift": ("noun", "magazine", "het"),
    "toch": ("adjective", "yet, still; anyway", None),
    "tocht": ("noun", "trip; draft (air)", "de"),
    "toe": ("adjective", "to; closed", None),
    "toegang": ("noun", "access, entrance", "de"),
    "toekomen": ("verb", "to be due; to get around to", None),
    "toekomst": ("noun", "future", "de"),
    "toekomstig": ("adjective", "future", None),
    "toelaten": ("verb", "to admit; to allow", None),
    "toenemen": ("verb", "to increase", None),
    "toepassen": ("verb", "to apply", None),
    "toepassing": ("noun", "application", "de"),
    "toer": ("noun", "tour; trick", "de"),
    "toestand": ("noun", "situation, condition", "de"),
    "toestemming": ("noun", "permission", "de"),
    "ton": ("noun", "ton; barrel", "de"),
    "tonen": ("verb", "to show", None),
    "toneel": ("noun", "stage; theater", "het"),
    "tong": ("noun", "tongue", "de"),
    "toon": ("noun", "tone", "de"),
    "top": ("noun", "top; summit", "de"),
    "toren": ("noun", "tower", "de"),
    "traan": ("noun", "tear", "de"),
    "trachten": ("verb", "to try, to attempt", None),
    "traditie": ("noun", "tradition", "de"),
    "traditioneel": ("adjective", "traditional", None),
    "trekken": ("verb", "to pull; to draw", None),
    "trend": ("noun", "trend", "de"),
    "troon": ("noun", "throne", "de"),
    "trots": ("adjective", "proud", None),
    "trouw": ("adjective", "faithful, loyal", None),
    "trouwen": ("verb", "to marry", None),
    "tuin": ("noun", "garden", "de"),
    "tunnel": ("noun", "tunnel", "de"),
    "twijfel": ("noun", "doubt", "de"),
    "twijfelen": ("verb", "to doubt", None),
    "type": ("noun", "type", "het"),
    "typisch": ("adjective", "typical", None),
    # U
    "uiteraard": ("adjective", "of course, naturally", None),
    "uiterlijk": ("noun", "appearance; at the latest", "het"),
    "uitermate": ("adjective", "extremely", None),
    "uiterst": ("adjective", "utmost, extreme", None),
    "uitbreiden": ("verb", "to expand", None),
    "uitbreiding": ("noun", "expansion", "de"),
    "uitdaging": ("noun", "challenge", "de"),
    "uitdrukken": ("verb", "to express", None),
    "uitdrukking": ("noun", "expression", "de"),
    "uiteindelijk": ("adjective", "ultimately, finally", None),
    "uiteenzetten": ("verb", "to explain", None),
    "uitgaan": ("verb", "to go out", None),
    "uitgangspunt": ("noun", "starting point", "het"),
    "uitgave": ("noun", "edition; expense", "de"),
    "uitgebreid": ("adjective", "extensive", None),
    "uitgeven": ("verb", "to spend; to publish", None),
    "uitkeren": ("verb", "to pay out", None),
    "uitkering": ("noun", "benefit, payment", "de"),
    "uitkomen": ("verb", "to come out; to turn out", None),
    "uitleggen": ("verb", "to explain", None),
    "uitmaken": ("verb", "to matter; to break up; to make up", None),
    "uitoefenen": ("verb", "to exercise; to practice", None),
    "uitputten": ("verb", "to exhaust", None),
    "uitslag": ("noun", "result; rash", "de"),
    "uitsluitend": ("adjective", "exclusively", None),
    "uitspreken": ("verb", "to pronounce; to express", None),
    "uitspraak": ("noun", "pronunciation; verdict", "de"),
    "uitsteken": ("verb", "to stick out", None),
    "uitstellen": ("verb", "to postpone", None),
    "uitvoeren": ("verb", "to carry out; to export", None),
    "uitvoering": ("noun", "execution; performance", "de"),
    "uitwerken": ("verb", "to work out", None),
    "uitwerking": ("noun", "effect", "de"),
    "uitzicht": ("noun", "view; prospect", "het"),
    "uitzien": ("verb", "to look out; to look forward to", None),
    "uitzondering": ("noun", "exception", "de"),
    "universiteit": ("noun", "university", "de"),
    "uur": ("noun", "hour", "het"),
    # V
    "vaag": ("adjective", "vague", None),
    "vaak": ("adjective", "often", None),
    "vaardigheid": ("noun", "skill", "de"),
    "vader": ("noun", "father", "de"),
    "vakantie": ("noun", "vacation", "de"),
    "vakbond": ("noun", "trade union", "de"),
    "vallen": ("verb", "to fall", None),
    "vals": ("adjective", "false; fake", None),
    "van": ("adjective", "of, from", None),
    "vandaag": ("adjective", "today", None),
    "vangen": ("verb", "to catch", None),
    "vast": ("adjective", "firm; fixed; stuck", None),
    "vaststellen": ("verb", "to establish; to determine", None),
    "veelal": ("adjective", "often, mostly", None),
    "veilig": ("adjective", "safe", None),
    "veiligheid": ("noun", "safety, security", "de"),
    "veld": ("noun", "field", "het"),
    "ver": ("adjective", "far", None),
    "veranderen": ("verb", "to change", None),
    "verandering": ("noun", "change", "de"),
    "verantwoordelijk": ("adjective", "responsible", None),
    "verantwoordelijkheid": ("noun", "responsibility", "de"),
    "verband": ("noun", "connection; bandage", "het"),
    "verbergen": ("verb", "to hide", None),
    "verbeteren": ("verb", "to improve", None),
    "verbetering": ("noun", "improvement", "de"),
    "verbeelding": ("noun", "imagination", "de"),
    "verbieden": ("verb", "to forbid", None),
    "verbinden": ("verb", "to connect", None),
    "verbinding": ("noun", "connection", "de"),
    "verblijf": ("noun", "stay; residence", "het"),
    "verbreken": ("verb", "to break (connection)", None),
    "verdedigen": ("verb", "to defend", None),
    "verdediging": ("noun", "defense", "de"),
    "verdelen": ("verb", "to divide; to distribute", None),
    "verder": ("adjective", "further", None),
    "verdienen": ("verb", "to earn; to deserve", None),
    "verdieping": ("noun", "floor, story", "de"),
    "verdragen": ("verb", "to tolerate; to bear", None),
    "verdrag": ("noun", "treaty", "het"),
    "verdwijnen": ("verb", "to disappear", None),
    "vereisen": ("verb", "to require", None),
    "verenigen": ("verb", "to unite", None),
    "vereniging": ("noun", "association, union", "de"),
    "vergadering": ("noun", "meeting", "de"),
    "vergelijken": ("verb", "to compare", None),
    "vergelijking": ("noun", "comparison", "de"),
    "vergeten": ("verb", "to forget", None),
    "vergoeding": ("noun", "compensation", "de"),
    "vergroten": ("verb", "to enlarge; to increase", None),
    "vergunning": ("noun", "permit", "de"),
    "verhaal": ("noun", "story", "het"),
    "verhouding": ("noun", "ratio; relationship", "de"),
    "verklaren": ("verb", "to explain; to declare", None),
    "verklaring": ("noun", "explanation; statement", "de"),
    "verkeer": ("noun", "traffic", "het"),
    "verkeerd": ("adjective", "wrong", None),
    "verkiezen": ("verb", "to prefer; to elect", None),
    "verkiezing": ("noun", "election", "de"),
    "verkopen": ("verb", "to sell", None),
    "verkrijgen": ("verb", "to obtain", None),
    "verlangen": ("verb", "to desire; to long for", None),
    "verlaten": ("verb", "to leave", None),
    "verleden": ("noun", "past", "het"),
    "verliezen": ("verb", "to lose", None),
    "verlies": ("noun", "loss", "het"),
    "vermijden": ("verb", "to avoid", None),
    "verminderen": ("verb", "to reduce", None),
    "vermogen": ("noun", "ability; fortune", "het"),
    "vermoorden": ("verb", "to murder", None),
    "vernietigen": ("verb", "to destroy", None),
    "verontschuldigen": ("verb", "to apologize", None),
    "veroorzaken": ("verb", "to cause", None),
    "veroorloven": ("verb", "to afford", None),
    "verplichting": ("noun", "obligation", "de"),
    "verplichten": ("verb", "to oblige", None),
    "verplicht": ("adjective", "obligatory", None),
    "verrassen": ("verb", "to surprise", None),
    "verrassing": ("noun", "surprise", "de"),
    "verschaffen": ("verb", "to provide", None),
    "verscheiden": ("adjective", "several; diverse", None),
    "verschil": ("noun", "difference", "het"),
    "verschillen": ("verb", "to differ", None),
    "verschillend": ("adjective", "different, various", None),
    "verschijnen": ("verb", "to appear", None),
    "verschijning": ("noun", "appearance; phenomenon", "de"),
    "verschijnsel": ("noun", "phenomenon", "het"),
    "verslag": ("noun", "report", "het"),
    "verspreiden": ("verb", "to spread", None),
    "verstand": ("noun", "mind; sense", "het"),
    "verstandig": ("adjective", "wise, sensible", None),
    "verstaan": ("verb", "to understand (hearing)", None),
    "verstellen": ("verb", "to adjust", None),
    "verstoren": ("verb", "to disturb", None),
    "versterken": ("verb", "to strengthen", None),
    "vertellen": ("verb", "to tell", None),
    "vertegenwoordigen": ("verb", "to represent", None),
    "vertegenwoordiger": ("noun", "representative", "de"),
    "vertonen": ("verb", "to show; to display", None),
    "vertrekken": ("verb", "to depart", None),
    "vertrouwen": ("noun", "trust, confidence", "het"),
    "vervolgen": ("verb", "to continue; to prosecute", None),
    "vervolgens": ("adjective", "subsequently", None),
    "vervoer": ("noun", "transport", "het"),
    "verwachten": ("verb", "to expect", None),
    "verwachting": ("noun", "expectation", "de"),
    "verwant": ("adjective", "related", None),
    "verwarren": ("verb", "to confuse", None),
    "verwerken": ("verb", "to process", None),
    "verwerpen": ("verb", "to reject", None),
    "verwerven": ("verb", "to acquire", None),
    "verwijderen": ("verb", "to remove", None),
    "verwijten": ("verb", "to blame; to reproach", None),
    "verwijzen": ("verb", "to refer", None),
    "verzamelen": ("verb", "to collect", None),
    "verzameling": ("noun", "collection", "de"),
    "verzekeren": ("verb", "to insure; to assure", None),
    "verzekering": ("noun", "insurance", "de"),
    "verzet": ("noun", "resistance", "het"),
    "verzetten": ("verb", "to move; to resist", None),
    "verzoek": ("noun", "request", "het"),
    "verzoeken": ("verb", "to request", None),
    "verzorgen": ("verb", "to take care of", None),
    "verzorging": ("noun", "care", "de"),
    "vest": ("noun", "vest; waistcoat", "het"),
    "vestigen": ("verb", "to establish; to settle", None),
    "vet": ("adjective", "fat", None),
    "vieren": ("verb", "to celebrate", None),
    "vijand": ("noun", "enemy", "de"),
    "vijandig": ("adjective", "hostile", None),
    "vinden": ("verb", "to find; to think", None),
    "vinger": ("noun", "finger", "de"),
    "vlak": ("adjective", "flat; just", None),
    "vlam": ("noun", "flame", "de"),
    "vlees": ("noun", "meat", "het"),
    "vliegen": ("verb", "to fly", None),
    "vliegtuig": ("noun", "airplane", "het"),
    "vloer": ("noun", "floor", "de"),
    "vloeien": ("verb", "to flow", None),
    "vlucht": ("noun", "flight; escape", "de"),
    "vluchten": ("verb", "to flee", None),
    "vluchteling": ("noun", "refugee", "de"),
    "vlug": ("adjective", "quick", None),
    "voeden": ("verb", "to feed; to nourish", None),
    "voedsel": ("noun", "food", "het"),
    "voelen": ("verb", "to feel", None),
    "voeren": ("verb", "to conduct; to feed", None),
    "voet": ("noun", "foot", "de"),
    "voetbal": ("noun", "football, soccer", "het"),
    "vogel": ("noun", "bird", "de"),
    "vol": ("adjective", "full", None),
    "voldoen": ("verb", "to satisfy; to meet (requirements)", None),
    "voldoende": ("adjective", "sufficient", None),
    "volgen": ("verb", "to follow", None),
    "volgend": ("adjective", "next, following", None),
    "volgens": ("adjective", "according to", None),
    "volk": ("noun", "people, nation", "het"),
    "volkomen": ("adjective", "complete, perfect", None),
    "volledig": ("adjective", "complete", None),
    "volop": ("adjective", "plenty of", None),
    "volstaan": ("verb", "to suffice", None),
    "volume": ("noun", "volume", "het"),
    "vonnis": ("noun", "verdict", "het"),
    "voorbeeld": ("noun", "example", "het"),
    "voorbij": ("adjective", "past, over", None),
    "voordeel": ("noun", "advantage", "het"),
    "voordracht": ("noun", "presentation; nomination", "de"),
    "voorkomen": ("verb", "to prevent; to occur; to appear", None),
    "voorlopig": ("adjective", "provisional; for now", None),
    "voornaam": ("adjective", "distinguished; first (name)", None),
    "voornamelijk": ("adjective", "mainly", None),
    "voornemen": ("noun", "intention", "het"),
    "voorop": ("adjective", "in front; first", None),
    "voorstander": ("noun", "proponent", "de"),
    "voorstellen": ("verb", "to introduce; to propose; to imagine", None),
    "voorstel": ("noun", "proposal", "het"),
    "voorstelling": ("noun", "performance; idea", "de"),
    "voortbrengen": ("verb", "to produce", None),
    "voortdurend": ("adjective", "continuous", None),
    "voortgang": ("noun", "progress", "de"),
    "vooruit": ("adjective", "forward", None),
    "vooruitgang": ("noun", "progress", "de"),
    "voorwaarde": ("noun", "condition", "de"),
    "voorwerp": ("noun", "object", "het"),
    "voorzichtig": ("adjective", "careful", None),
    "voorzien": ("verb", "to foresee; to provide", None),
    "voorzitter": ("noun", "chairman", "de"),
    "vorderen": ("verb", "to progress; to demand", None),
    "vordering": ("noun", "progress; claim", "de"),
    "vorm": ("noun", "form, shape", "de"),
    "vormen": ("verb", "to form", None),
    "vorst": ("noun", "ruler; frost", "de"),
    "vraag": ("noun", "question; demand", "de"),
    "vragen": ("verb", "to ask", None),
    "vrede": ("noun", "peace", "de"),
    "vreemd": ("adjective", "strange; foreign", None),
    "vreemde": ("noun", "stranger", "de"),
    "vreemden": ("noun", "strangers", "de"),
    "vrees": ("noun", "fear", "de"),
    "vrezen": ("verb", "to fear", None),
    "vriend": ("noun", "friend", "de"),
    "vriendelijk": ("adjective", "friendly", None),
    "vriendschap": ("noun", "friendship", "de"),
    "vrij": ("adjective", "free", None),
    "vrijdag": ("noun", "Friday", "de"),
    "vrijheid": ("noun", "freedom", "de"),
    "vrijwel": ("adjective", "virtually, almost", None),
    "vroeg": ("adjective", "early", None),
    "vroeger": ("adjective", "formerly", None),
    "vrolijk": ("adjective", "cheerful", None),
    "vrouw": ("noun", "woman; wife", "de"),
    "vrouwelijk": ("adjective", "female; feminine", None),
    "vrucht": ("noun", "fruit", "de"),
    "vuil": ("adjective", "dirty", None),
    "vullen": ("verb", "to fill", None),
    "vuren": ("verb", "to fire", None),
    "vuur": ("noun", "fire", "het"),
    # W
    "waaien": ("verb", "to blow (wind)", None),
    "waard": ("adjective", "worth", None),
    "waarde": ("noun", "value", "de"),
    "waarderen": ("verb", "to appreciate; to value", None),
    "waardering": ("noun", "appreciation", "de"),
    "waardig": ("adjective", "dignified", None),
    "waarheen": ("adjective", "where to", None),
    "waarheid": ("noun", "truth", "de"),
    "waarlijk": ("adjective", "truly", None),
    "waarnemen": ("verb", "to observe; to deputize", None),
    "waarneming": ("noun", "observation", "de"),
    "waarom": ("adjective", "why", None),
    "waarschuwen": ("verb", "to warn", None),
    "waarschuwing": ("noun", "warning", "de"),
    "waarschijnlijk": ("adjective", "probably", None),
    "wachten": ("verb", "to wait", None),
    "wagen": ("verb", "to dare; to risk", None),
    "wand": ("noun", "wall (interior)", "de"),
    "wandelen": ("verb", "to walk, to stroll", None),
    "wapen": ("noun", "weapon", "het"),
    "warm": ("adjective", "warm", None),
    "warmte": ("noun", "warmth, heat", "de"),
    "wassen": ("verb", "to wash; to grow", None),
    "water": ("noun", "water", "het"),
    "wedstrijd": ("noun", "match, competition", "de"),
    "week": ("noun", "week", "de"),
    "weer": ("noun", "weather; again", "het"),
    "weerstand": ("noun", "resistance", "de"),
    "weg": ("noun", "road, way", "de"),
    "wegen": ("verb", "to weigh", None),
    "wegens": ("adjective", "because of", None),
    "weigeren": ("verb", "to refuse", None),
    "weinig": ("adjective", "few, little", None),
    "wekken": ("verb", "to wake; to arouse", None),
    "welk": ("adjective", "which", None),
    "wens": ("noun", "wish", "de"),
    "wensen": ("verb", "to wish", None),
    "wereld": ("noun", "world", "de"),
    "wereldoorlog": ("noun", "world war", "de"),
    "werk": ("noun", "work", "het"),
    "werkelijk": ("adjective", "real, actual", None),
    "werkelijkheid": ("noun", "reality", "de"),
    "werken": ("verb", "to work", None),
    "werker": ("noun", "worker", "de"),
    "werkgever": ("noun", "employer", "de"),
    "werking": ("noun", "functioning, effect", "de"),
    "werknemer": ("noun", "employee", "de"),
    "werkzaamheid": ("noun", "activity, work", "de"),
    "werpen": ("verb", "to throw", None),
    "wet": ("noun", "law", "de"),
    "wetenschap": ("noun", "science", "de"),
    "wetenschappelijk": ("adjective", "scientific", None),
    "wetenschapper": ("noun", "scientist", "de"),
    "weten": ("verb", "to know", None),
    "wetgeving": ("noun", "legislation", "de"),
    "wethouder": ("noun", "alderman", "de"),
    "wetten": ("verb", "to sharpen", None),
    "wettelijk": ("adjective", "legal", None),
    "wezen": ("noun", "being; essence", "het"),
    "wezenlijk": ("adjective", "essential", None),
    "wijd": ("adjective", "wide", None),
    "wijden": ("verb", "to devote; to consecrate", None),
    "wijk": ("noun", "neighborhood, district", "de"),
    "wijn": ("noun", "wine", "de"),
    "wijze": ("noun", "way, manner; wise person", "de"),
    "wijzen": ("verb", "to point", None),
    "wijziging": ("noun", "change, modification", "de"),
    "wijzigen": ("verb", "to change, to modify", None),
    "wil": ("noun", "will", "de"),
    "wild": ("adjective", "wild", None),
    "willen": ("verb", "to want", None),
    "wind": ("noun", "wind", "de"),
    "winkel": ("noun", "shop, store", "de"),
    "winnen": ("verb", "to win", None),
    "winst": ("noun", "profit", "de"),
    "winter": ("noun", "winter", "de"),
    "wisselen": ("verb", "to exchange; to change", None),
    "wit": ("adjective", "white", None),
    "wonen": ("verb", "to live (reside)", None),
    "woning": ("noun", "dwelling, house", "de"),
    "woord": ("noun", "word", "het"),
    "woordvoerder": ("noun", "spokesperson", "de"),
    "worden": ("verb", "to become", None),
    "woud": ("noun", "forest", "het"),
    "wraak": ("noun", "revenge", "de"),
    "wrijven": ("verb", "to rub", None),
    "wreed": ("adjective", "cruel", None),
    # Z
    "zaak": ("noun", "matter; business; case", "de"),
    "zaal": ("noun", "hall, room", "de"),
    "zacht": ("adjective", "soft; gentle", None),
    "zak": ("noun", "bag; pocket", "de"),
    "zakelijk": ("adjective", "businesslike", None),
    "zand": ("noun", "sand", "het"),
    "zee": ("noun", "sea", "de"),
    "zeeman": ("noun", "sailor", "de"),
    "zegen": ("noun", "blessing", "de"),
    "zeggen": ("verb", "to say", None),
    "zeil": ("noun", "sail", "het"),
    "zeilen": ("verb", "to sail", None),
    "zeker": ("adjective", "certain, sure", None),
    "zekerheid": ("noun", "certainty; security", "de"),
    "zelden": ("adjective", "seldom, rarely", None),
    "zelf": ("adjective", "self", None),
    "zelfstandig": ("adjective", "independent", None),
    "zenden": ("verb", "to send", None),
    "zenuw": ("noun", "nerve", "de"),
    "zestig": ("adjective", "sixty", None),
    "zetten": ("verb", "to put; to set", None),
    "zeventig": ("adjective", "seventy", None),
    "zicht": ("noun", "sight, view", "het"),
    "zichtbaar": ("adjective", "visible", None),
    "ziek": ("adjective", "sick", None),
    "zieke": ("noun", "sick person", "de"),
    "ziekenhuis": ("noun", "hospital", "het"),
    "ziekte": ("noun", "illness, disease", "de"),
    "ziel": ("noun", "soul", "de"),
    "zien": ("verb", "to see", None),
    "zijn": ("verb", "to be", None),
    "zilver": ("noun", "silver", "het"),
    "zin": ("noun", "sentence; sense; desire", "de"),
    "zinloos": ("adjective", "pointless", None),
    "zinnen": ("verb", "to ponder", None),
    "zitten": ("verb", "to sit", None),
    "zo": ("adjective", "so; like this", None),
    "zoeken": ("verb", "to search", None),
    "zogeheten": ("adjective", "so-called", None),
    "zogenaamd": ("adjective", "so-called", None),
    "zomer": ("noun", "summer", "de"),
    "zon": ("noun", "sun", "de"),
    "zondag": ("noun", "Sunday", "de"),
    "zonde": ("noun", "sin; pity", "de"),
    "zonlicht": ("noun", "sunlight", "het"),
    "zonnig": ("adjective", "sunny", None),
    "zoon": ("noun", "son", "de"),
    "zorg": ("noun", "care; worry", "de"),
    "zorgen": ("verb", "to take care of; to worry", None),
    "zorgvuldig": ("adjective", "careful, thorough", None),
    "zout": ("noun", "salt", "het"),
    "zucht": ("noun", "sigh", "de"),
    "zuchten": ("verb", "to sigh", None),
    "zuidelijk": ("adjective", "southern", None),
    "zuiden": ("noun", "south", "het"),
    "zuigeling": ("noun", "infant", "de"),
    "zuigen": ("verb", "to suck", None),
    "zuil": ("noun", "column, pillar", "de"),
    "zuinig": ("adjective", "economical, thrifty", None),
    "zuiver": ("adjective", "pure, clean", None),
    "zullen": ("verb", "to shall, will", None),
    "zuster": ("noun", "sister; nurse", "de"),
    "zuur": ("adjective", "sour", None),
    "zuurstof": ("noun", "oxygen", "de"),
    "zwaaien": ("verb", "to wave", None),
    "zwaar": ("adjective", "heavy", None),
    "zwaard": ("noun", "sword", "het"),
    "zwak": ("adjective", "weak", None),
    "zwanger": ("adjective", "pregnant", None),
    "zwangerschap": ("noun", "pregnancy", "de"),
    "zwart": ("adjective", "black", None),
    "zweet": ("noun", "sweat", "het"),
    "zwellen": ("verb", "to swell", None),
    "zwembad": ("noun", "swimming pool", "het"),
    "zwemmen": ("verb", "to swim", None),
    "zweren": ("verb", "to swear", None),
    "zwerven": ("verb", "to wander", None),
    "zweten": ("verb", "to sweat", None),
    "zweven": ("verb", "to float, to hover", None),
    "zwijgen": ("verb", "to be silent", None),
}
