WORDS = {
    "echo": ("noun", "echo", "de"),
    "echt": ("adjective", "real; really", None),
    "echtpaar": ("noun", "married couple", "het"),
    "echtscheiding": ("noun", "divorce", "de"),
    "econoom": ("noun", "economist", "de"),
    "edel": ("adjective", "noble", None),
    "eenheid": ("noun", "unit; unity", "de"),
    "eenzaam": ("adjective", "lonely", None),
    "eenzijdig": ("adjective", "one-sided", None),
    "eerbied": ("noun", "respect, reverence", "de"),
    "eeuw": ("noun", "century", "de"),
    "eeuwig": ("adjective", "eternal", None),
    "efficiënt": ("adjective", "efficient", None),
    "eigenaar": ("noun", "owner", "de"),
    "eigenschap": ("noun", "quality, property", "de"),
    "eik": ("noun", "oak", "de"),
    "eiland": ("noun", "island", "het"),
    "eind": ("noun", "end", "het"),
    "eindeloos": ("adjective", "endless", None),
    "eindigen": ("verb", "to end", None),
    "elegant": ("adjective", "elegant", None),
    "elektronisch": ("adjective", "electronic", None),
    "elementair": ("adjective", "elementary", None),
    "elite": ("noun", "elite", "de"),
    "elleboog": ("noun", "elbow", "de"),
    "ellendig": ("adjective", "miserable", None),
    "emancipatie": ("noun", "emancipation", "de"),
    "emmer": ("noun", "bucket", "de"),
    "emotie": ("noun", "emotion", "de"),
    "emotioneel": ("adjective", "emotional", None),
    "energie": ("noun", "energy", "de"),
    "enerzijds": ("adjective", "on the one hand", None),
    "eng": ("adjective", "scary; narrow", None),
    "enigszins": ("adjective", "somewhat", None),
    "enkeling": ("noun", "individual", "de"),
    "enthousiasme": ("noun", "enthusiasm", "het"),
    "envelop": ("noun", "envelope", "de"),
    "enzovoort": ("adjective", "and so on", None),
    "erf": ("noun", "yard, grounds", "het"),
    "erfelijk": ("adjective", "hereditary", None),
    "erfenis": ("noun", "inheritance", "de"),
    "ergernis": ("noun", "irritation, annoyance", "de"),
    "erotisch": ("adjective", "erotic", None),
    "etalage": ("noun", "shop window", "de"),
    "ethiek": ("noun", "ethics", "de"),
    "evaluatie": ("noun", "evaluation", "de"),
    "evangelie": ("noun", "gospel", "het"),
    "evenwicht": ("noun", "balance, equilibrium", "het"),
    "evenwichtig": ("adjective", "balanced", None),
    "evolutie": ("noun", "evolution", "de"),
    "exact": ("adjective", "exact", None),
    "examen": ("noun", "exam", "het"),
    "exclusief": ("adjective", "exclusive", None),
    "excuus": ("noun", "excuse, apology", "het"),
    "expeditie": ("noun", "expedition", "de"),
    "experiment": ("noun", "experiment", "het"),
    "experimenteel": ("adjective", "experimental", None),
    "experimenteren": ("verb", "to experiment", None),
    "expliciet": ("adjective", "explicit", None),
    "explosie": ("noun", "explosion", "de"),
    "extern": ("adjective", "external", None),
    "extreem": ("adjective", "extreme", None),
    "ezel": ("noun", "donkey", "de"),
    "fabriek": ("noun", "factory", "de"),
    "fabrikant": ("noun", "manufacturer", "de"),
    "factor": ("noun", "factor", "de"),
    "faculteit": ("noun", "faculty", "de"),
    "fantastisch": ("adjective", "fantastic", None),
    "fascineren": ("verb", "to fascinate", None),
    "fataal": ("adjective", "fatal", None),
    "fatsoenlijk": ("adjective", "decent, proper", None),
    "feest": ("noun", "party, celebration", "het"),
    "feestelijk": ("adjective", "festive", None),
    "fel": ("adjective", "fierce; bright", None),
    "fenomeen": ("noun", "phenomenon", "het"),
    "fiets": ("noun", "bicycle", "de"),
    "fietsen": ("verb", "to cycle", None),
    "fijn": ("adjective", "fine; nice", None),
    "film": ("noun", "film, movie", "de"),
    "filosofisch": ("adjective", "philosophical", None),
    "fles": ("noun", "bottle", "de"),
    "flink": ("adjective", "considerable; brave", None),
    "fluisteren": ("verb", "to whisper", None),
    "fonds": ("noun", "fund", "het"),
    "formule": ("noun", "formula", "de"),
    "formulering": ("noun", "wording, formulation", "de"),
    "fors": ("adjective", "sturdy; substantial", None),
    "fort": ("noun", "fort", "het"),
    "fotograaf": ("noun", "photographer", "de"),
    "fotograferen": ("verb", "to photograph", None),
    "fraai": ("adjective", "beautiful, fine", None),
    "fragment": ("noun", "fragment", "het"),
    "fruit": ("noun", "fruit", "het"),
    "frustratie": ("noun", "frustration", "de"),
    "functionaris": ("noun", "official, functionary", "de"),
    "functioneel": ("adjective", "functional", None),
    "fundamenteel": ("adjective", "fundamental", None),
    "fungeren": ("verb", "to function as", None),
    "gadeslaan": ("verb", "to observe, to watch", None),
    "gangbaar": ("adjective", "common, current", None),
    "gans": ("noun", "goose", "de"),
    "gapen": ("verb", "to yawn", None),
    "garage": ("noun", "garage", "de"),
    "garanderen": ("verb", "to guarantee", None),
    "garantie": ("noun", "guarantee", "de"),
    "gat": ("noun", "hole", "het"),
    "gave": ("noun", "gift, talent", "de"),
    "gebaar": ("noun", "gesture", "het"),
    "gebaren": ("verb", "to gesture", None),
    "gebieden": ("verb", "to command; to demand", None),
    "gebit": ("noun", "teeth; dentures", "het"),
    "gebod": ("noun", "commandment", "het"),
    "geboorte": ("noun", "birth", "de"),
    "geboren": ("adjective", "born", None),
    "gebrekkig": ("adjective", "deficient, poor", None),
    "gebruikelijk": ("adjective", "usual, customary", None),
    "gecompliceerd": ("adjective", "complicated", None),
    "gedaante": ("noun", "shape, form", "de"),
    "gedeeltelijk": ("adjective", "partial", None),
    "gedicht": ("noun", "poem", "het"),
    "geding": ("noun", "legal case; issue", "het"),
    "gedoe": ("noun", "fuss, hassle", "het"),
    "gedragen": ("verb", "to behave", None),
    "gedreven": ("adjective", "driven, passionate", None),
    "geduldig": ("adjective", "patient", None),
    "geestelijk": ("adjective", "spiritual; mental", None),
    "geheugen": ("noun", "memory", "het"),
    "gehoor": ("noun", "hearing; audience", "het"),
    "gehoorzamen": ("verb", "to obey", None),
    "geit": ("noun", "goat", "de"),
    "gelaat": ("noun", "face, countenance", "het"),
    "geleerd": ("adjective", "learned, scholarly", None),
    "geleerde": ("noun", "scholar", "de"),
    "gelegen": ("adjective", "situated; convenient", None),
    "geliefd": ("adjective", "beloved", None),
    "gelijk": ("adjective", "equal; right", None),
    "gelijken": ("verb", "to resemble", None),
    "gelijkenis": ("noun", "resemblance; parable", "de"),
    "gelijktijdig": ("adjective", "simultaneous", None),
    "gelovige": ("noun", "believer", "de"),
    "gemak": ("noun", "ease, comfort", "het"),
    "gemeen": ("adjective", "mean; common", None),
    "gemeenschap": ("noun", "community", "de"),
    "gemeenschappelijk": ("adjective", "communal, shared", None),
    "gemeentelijk": ("adjective", "municipal", None),
    "gemeenteraad": ("noun", "city council", "de"),
    "gemiddelde": ("noun", "average", "het"),
    "genade": ("noun", "mercy, grace", "de"),
    "geneeskunde": ("noun", "medicine (science)", "de"),
    "genegenheid": ("noun", "affection", "de"),
    "geneigd": ("adjective", "inclined", None),
    "generaal": ("noun", "general", "de"),
    "genetisch": ("adjective", "genetic", None),
    "genezen": ("verb", "to heal, to cure", None),
    "genie": ("noun", "genius", "het"),
    "gereedschap": ("noun", "tools", "het"),
    "gering": ("adjective", "small, slight", None),
    "gerucht": ("noun", "rumor", "het"),
    "geruststellen": ("verb", "to reassure", None),
    "geschenk": ("noun", "gift, present", "het"),
    "geslaagd": ("adjective", "successful", None),
    "gesloten": ("adjective", "closed", None),
    "gesteld": ("adjective", "set; disposed", None),
    "getuigenis": ("noun", "testimony", "de"),
    "geur": ("noun", "scent, smell", "de"),
    "geuren": ("verb", "to smell (good)", None),
    "gevangen": ("adjective", "captured, imprisoned", None),
    "gevel": ("noun", "facade", "de"),
    "gevestigd": ("adjective", "established", None),
    "gewaarwording": ("noun", "sensation, perception", "de"),
    "geweer": ("noun", "rifle", "het"),
    "gewest": ("noun", "region, province", "het"),
    "gewijd": ("adjective", "devoted; sacred", None),
    "gewoonlijk": ("adjective", "usually", None),
    "gezellig": ("adjective", "cozy, sociable", None),
    "gezelschap": ("noun", "company, group", "het"),
    "gezichtspunt": ("noun", "point of view", "het"),
    "gezondheidszorg": ("noun", "healthcare", "de"),
    "geïnteresseerd": ("adjective", "interested", None),
    "gids": ("noun", "guide", "de"),
    "giftig": ("adjective", "poisonous, toxic", None),
    "gigantisch": ("adjective", "gigantic", None),
    "glans": ("noun", "shine, luster", "de"),
    "glijden": ("verb", "to slide, to glide", None),
    "glimlach": ("noun", "smile", "de"),
    "glinsteren": ("verb", "to glitter, to sparkle", None),
    "globaal": ("adjective", "global; rough", None),
    "gloed": ("noun", "glow", "de"),
    "glorie": ("noun", "glory", "de"),
    "godheid": ("noun", "deity", "de"),
    "godsdienst": ("noun", "religion", "de"),
    "goederen": ("noun", "goods", "de"),
    "goedheid": ("noun", "goodness", "de"),
    "goedkeuren": ("verb", "to approve", None),
    "goedkeuring": ("noun", "approval", "de"),
    "golf": ("noun", "wave; golf", "de"),
    "golven": ("verb", "to wave, to undulate", None),
    "gooien": ("verb", "to throw", None),
    "gordijn": ("noun", "curtain", "het"),
    "gouverneur": ("noun", "governor", "de"),
    "graan": ("noun", "grain", "het"),
    "gracht": ("noun", "canal (city)", "de"),
    "grappig": ("adjective", "funny", None),
    "gras": ("noun", "grass", "het"),
    "gratis": ("adjective", "free (no cost)", None),
    "greep": ("noun", "grip; handle", "de"),
    "grenzen": ("verb", "to border on", None),
    "gretig": ("adjective", "eager, greedy", None),
    "griezelig": ("adjective", "creepy", None),
    "grijns": ("noun", "grin", "de"),
    "grijpen": ("verb", "to grab, to seize", None),
    "grijs": ("adjective", "gray", None),
    "grillig": ("adjective", "capricious, erratic", None),
    "grimmig": ("adjective", "grim, fierce", None),
    "groen": ("adjective", "green", None),
    "groepering": ("noun", "grouping", "de"),
    "groet": ("noun", "greeting", "de"),
    "grondslag": ("noun", "foundation, basis", "de"),
    "grondstof": ("noun", "raw material", "de"),
    "grondwet": ("noun", "constitution", "de"),
    "groots": ("adjective", "grand, grandiose", None),
    "grot": ("noun", "cave", "de"),
    "gruwelijk": ("adjective", "gruesome, horrible", None),
    "gunstig": ("adjective", "favorable", None),
    "haak": ("noun", "hook", "de"),
    "haan": ("noun", "rooster", "de"),
    "haard": ("noun", "fireplace; hearth", "de"),
    "haast": ("noun", "haste, hurry", "de"),
    "hak": ("noun", "heel; chop", "de"),
    "haken": ("verb", "to hook; to crochet", None),
    "hakken": ("verb", "to chop", None),
    "hals": ("noun", "neck", "de"),
    "handdoek": ("noun", "towel", "de"),
    "handel": ("noun", "trade, commerce", "de"),
    "handelaar": ("noun", "trader, merchant", "de"),
    "handhaven": ("verb", "to maintain, to uphold", None),
    "handschoen": ("noun", "glove", "de"),
    "handschrift": ("noun", "handwriting", "het"),
    "hardnekkig": ("adjective", "stubborn, persistent", None),
    "hardop": ("adjective", "aloud", None),
    "harmonie": ("noun", "harmony", "de"),
    "hartstocht": ("noun", "passion", "de"),
    "hartstochtelijk": ("adjective", "passionate", None),
    "hebben": ("verb", "to have", None),
    "hecht": ("adjective", "close, tight", None),
    "heden": ("noun", "present (time)", "het"),
    "hedendaags": ("adjective", "contemporary", None),
    "heel": ("adjective", "whole; very", None),
    "heelal": ("noun", "universe", "het"),
    "heer": ("noun", "gentleman; lord", "de"),
    "heerlijk": ("adjective", "delicious; wonderful", None),
    "heersen": ("verb", "to rule; to prevail", None),
    "heet": ("adjective", "hot", None),
    "heil": ("noun", "salvation", "het"),
    "heilig": ("adjective", "holy, sacred", None),
    "heimelijk": ("adjective", "secret, stealthy", None),
    "heimwee": ("noun", "homesickness", "het"),
    "hekel": ("noun", "dislike", "de"),
    "heks": ("noun", "witch", "de"),
    "hel": ("noun", "hell", "de"),
    "helder": ("adjective", "clear, bright", None),
    "helemaal": ("adjective", "completely", None),
    "helm": ("noun", "helmet", "de"),
    "hemel": ("noun", "sky, heaven", "de"),
    "herfst": ("noun", "autumn, fall", "de"),
    "herhaling": ("noun", "repetition, repeat", "de"),
    "herkomst": ("noun", "origin", "de"),
    "hervorming": ("noun", "reform", "de"),
    "heten": ("verb", "to be called", None),
    "hetzelfde": ("adjective", "the same", None),
    "heuvel": ("noun", "hill", "de"),
    "hevig": ("adjective", "fierce, severe", None),
    "hijsen": ("verb", "to hoist", None),
    "hinderen": ("verb", "to hinder, to bother", None),
    "hinderlijk": ("adjective", "annoying", None),
    "historicus": ("noun", "historian", "de"),
    "hoed": ("noun", "hat", "de"),
    "hoer": ("noun", "prostitute", "de"),
    "hoesten": ("verb", "to cough", None),
    "hoeveelheid": ("noun", "quantity, amount", "de"),
    "hoeven": ("verb", "to need to", None),
    "hok": ("noun", "cage; shed", "het"),
    "hond": ("noun", "dog", "de"),
    "honger": ("noun", "hunger", "de"),
    "hoofd": ("noun", "head", "het"),
    "hoofdpijn": ("noun", "headache", "de"),
    "hoofdstuk": ("noun", "chapter", "het"),
    "hoofdzakelijk": ("adjective", "mainly", None),
    "hoogleraar": ("noun", "professor", "de"),
    "hoogtepunt": ("noun", "highlight, peak", "het"),
    "hoop": ("noun", "hope; heap", "de"),
    "hopeloos": ("adjective", "hopeless", None),
    "hopen": ("verb", "to hope", None),
    "horizontaal": ("adjective", "horizontal", None),
    "houvast": ("noun", "grip; support", "het"),
    "huid": ("noun", "skin", "de"),
    "huidig": ("adjective", "current, present", None),
    "huilen": ("verb", "to cry", None),
    "huisarts": ("noun", "family doctor", "de"),
    "huiskamer": ("noun", "living room", "de"),
    "huiveren": ("verb", "to shiver; to shudder", None),
    "hulpeloos": ("adjective", "helpless", None),
    "hulpmiddel": ("noun", "tool, aid", "het"),
    "hulpverlener": ("noun", "aid worker", "de"),
    "humor": ("noun", "humor", "de"),
    "huur": ("noun", "rent", "de"),
    "hypothese": ("noun", "hypothesis", "de"),
    "identiek": ("adjective", "identical", None),
    "identificeren": ("verb", "to identify", None),
    "ideologie": ("noun", "ideology", "de"),
    "idioot": ("adjective", "idiotic; idiot", None),
    "ieder": ("adjective", "every, each", None),
    "iedereen": ("adjective", "everyone", None),
    "iemand": ("adjective", "someone", None),
    "iets": ("adjective", "something", None),
    "illegaal": ("adjective", "illegal", None),
    "illustratie": ("noun", "illustration", "de"),
    "illustreren": ("verb", "to illustrate", None),
    "impliceren": ("verb", "to imply", None),
    "impuls": ("noun", "impulse", "de"),
    "inbrengen": ("verb", "to bring in; to contribute", None),
    "incident": ("noun", "incident", "het"),
    "inclusief": ("adjective", "inclusive", None),
    "indelen": ("verb", "to classify, to divide", None),
    "inderdaad": ("adjective", "indeed", None),
    "indienen": ("verb", "to submit", None),
    "indirect": ("adjective", "indirect", None),
    "individu": ("noun", "individual", "het"),
    "individueel": ("adjective", "individual", None),
    "infectie": ("noun", "infection", "de"),
    "ingaan": ("verb", "to enter; to take effect", None),
    "ingenieur": ("noun", "engineer", "de"),
    "ingewikkeld": ("adjective", "complicated", None),
    "ingreep": ("noun", "intervention; operation", "de"),
    "inheems": ("adjective", "indigenous", None),
    "inhoudelijk": ("adjective", "substantive, content-related", None),
    "inhouden": ("verb", "to contain; to withhold", None),
    "initiatief": ("noun", "initiative", "het"),
    "inkomsten": ("noun", "income, revenue", "de"),
    "inlichten": ("verb", "to inform", None),
    "inlichting": ("noun", "information", "de"),
    "innemen": ("verb", "to take (medicine); to capture", None),
    "innerlijk": ("adjective", "inner, internal", None),
    "innig": ("adjective", "intimate, heartfelt", None),
    "inrichting": ("noun", "institution; layout", "de"),
    "inschakelen": ("verb", "to engage; to call in", None),
    "insect": ("noun", "insect", "het"),
    "inspecteur": ("noun", "inspector", "de"),
    "inspiratie": ("noun", "inspiration", "de"),
    "inspireren": ("verb", "to inspire", None),
    "inspraak": ("noun", "voice, say", "de"),
    "installeren": ("verb", "to install", None),
    "instantie": ("noun", "authority, instance", "de"),
    "instemming": ("noun", "approval, agreement", "de"),
    "instinct": ("noun", "instinct", "het"),
    "instrument": ("noun", "instrument", "het"),
    "integendeel": ("adjective", "on the contrary", None),
    "integratie": ("noun", "integration", "de"),
    "integreren": ("verb", "to integrate", None),
    "intensiteit": ("noun", "intensity", "de"),
    "interactie": ("noun", "interaction", "de"),
    "interesseren": ("verb", "to interest", None),
    "intern": ("adjective", "internal", None),
    "intiem": ("adjective", "intimate", None),
    "intrekken": ("verb", "to withdraw; to move in", None),
    "introduceren": ("verb", "to introduce", None),
    "intuïtie": ("noun", "intuition", "de"),
    "inval": ("noun", "raid; idea", "de"),
    "investering": ("noun", "investment", "de"),
    "invullen": ("verb", "to fill in", None),
    "inwendig": ("adjective", "internal, inner", None),
    "inzetten": ("verb", "to deploy; to bet", None),
    "ironie": ("noun", "irony", "de"),
    "ironisch": ("adjective", "ironic", None),
    "irriteren": ("verb", "to irritate", None),
    "islam": ("noun", "Islam", "de"),
    "isoleren": ("verb", "to isolate", None),
    "jager": ("noun", "hunter", "de"),
    "jaloezie": ("noun", "jealousy", "de"),
    "jas": ("noun", "coat", "de"),
    "jeugdig": ("adjective", "youthful", None),
    "jongen": ("noun", "boy", "de"),
    "jurk": ("noun", "dress", "de"),
    "juweel": ("noun", "jewel", "het"),
    "kaak": ("noun", "jaw", "de"),
    "kaars": ("noun", "candle", "de"),
    "kaas": ("noun", "cheese", "de"),
    "kabel": ("noun", "cable", "de"),
    "kachel": ("noun", "stove, heater", "de"),
    "kade": ("noun", "quay", "de"),
    "kader": ("noun", "framework", "het"),
    "kalm": ("adjective", "calm", None),
    "kalmeren": ("verb", "to calm down", None),
    "kandidaat": ("noun", "candidate", "de"),
    "kanker": ("noun", "cancer", "de"),
    "kanon": ("noun", "cannon", "het"),
    "kapel": ("noun", "chapel", "de"),
    "kapitalisme": ("noun", "capitalism", "het"),
    "kapitein": ("noun", "captain", "de"),
    "kapot": ("adjective", "broken", None),
    "kar": ("noun", "cart", "de"),
    "karakteristiek": ("adjective", "characteristic", None),
    "kas": ("noun", "greenhouse; cash register", "de"),
    "kast": ("noun", "closet, cabinet", "de"),
    "kathedraal": ("noun", "cathedral", "de"),
    "katholiek": ("adjective", "Catholic", None),
    "kauwen": ("verb", "to chew", None),
    "keel": ("noun", "throat", "de"),
    "keer": ("noun", "time (occasion)", "de"),
    "kei": ("noun", "boulder; ace", "de"),
    "kelner": ("noun", "waiter", "de"),
    "kenbaar": ("adjective", "recognizable; known", None),
    "kenmerk": ("noun", "characteristic, feature", "het"),
    "kenmerkend": ("adjective", "characteristic", None),
    "kennelijk": ("adjective", "apparently", None),
    "kerel": ("noun", "fellow, guy", "de"),
    "kerkhof": ("noun", "cemetery", "het"),
    "keten": ("noun", "chain", "de"),
    "ketting": ("noun", "chain; necklace", "de"),
    "keuren": ("verb", "to inspect; to approve", None),
    "keurig": ("adjective", "neat, proper", None),
    "keuze": ("noun", "choice", "de"),
    "kiezer": ("noun", "voter", "de"),
    "kijker": ("noun", "viewer; binoculars", "de"),
    "kilo": ("noun", "kilo", "de"),
    "kilometer": ("noun", "kilometer", "de"),
    "kin": ("noun", "chin", "de"),
    "kinderlijk": ("adjective", "childlike", None),
    "kip": ("noun", "chicken", "de"),
    "kist": ("noun", "box; coffin", "de"),
    "klaar": ("adjective", "ready; finished", None),
    "klagen": ("verb", "to complain", None),
    "klappen": ("verb", "to clap; to hit", None),
    "klassiek": ("adjective", "classical", None),
    "kleren": ("noun", "clothes", "de"),
    "kletsen": ("verb", "to chat; to talk nonsense", None),
    "kleuren": ("verb", "to color", None),
    "kleurig": ("adjective", "colorful", None),
    "kleuter": ("noun", "toddler", "de"),
    "kleven": ("verb", "to stick", None),
    "kliniek": ("noun", "clinic", "de"),
    "klok": ("noun", "clock; bell", "de"),
    "kloof": ("noun", "gap; gorge", "de"),
    "knaap": ("noun", "boy, lad", "de"),
    "knap": ("adjective", "handsome; clever", None),
    "knecht": ("noun", "servant", "de"),
    "knielen": ("verb", "to kneel", None),
    "knijpen": ("verb", "to pinch; to squeeze", None),
    "knikken": ("verb", "to nod", None),
    "knippen": ("verb", "to cut (scissors)", None),
    "knop": ("noun", "button; bud", "de"),
    "knopen": ("verb", "to tie, to knot", None),
    "koe": ("noun", "cow", "de"),
    "koel": ("adjective", "cool", None),
    "koepel": ("noun", "dome", "de"),
    "koesteren": ("verb", "to cherish", None),
    "koffer": ("noun", "suitcase", "de"),
    "koffie": ("noun", "coffee", "de"),
    "kogel": ("noun", "bullet", "de"),
    "kolonel": ("noun", "colonel", "de"),
    "kom": ("noun", "bowl", "de"),
    "komst": ("noun", "coming, arrival", "de"),
    "konijn": ("noun", "rabbit", "het"),
    "koningin": ("noun", "queen", "de"),
    "kooi": ("noun", "cage", "de"),
    "koop": ("noun", "purchase", "de"),
    "koor": ("noun", "choir", "het"),
    "koorts": ("noun", "fever", "de"),
    "koper": ("noun", "buyer; copper", "de"),
    "kopie": ("noun", "copy", "de"),
    "koppig": ("adjective", "stubborn", None),
    "kostbaar": ("adjective", "precious, valuable", None),
    "kostuum": ("noun", "suit; costume", "het"),
    "kou": ("noun", "cold", "de"),
    "kraag": ("noun", "collar", "de"),
    "kraan": ("noun", "tap; crane", "de"),
    "krabben": ("verb", "to scratch", None),
    "kraken": ("verb", "to crack; to squat", None),
    "krankzinnig": ("adjective", "insane", None),
    "kreet": ("noun", "cry, shout", "de"),
    "kreunen": ("verb", "to groan", None),
    "krijger": ("noun", "warrior", "de"),
    "krimpen": ("verb", "to shrink", None),
    "kring": ("noun", "circle", "de"),
    "kroeg": ("noun", "pub, bar", "de"),
    "kruid": ("noun", "herb", "het"),
    "kruisen": ("verb", "to cross", None),
    "kudde": ("noun", "herd, flock", "de"),
    "kuil": ("noun", "pit, hole", "de"),
    "kunnen": ("verb", "to be able to, can", None),
    "kunstwerk": ("noun", "work of art", "het"),
    "kus": ("noun", "kiss", "de"),
    "kussen": ("verb", "to kiss", None),
    "kwaal": ("noun", "ailment", "de"),
    "kwalijk": ("adjective", "wrong; badly", None),
    "kweken": ("verb", "to grow, to breed", None),
    "kwellen": ("verb", "to torment", None),
    "kwetsbaar": ("adjective", "vulnerable", None),
    "kwetsen": ("verb", "to hurt, to injure", None),
    "kwijt": ("adjective", "lost, missing", None),
    "kwijtraken": ("verb", "to lose", None),
}
