WORDS = {
    # A
    "aanbevelen": ("verb", "to recommend", None),
    "aanbeveling": ("noun", "recommendation", "de"),
    "aanbieden": ("verb", "to offer", None),
    "aanblik": ("noun", "sight, view", "de"),
    "aanbod": ("noun", "offer, supply", "het"),
    "aanbreken": ("verb", "to break open; to dawn", None),
    "aanbrengen": ("verb", "to apply; to install", None),
    "aandacht": ("noun", "attention", "de"),
    "aandachtig": ("adjective", "attentive", None),
    "aandeel": ("noun", "share, part", "het"),
    "aandoen": ("verb", "to put on; to affect", None),
    "aandoening": ("noun", "condition, ailment", "de"),
    "aandringen": ("verb", "to insist", None),
    "aanduiden": ("verb", "to indicate", None),
    "aangaan": ("verb", "to enter into; to concern", None),
    "aangeboren": ("adjective", "innate, inborn", None),
    "aangelegenheid": ("noun", "matter, affair", "de"),
    "aangenaam": ("adjective", "pleasant", None),
    "aangeven": ("verb", "to indicate; to hand", None),
    "aangewezen": ("adjective", "designated; dependent on", None),
    "aanhalen": ("verb", "to quote; to tighten", None),
    "aanhanger": ("noun", "supporter, follower", "de"),
    "aanhouden": ("verb", "to arrest; to persist", None),
    "aankijken": ("verb", "to look at", None),
    "aankomen": ("verb", "to arrive", None),
    "aankomst": ("noun", "arrival", "de"),
    "aankondigen": ("verb", "to announce", None),
    "aankoop": ("noun", "purchase", "de"),
    "aanleg": ("noun", "talent; construction", "de"),
    "aanleggen": ("verb", "to construct; to create", None),
    "aanleiding": ("noun", "cause, reason", "de"),
    "aanmerking": ("noun", "consideration, remark", "de"),
    "aanmoedigen": ("verb", "to encourage", None),
    "aannemen": ("verb", "to accept; to assume", None),
    "aanpak": ("noun", "approach", "de"),
    "aanpakken": ("verb", "to tackle", None),
    "aanpassen": ("verb", "to adapt, to adjust", None),
    "aanraden": ("verb", "to advise", None),
    "aanraken": ("verb", "to touch", None),
    "aanraking": ("noun", "touch, contact", "de"),
    "aanslag": ("noun", "attack; deposit", "de"),
    "aansluiten": ("verb", "to connect; to join", None),
    "aansluiting": ("noun", "connection", "de"),
    "aanspraak": ("noun", "claim", "de"),
    "aanspreken": ("verb", "to address; to appeal to", None),
    "aantal": ("noun", "number, quantity", "het"),
    "aantasten": ("verb", "to damage; to affect", None),
    "aantekening": ("noun", "note", "de"),
    "aantonen": ("verb", "to demonstrate, to prove", None),
    "aantreffen": ("verb", "to encounter, to find", None),
    "aantrekkelijk": ("adjective", "attractive", None),
    "aantrekken": ("verb", "to attract; to put on", None),
    "aanvaarden": ("verb", "to accept", None),
    "aanval": ("noun", "attack", "de"),
    "aanvallen": ("verb", "to attack", None),
    "aanvankelijk": ("adjective", "initial", None),
    "aanvullen": ("verb", "to supplement", None),
    "aanvulling": ("noun", "supplement, addition", "de"),
    "aanwezig": ("adjective", "present", None),
    "aanwezigheid": ("noun", "presence", "de"),
    "aanwijzen": ("verb", "to point out; to appoint", None),
    "aanwijzing": ("noun", "instruction, indication", "de"),
    "aanzien": ("noun", "prestige; appearance", "het"),
    "aanzienlijk": ("adjective", "considerable", None),
    "aard": ("noun", "nature, character", "de"),
    "aardappel": ("noun", "potato", "de"),
    "aarde": ("noun", "earth", "de"),
    "aardig": ("adjective", "nice, kind", None),
    "aards": ("adjective", "earthly", None),
    "aarzelen": ("verb", "to hesitate", None),
    "absoluut": ("adjective", "absolute", None),
    "accent": ("noun", "accent", "het"),
    "accepteren": ("verb", "to accept", None),
    "actie": ("noun", "action", "de"),
    "actief": ("adjective", "active", None),
    "activiteit": ("noun", "activity", "de"),
    "adem": ("noun", "breath", "de"),
    "ademen": ("verb", "to breathe", None),
    "administratief": ("adjective", "administrative", None),
    "adres": ("noun", "address", "het"),
    "advies": ("noun", "advice", "het"),
    "advocaat": ("noun", "lawyer", "de"),
    "afdeling": ("noun", "department", "de"),
    "afgezien": ("adjective", "apart from", None),
    "afhankelijk": ("adjective", "dependent", None),
    "afkeer": ("noun", "aversion", "de"),
    "afkomstig": ("adjective", "originating from", None),
    "afleggen": ("verb", "to cover (distance); to take (exam)", None),
    "afleiden": ("verb", "to derive; to distract", None),
    "afloop": ("noun", "end, outcome", "de"),
    "aflopen": ("verb", "to end, to expire", None),
    "afnemen": ("verb", "to decrease; to take away", None),
    "afscheid": ("noun", "farewell", "het"),
    "afschuwelijk": ("adjective", "horrible, awful", None),
    "afsluiten": ("verb", "to close; to conclude", None),
    "afspelen": ("verb", "to play; to take place", None),
    "afspraak": ("noun", "appointment, agreement", "de"),
    "afstand": ("noun", "distance", "de"),
    "afvragen": ("verb", "to wonder", None),
    "afwijken": ("verb", "to deviate", None),
    "afwijking": ("noun", "deviation", "de"),
    "afwijzen": ("verb", "to reject", None),
    "afzonderlijk": ("adjective", "separate, individual", None),
    "agent": ("noun", "police officer; agent", "de"),
    "agressief": ("adjective", "aggressive", None),
    "alcohol": ("noun", "alcohol", "de"),
    "algemeen": ("adjective", "general", None),
    "allerlei": ("adjective", "all kinds of", None),
    "alternatief": ("noun", "alternative", "het"),
    "ambtenaar": ("noun", "civil servant", "de"),
    "analyse": ("noun", "analysis", "de"),
    "analyseren": ("verb", "to analyze", None),
    "angst": ("noun", "fear, anxiety", "de"),
    "angstig": ("adjective", "anxious, fearful", None),
    "antwoord": ("noun", "answer", "het"),
    "antwoorden": ("verb", "to answer", None),
    "apart": ("adjective", "separate; special", None),
    "apparaat": ("noun", "device, apparatus", "het"),
    "appel": ("noun", "apple", "de"),
    "arbeid": ("noun", "labor, work", "de"),
    "arbeider": ("noun", "worker", "de"),
    "argument": ("noun", "argument", "het"),
    "arm": ("noun", "arm", "de"),
    "artikel": ("noun", "article", "het"),
    "arts": ("noun", "doctor", "de"),
    "aspect": ("noun", "aspect", "het"),
    "auteur": ("noun", "author", "de"),
    "auto": ("noun", "car", "de"),
    "automatisch": ("adjective", "automatic", None),
    "autoriteit": ("noun", "authority", "de"),
    "avond": ("noun", "evening", "de"),
    "avontuur": ("noun", "adventure", "het"),
    # B
    "baan": ("noun", "job; lane", "de"),
    "baas": ("noun", "boss", "de"),
    "baby": ("noun", "baby", "de"),
    "bad": ("noun", "bath", "het"),
    "badkamer": ("noun", "bathroom", "de"),
    "bal": ("noun", "ball", "de"),
    "band": ("noun", "band; tire; bond", "de"),
    "bang": ("adjective", "afraid, scared", None),
    "bank": ("noun", "bank; couch", "de"),
    "bar": ("adjective", "harsh; bar", None),
    "barsten": ("verb", "to burst, to crack", None),
    "baseren": ("verb", "to base", None),
    "basis": ("noun", "basis, foundation", "de"),
    "beantwoorden": ("verb", "to answer", None),
    "bed": ("noun", "bed", "het"),
    "bedacht": ("adjective", "prepared for; devised", None),
    "bedanken": ("verb", "to thank; to decline", None),
    "bedekken": ("verb", "to cover", None),
    "bedenken": ("verb", "to think of; to consider", None),
    "bedienen": ("verb", "to serve; to operate", None),
    "bedoelen": ("verb", "to mean, to intend", None),
    "bedoeling": ("noun", "intention, purpose", "de"),
    "bedrag": ("noun", "amount", "het"),
    "bedragen": ("verb", "to amount to", None),
    "bedreigen": ("verb", "to threaten", None),
    "bedreiging": ("noun", "threat", "de"),
    "bedriegen": ("verb", "to deceive", None),
    "bedrijf": ("noun", "company, business", "het"),
    "bedrijven": ("verb", "to commit (a crime)", None),
    "beeld": ("noun", "image, picture", "het"),
    "been": ("noun", "leg; bone", "het"),
    "beest": ("noun", "beast, animal", "het"),
    "beet": ("noun", "bite", "de"),
    "beetje": ("noun", "a little bit", "het"),
    "begeleiden": ("verb", "to accompany; to guide", None),
    "begeven": ("verb", "to give way; to go to", None),
    "begin": ("noun", "beginning", "het"),
    "beginnen": ("verb", "to begin", None),
    "beginsel": ("noun", "principle", "het"),
    "begrafenis": ("noun", "funeral", "de"),
    "begraven": ("verb", "to bury", None),
    "begrijpelijk": ("adjective", "understandable", None),
    "begrijpen": ("verb", "to understand", None),
    "begrip": ("noun", "concept; understanding", "het"),
    "begroeten": ("verb", "to greet", None),
    "behandelen": ("verb", "to treat; to handle", None),
    "behandeling": ("noun", "treatment", "de"),
    "beheersen": ("verb", "to control; to master", None),
    "behoefte": ("noun", "need", "de"),
    "behoren": ("verb", "to belong to; ought to", None),
    "behouden": ("verb", "to keep, to retain", None),
    "behoorlijk": ("adjective", "considerable; proper", None),
    "beide": ("adjective", "both", None),
    "bejaarde": ("noun", "elderly person", "de"),
    "bekend": ("adjective", "known, famous", None),
    "bekennen": ("verb", "to confess", None),
    "bekijken": ("verb", "to look at, to examine", None),
    "bel": ("noun", "bell", "de"),
    "belachelijk": ("adjective", "ridiculous", None),
    "belang": ("noun", "interest, importance", "het"),
    "belangrijk": ("adjective", "important", None),
    "belangstelling": ("noun", "interest", "de"),
    "belasting": ("noun", "tax", "de"),
    "beleid": ("noun", "policy", "het"),
    "beleven": ("verb", "to experience", None),
    "bellen": ("verb", "to call, to ring", None),
    "belofte": ("noun", "promise", "de"),
    "beloven": ("verb", "to promise", None),
    "bemanning": ("noun", "crew", "de"),
    "bemoeien": ("verb", "to interfere", None),
    "benaderen": ("verb", "to approach", None),
    "beoordelen": ("verb", "to judge, to assess", None),
    "bepaald": ("adjective", "certain, specific", None),
    "bepalen": ("verb", "to determine", None),
    "bepaling": ("noun", "regulation; determination", "de"),
    "beperken": ("verb", "to limit, to restrict", None),
    "beperking": ("noun", "limitation, restriction", "de"),
    "beperkt": ("adjective", "limited", None),
    "bereid": ("adjective", "willing, prepared", None),
    "bereiden": ("verb", "to prepare", None),
    "bereiken": ("verb", "to reach, to achieve", None),
    "berg": ("noun", "mountain", "de"),
    "bericht": ("noun", "message, report", "het"),
    "beroemd": ("adjective", "famous", None),
    "beroemen": ("verb", "to boast", None),
    "beroep": ("noun", "profession; appeal", "het"),
    "berusten": ("verb", "to rest on; to accept", None),
    "beschaving": ("noun", "civilization", "de"),
    "bescheiden": ("adjective", "modest", None),
    "beschermen": ("verb", "to protect", None),
    "bescherming": ("noun", "protection", "de"),
    "beschikbaar": ("adjective", "available", None),
    "beschikken": ("verb", "to have at disposal", None),
    "beschikking": ("noun", "disposal; decree", "de"),
    "beschouwen": ("verb", "to consider, to regard", None),
    "beschouwing": ("noun", "consideration, reflection", "de"),
    "beschrijven": ("verb", "to describe", None),
    "beschrijving": ("noun", "description", "de"),
    "besef": ("noun", "realization, awareness", "het"),
    "beseffen": ("verb", "to realize", None),
    "beslag": ("noun", "seizure; batter", "het"),
    "beslissen": ("verb", "to decide", None),
    "beslissing": ("noun", "decision", "de"),
    "beslist": ("adjective", "definite, resolute", None),
    "besloten": ("adjective", "closed; private", None),
    "besluit": ("noun", "decision, resolution", "het"),
    "besluiten": ("verb", "to decide", None),
    "bespreken": ("verb", "to discuss", None),
    "bespreking": ("noun", "discussion, review", "de"),
    "best": ("adjective", "best", None),
    "bestaan": ("verb", "to exist", None),
    "besteden": ("verb", "to spend (time/money)", None),
    "bestellen": ("verb", "to order", None),
    "bestemmen": ("verb", "to destine", None),
    "bestrijden": ("verb", "to fight, to combat", None),
    "bestuderen": ("verb", "to study", None),
    "bestuur": ("noun", "management, board", "het"),
    "bestuursdwang": ("noun", "administrative enforcement", "de"),
    "betalen": ("verb", "to pay", None),
    "betekenen": ("verb", "to mean, to signify", None),
    "betekenis": ("noun", "meaning, significance", "de"),
    "beter": ("adjective", "better", None),
    "betreffen": ("verb", "to concern", None),
    "betreffende": ("adjective", "concerning, regarding", None),
    "betrekkelijk": ("adjective", "relative, relatively", None),
    "betrekken": ("verb", "to involve; to move into", None),
    "betrekking": ("noun", "position; relation", "de"),
    "betrokken": ("adjective", "involved, concerned", None),
    "betrokkene": ("noun", "person involved", "de"),
    "betrouwbaar": ("adjective", "reliable", None),
    "beurt": ("noun", "turn", "de"),
    "bevallen": ("verb", "to give birth; to please", None),
    "bevatten": ("verb", "to contain", None),
    "bevel": ("noun", "command, order", "het"),
    "bevelen": ("verb", "to command", None),
    "bevestigen": ("verb", "to confirm; to attach", None),
    "beven": ("verb", "to tremble", None),
    "bevinden": ("verb", "to be (located); to find", None),
    "bevolking": ("noun", "population", "de"),
    "bevorderen": ("verb", "to promote", None),
    "bevredigen": ("verb", "to satisfy", None),
    "bevrijden": ("verb", "to liberate", None),
    "bevrijding": ("noun", "liberation", "de"),
    "bewaren": ("verb", "to keep, to preserve", None),
    "bewegen": ("verb", "to move", None),
    "beweging": ("noun", "movement", "de"),
    "beweren": ("verb", "to claim, to assert", None),
    "bewijs": ("noun", "proof, evidence", "het"),
    "bewijzen": ("verb", "to prove", None),
    "bewonderen": ("verb", "to admire", None),
    "bewondering": ("noun", "admiration", "de"),
    "bewoner": ("noun", "resident, inhabitant", "de"),
    "bewust": ("adjective", "conscious, aware", None),
    "bewustzijn": ("noun", "consciousness", "het"),
    "bezig": ("adjective", "busy", None),
    "bezien": ("verb", "to look at, to consider", None),
    "bezighouden": ("verb", "to keep busy; to occupy", None),
    "bezit": ("noun", "possession, property", "het"),
    "bezitten": ("verb", "to own, to possess", None),
    "bezoek": ("noun", "visit", "het"),
    "bezoeken": ("verb", "to visit", None),
    "bezoeker": ("noun", "visitor", "de"),
    "bezorgen": ("verb", "to deliver; to cause", None),
    "bezorgd": ("adjective", "worried, concerned", None),
    "bezwaar": ("noun", "objection", "het"),
    "bibliotheek": ("noun", "library", "de"),
    "bidden": ("verb", "to pray", None),
    "bieden": ("verb", "to offer", None),
    "bier": ("noun", "beer", "het"),
    "bijbel": ("noun", "bible", "de"),
    "bijdrage": ("noun", "contribution", "de"),
    "bijdragen": ("verb", "to contribute", None),
    "bijeenkomst": ("noun", "meeting, gathering", "de"),
    "bijten": ("verb", "to bite", None),
    "bijzonder": ("adjective", "special, remarkable", None),
    "binden": ("verb", "to bind, to tie", None),
    "biologisch": ("adjective", "biological, organic", None),
    "bisschop": ("noun", "bishop", "de"),
    "bitter": ("adjective", "bitter", None),
    "blad": ("noun", "leaf; sheet; magazine", "het"),
    "bladzijde": ("noun", "page", "de"),
    "blank": ("adjective", "white, pale", None),
    "blauw": ("adjective", "blue", None),
    "blazen": ("verb", "to blow", None),
    "bleek": ("adjective", "pale", None),
    "blij": ("adjective", "happy, glad", None),
    "blijkbaar": ("adjective", "apparently", None),
    "blijken": ("verb", "to turn out, to appear", None),
    "blijven": ("verb", "to stay, to remain", None),
    "blik": ("noun", "glance; tin can", "de"),
    "blind": ("adjective", "blind", None),
    "bloed": ("noun", "blood", "het"),
    "bloeien": ("verb", "to bloom, to flourish", None),
    "bloem": ("noun", "flower", "de"),
    "blok": ("noun", "block", "het"),
    "blond": ("adjective", "blond", None),
    "bloot": ("adjective", "bare, naked", None),
    "bocht": ("noun", "curve, bend", "de"),
    "bodem": ("noun", "bottom; soil", "de"),
    "boek": ("noun", "book", "het"),
    "boeien": ("verb", "to fascinate; to handcuff", None),
    "boel": ("noun", "a lot; mess", "de"),
    "boer": ("noun", "farmer", "de"),
    "boerderij": ("noun", "farm", "de"),
    "boog": ("noun", "arch; bow", "de"),
    "boom": ("noun", "tree", "de"),
    "boodschap": ("noun", "message; errand", "de"),
    "boord": ("noun", "board; collar", "het"),
    "boos": ("adjective", "angry", None),
    "boot": ("noun", "boat", "de"),
    "bord": ("noun", "plate; sign", "het"),
    "borst": ("noun", "chest, breast", "de"),
    "bos": ("noun", "forest; bunch", "het"),
    "boter": ("noun", "butter", "de"),
    "bouwen": ("verb", "to build", None),
    "braaf": ("adjective", "well-behaved, good", None),
    "brand": ("noun", "fire", "de"),
    "branden": ("verb", "to burn", None),
    "breed": ("adjective", "wide, broad", None),
    "breken": ("verb", "to break", None),
    "brengen": ("verb", "to bring", None),
    "brief": ("noun", "letter", "de"),
    "bril": ("noun", "glasses", "de"),
    "broeder": ("noun", "brother (formal)", "de"),
    "broek": ("noun", "pants", "de"),
    "broer": ("noun", "brother", "de"),
    "bron": ("noun", "source", "de"),
    "brood": ("noun", "bread", "het"),
    "brug": ("noun", "bridge", "de"),
    "bruin": ("adjective", "brown", None),
    "brullen": ("verb", "to roar", None),
    "buigen": ("verb", "to bend, to bow", None),
    "buik": ("noun", "belly, stomach", "de"),
    "bundel": ("noun", "bundle; volume", "de"),
    "bureau": ("noun", "desk; office", "het"),
    "burger": ("noun", "citizen", "de"),
    "burgemeester": ("noun", "mayor", "de"),
    "burgerlijk": ("adjective", "civil; bourgeois", None),
    "bus": ("noun", "bus", "de"),
    "buur": ("noun", "neighbor", "de"),
    "buurt": ("noun", "neighborhood", "de"),
    # C
    "categorie": ("noun", "category", "de"),
    "cel": ("noun", "cell", "de"),
    "cent": ("noun", "cent", "de"),
    "centimeter": ("noun", "centimeter", "de"),
    "centraal": ("adjective", "central", None),
    "centrum": ("noun", "center", "het"),
    "champagne": ("noun", "champagne", "de"),
    "chauffeur": ("noun", "driver", "de"),
    "chef": ("noun", "chef; boss", "de"),
    "chemisch": ("adjective", "chemical", None),
    "christen": ("noun", "Christian", "de"),
    "christelijk": ("adjective", "Christian", None),
    "christendom": ("noun", "Christianity", "het"),
    "cijfer": ("noun", "number; grade", "het"),
    "cirkel": ("noun", "circle", "de"),
    "citeren": ("verb", "to quote", None),
    "collectief": ("adjective", "collective", None),
    "college": ("noun", "lecture; board", "het"),
    "combinatie": ("noun", "combination", "de"),
    "commandant": ("noun", "commander", "de"),
    "commentaar": ("noun", "commentary", "het"),
    "commissaris": ("noun", "commissioner", "de"),
    "commissie": ("noun", "committee", "de"),
    "communicatie": ("noun", "communication", "de"),
    "communistisch": ("adjective", "communist", None),
    "compleet": ("adjective", "complete", None),
    "computer": ("noun", "computer", "de"),
    "concentreren": ("verb", "to concentrate", None),
    "conclusie": ("noun", "conclusion", "de"),
    "concluderen": ("verb", "to conclude", None),
    "concreet": ("adjective", "concrete, specific", None),
    "conflict": ("noun", "conflict", "het"),
    "confronteren": ("verb", "to confront", None),
    "consequentie": ("noun", "consequence", "de"),
    "constateren": ("verb", "to establish, to observe", None),
    "consument": ("noun", "consumer", "de"),
    "contact": ("noun", "contact", "het"),
    "controle": ("noun", "control; check", "de"),
    "controleren": ("verb", "to check, to control", None),
    "crisis": ("noun", "crisis", "de"),
    "criterium": ("noun", "criterion", "het"),
    "criticus": ("noun", "critic", "de"),
    "cultureel": ("adjective", "cultural", None),
    "cultuur": ("noun", "culture", "de"),
    # D
    "daad": ("noun", "deed, act", "de"),
    "dag": ("noun", "day", "de"),
    "dagboek": ("noun", "diary", "het"),
    "dagelijks": ("adjective", "daily", None),
    "dak": ("noun", "roof", "het"),
    "dal": ("noun", "valley", "het"),
    "dalen": ("verb", "to descend; to decrease", None),
    "dame": ("noun", "lady", "de"),
    "dank": ("noun", "thanks", "de"),
    "dankbaar": ("adjective", "grateful", None),
    "danken": ("verb", "to thank", None),
    "dansen": ("verb", "to dance", None),
    "deel": ("noun", "part", "het"),
    "deelnemen": ("verb", "to participate", None),
    "deelnemer": ("noun", "participant", "de"),
    "definitie": ("noun", "definition", "de"),
    "definitief": ("adjective", "definitive, final", None),
    "degelijk": ("adjective", "solid, thorough", None),
    "deken": ("noun", "blanket; dean", "de"),
    "dekken": ("verb", "to cover; to set (table)", None),
    "delen": ("verb", "to share; to divide", None),
    "democratie": ("noun", "democracy", "de"),
    "democratisch": ("adjective", "democratic", None),
    "denkbaar": ("adjective", "conceivable", None),
    "denkbeeld": ("noun", "idea, notion", "het"),
    "denken": ("verb", "to think", None),
    "derde": ("adjective", "third", None),
    "dergelijk": ("adjective", "such, similar", None),
    "deskundige": ("noun", "expert", "de"),
    "detail": ("noun", "detail", "het"),
    "deur": ("noun", "door", "de"),
    "diagnose": ("noun", "diagnosis", "de"),
    "dicht": ("adjective", "closed; dense; near", None),
    "dichtbij": ("adjective", "nearby", None),
    "dichter": ("noun", "poet", "de"),
    "dienen": ("verb", "to serve", None),
    "dienst": ("noun", "service", "de"),
    "diep": ("adjective", "deep", None),
    "diepte": ("noun", "depth", "de"),
    "dier": ("noun", "animal", "het"),
    "dik": ("adjective", "thick, fat", None),
    "dimensie": ("noun", "dimension", "de"),
    "ding": ("noun", "thing", "het"),
    "direct": ("adjective", "direct", None),
    "directeur": ("noun", "director", "de"),
    "directie": ("noun", "management, direction", "de"),
    "discussie": ("noun", "discussion", "de"),
    "divers": ("adjective", "various", None),
    "dochter": ("noun", "daughter", "de"),
    "document": ("noun", "document", "het"),
    "dodelijk": ("adjective", "deadly", None),
    "dode": ("noun", "dead person", "de"),
    "doden": ("verb", "to kill", None),
    "doel": ("noun", "goal, purpose", "het"),
    "doeleinde": ("noun", "purpose, objective", "het"),
    "doelstelling": ("noun", "objective", "de"),
    "doen": ("verb", "to do", None),
    "doek": ("noun", "cloth; canvas", "het"),
    "dokter": ("noun", "doctor", "de"),
    "dol": ("adjective", "crazy; fond of", None),
    "dollar": ("noun", "dollar", "de"),
    "dom": ("adjective", "stupid", None),
    "donker": ("adjective", "dark", None),
    "dood": ("noun", "death", "de"),
    "doorbreken": ("verb", "to break through", None),
    "doorbrengen": ("verb", "to spend (time)", None),
    "doordringen": ("verb", "to penetrate; to realize", None),
    "doorgaan": ("verb", "to continue", None),
    "doorlopen": ("verb", "to walk through; to continue", None),
    "doos": ("noun", "box", "de"),
    "dorp": ("noun", "village", "het"),
    "draad": ("noun", "thread; wire", "de"),
    "draaien": ("verb", "to turn, to rotate", None),
    "dragen": ("verb", "to carry; to wear", None),
    "drank": ("noun", "drink; alcohol", "de"),
    "dreigen": ("verb", "to threaten", None),
    "dringen": ("verb", "to push; to urge", None),
    "drinken": ("verb", "to drink", None),
    "drogen": ("verb", "to dry", None),
    "drom": ("noun", "crowd", "de"),
    "dromen": ("verb", "to dream", None),
    "dronken": ("adjective", "drunk", None),
    "droog": ("adjective", "dry", None),
    "droom": ("noun", "dream", "de"),
    "druif": ("noun", "grape", "de"),
    "druk": ("adjective", "busy; pressure", None),
    "drukken": ("verb", "to press; to print", None),
    "druppel": ("noun", "drop", "de"),
    "duiden": ("verb", "to indicate; to interpret", None),
    "duidelijk": ("adjective", "clear, obvious", None),
    "duim": ("noun", "thumb", "de"),
    "duister": ("adjective", "dark, obscure", None),
    "duisternis": ("noun", "darkness", "de"),
    "duizend": ("adjective", "thousand", None),
    "duren": ("verb", "to last, to take (time)", None),
    "durven": ("verb", "to dare", None),
    "duur": ("adjective", "expensive", None),
    "duurzaam": ("adjective", "sustainable, durable", None),
    "dwingen": ("verb", "to force, to compel", None),
}
