WORDS = {
    "laars": ("noun", "boot", "de"),
    "laboratorium": ("noun", "laboratory", "het"),
    "ladder": ("noun", "ladder", "de"),
    "lading": ("noun", "cargo; charge", "de"),
    "laken": ("noun", "sheet; cloth", "het"),
    "lamp": ("noun", "lamp", "de"),
    "lanceren": ("verb", "to launch", None),
    "landbouw": ("noun", "agriculture", "de"),
    "landschap": ("noun", "landscape", "het"),
    "langdurig": ("adjective", "prolonged, lengthy", None),
    "lastig": ("adjective", "difficult; annoying", None),
    "later": ("adjective", "later", None),
    "lauw": ("adjective", "lukewarm", None),
    "lawaai": ("noun", "noise", "het"),
    "leeg": ("adjective", "empty", None),
    "leegte": ("noun", "emptiness, void", "de"),
    "leek": ("noun", "layman", "de"),
    "legende": ("noun", "legend", "de"),
    "lekker": ("adjective", "tasty; nice", None),
    "lenen": ("verb", "to lend; to borrow", None),
    "lente": ("noun", "spring (season)", "de"),
    "lepel": ("noun", "spoon", "de"),
    "leraar": ("noun", "teacher", "de"),
    "letten": ("verb", "to pay attention", None),
    "leugen": ("noun", "lie", "de"),
    "levendig": ("adjective", "lively", None),
    "lever": ("noun", "liver", "de"),
    "leverancier": ("noun", "supplier", "de"),
    "lezing": ("noun", "lecture; reading", "de"),
    "lichten": ("verb", "to light; to lift", None),
    "lied": ("noun", "song", "het"),
    "lieden": ("noun", "people", "de"),
    "liefhebben": ("verb", "to love", None),
    "liefje": ("noun", "sweetheart", "het"),
    "liegen": ("verb", "to lie (untruth)", None),
    "lift": ("noun", "elevator", "de"),
    "likken": ("verb", "to lick", None),
    "liter": ("noun", "liter", "de"),
    "literair": ("adjective", "literary", None),
    "litteken": ("noun", "scar", "het"),
    "logeren": ("verb", "to stay (as guest)", None),
    "logica": ("noun", "logic", "de"),
    "lokken": ("verb", "to lure, to attract", None),
    "long": ("noun", "lung", "de"),
    "lopend": ("adjective", "running; current", None),
    "lossen": ("verb", "to unload; to solve", None),
    "louter": ("adjective", "pure; merely", None),
    "luchtig": ("adjective", "light; airy", None),
    "luid": ("adjective", "loud", None),
    "luidruchtig": ("adjective", "noisy", None),
    "luik": ("noun", "shutter; hatch", "het"),
    "luitenant": ("noun", "lieutenant", "de"),
    "luxe": ("noun", "luxury", "de"),
    "maag": ("noun", "stomach", "de"),
    "maaltijd": ("noun", "meal", "de"),
    "maan": ("noun", "moon", "de"),
    "maat": ("noun", "measure; size; mate", "de"),
    "maatschappelijk": ("adjective", "social, societal", None),
    "maatschappij": ("noun", "society; company", "de"),
    "maatstaf": ("noun", "standard, criterion", "de"),
    "machine": ("noun", "machine", "de"),
    "machteloos": ("adjective", "powerless", None),
    "magisch": ("adjective", "magical", None),
    "majesteit": ("noun", "majesty", "de"),
    "makkelijk": ("adjective", "easy", None),
    "malen": ("verb", "to grind", None),
    "mand": ("noun", "basket", "de"),
    "mannelijk": ("adjective", "male; masculine", None),
    "mannetje": ("noun", "little man; male animal", "het"),
    "mantel": ("noun", "coat; cloak", "de"),
    "manuscript": ("noun", "manuscript", "het"),
    "marcheren": ("verb", "to march", None),
    "markt": ("noun", "market", "de"),
    "masker": ("noun", "mask", "het"),
    "massaal": ("adjective", "massive, mass", None),
    "massief": ("adjective", "massive, solid", None),
    "mate": ("noun", "degree, extent", "de"),
    "materie": ("noun", "matter", "de"),
    "materieel": ("adjective", "material", None),
    "matras": ("noun", "mattress", "de"),
    "maximaal": ("adjective", "maximum", None),
    "mechanisch": ("adjective", "mechanical", None),
    "medelijden": ("noun", "pity, compassion", "het"),
    "medemens": ("noun", "fellow human", "de"),
    "media": ("noun", "media", "de"),
    "medisch": ("adjective", "medical", None),
    "meebrengen": ("verb", "to bring along", None),
    "meedelen": ("verb", "to inform, to communicate", None),
    "meedogenloos": ("adjective", "merciless", None),
    "meegaan": ("verb", "to go along", None),
    "meemaken": ("verb", "to experience", None),
    "meer": ("noun", "lake", "het"),
    "meerdere": ("adjective", "several; superior", None),
    "meestal": ("adjective", "mostly, usually", None),
    "meid": ("noun", "girl; maid", "de"),
    "melding": ("noun", "report, notification", "de"),
    "melodie": ("noun", "melody", "de"),
    "meneer": ("noun", "sir, mister", "de"),
    "menen": ("verb", "to mean; to believe", None),
    "mengsel": ("noun", "mixture", "het"),
    "menigte": ("noun", "crowd", "de"),
    "mensheid": ("noun", "humanity, mankind", "de"),
    "mentaal": ("adjective", "mental", None),
    "mentaliteit": ("noun", "mentality", "de"),
    "merendeel": ("noun", "majority", "het"),
    "merk": ("noun", "brand", "het"),
    "merkwaardig": ("adjective", "remarkable, strange", None),
    "metaal": ("noun", "metal", "het"),
    "meteen": ("adjective", "immediately", None),
    "meter": ("noun", "meter", "de"),
    "meubel": ("noun", "piece of furniture", "het"),
    "mevrouw": ("noun", "madam, Mrs.", "de"),
    "middelbaar": ("adjective", "secondary; average", None),
    "middeleeuwen": ("noun", "Middle Ages", "de"),
    "middelpunt": ("noun", "center point", "het"),
    "middernacht": ("noun", "midnight", "de"),
    "mild": ("adjective", "mild; generous", None),
    "minder": ("adjective", "less; fewer", None),
    "minderheid": ("noun", "minority", "de"),
    "minimaal": ("adjective", "minimal", None),
    "minimum": ("noun", "minimum", "het"),
    "minnaar": ("noun", "lover", "de"),
    "minstens": ("adjective", "at least", None),
    "minuut": ("noun", "minute", "de"),
    "misbruik": ("noun", "abuse, misuse", "het"),
    "misdaad": ("noun", "crime", "de"),
    "misdadiger": ("noun", "criminal", "de"),
    "misleiden": ("verb", "to mislead, to deceive", None),
    "mislukken": ("verb", "to fail", None),
    "mislukking": ("noun", "failure", "de"),
    "missen": ("verb", "to miss", None),
    "missie": ("noun", "mission", "de"),
    "mist": ("noun", "fog", "de"),
    "misverstand": ("noun", "misunderstanding", "het"),
    "modder": ("noun", "mud", "de"),
    "mode": ("noun", "fashion", "de"),
    "model": ("noun", "model", "het"),
    "moe": ("adjective", "tired", None),
    "moed": ("noun", "courage", "de"),
    "moedig": ("adjective", "courageous, brave", None),
    "moeizaam": ("adjective", "laborious, difficult", None),
    "moeras": ("noun", "swamp, marsh", "het"),
    "momenteel": ("adjective", "currently", None),
    "mompelen": ("verb", "to mumble", None),
    "monnik": ("noun", "monk", "de"),
    "monster": ("noun", "monster; sample", "het"),
    "monument": ("noun", "monument", "het"),
    "moordenaar": ("noun", "murderer", "de"),
    "mopperen": ("verb", "to grumble", None),
    "motief": ("noun", "motive", "het"),
    "motivatie": ("noun", "motivation", "de"),
    "muis": ("noun", "mouse", "de"),
    "museum": ("noun", "museum", "het"),
    "muzikaal": ("adjective", "musical", None),
    "mysterie": ("noun", "mystery", "het"),
    "mysterieus": ("adjective", "mysterious", None),
    "mythe": ("noun", "myth", "de"),
    "naakt": ("adjective", "naked", None),
    "naald": ("noun", "needle", "de"),
    "naast": ("adjective", "next to; nearest", None),
    "nabij": ("adjective", "near, close", None),
    "nabijheid": ("noun", "proximity", "de"),
    "nachtelijk": ("adjective", "nightly, nocturnal", None),
    "nachtmerrie": ("noun", "nightmare", "de"),
    "nadeel": ("noun", "disadvantage", "het"),
    "nadenken": ("verb", "to think about, to reflect", None),
    "naderen": ("verb", "to approach", None),
    "nadrukkelijk": ("adjective", "emphatic", None),
    "nagel": ("noun", "nail", "de"),
    "nastreven": ("verb", "to pursue, to strive for", None),
    "nat": ("adjective", "wet", None),
    "natie": ("noun", "nation", "de"),
    "nationaal": ("adjective", "national", None),
    "naïef": ("adjective", "naive", None),
    "nederlaag": ("noun", "defeat", "de"),
    "neef": ("noun", "cousin; nephew", "de"),
    "neerkomen": ("verb", "to come down; to amount to", None),
    "neerzetten": ("verb", "to put down", None),
    "negeren": ("verb", "to ignore", None),
    "neigen": ("verb", "to tend; to lean", None),
    "nek": ("noun", "neck (back)", "de"),
    "nerveus": ("adjective", "nervous", None),
    "nest": ("noun", "nest", "het"),
    "netjes": ("adjective", "neat, tidy", None),
    "netwerk": ("noun", "network", "het"),
    "nevel": ("noun", "mist, haze", "de"),
    "nicht": ("noun", "cousin (female); niece", "de"),
    "niemand": ("adjective", "nobody", None),
    "nier": ("noun", "kidney", "de"),
    "nieuwsgierig": ("adjective", "curious", None),
    "noodlot": ("noun", "fate, destiny", "het"),
    "noordelijk": ("adjective", "northern", None),
    "noorden": ("noun", "north", "het"),
    "noot": ("noun", "note (music); nut", "de"),
    "nors": ("adjective", "grumpy, surly", None),
    "notaris": ("noun", "notary", "de"),
    "noteren": ("verb", "to note down", None),
    "nuchter": ("adjective", "sober; sensible", None),
    "nutteloos": ("adjective", "useless", None),
    "object": ("noun", "object", "het"),
    "objectief": ("adjective", "objective", None),
    "observatie": ("noun", "observation", "de"),
    "observeren": ("verb", "to observe", None),
    "oceaan": ("noun", "ocean", "de"),
    "offeren": ("verb", "to sacrifice", None),
    "ogenblik": ("noun", "moment", "het"),
    "olie": ("noun", "oil", "de"),
    "oma": ("noun", "grandmother", "de"),
    "omdraaien": ("verb", "to turn around", None),
    "omgaan": ("verb", "to deal with; to go around", None),
    "omgekeerd": ("adjective", "reversed; vice versa", None),
    "omgeven": ("verb", "to surround", None),
    "omhelzen": ("verb", "to embrace", None),
    "omkeren": ("verb", "to turn around; to reverse", None),
    "omringen": ("verb", "to surround", None),
    "omroep": ("noun", "broadcasting", "de"),
    "omschrijven": ("verb", "to describe; to paraphrase", None),
    "omschrijving": ("noun", "description", "de"),
    "omvangrijk": ("adjective", "extensive, large", None),
    "omweg": ("noun", "detour", "de"),
    "onbeweeglijk": ("adjective", "motionless", None),
    "onderbreken": ("verb", "to interrupt", None),
    "onderdak": ("noun", "shelter", "het"),
    "onderdrukken": ("verb", "to suppress; to oppress", None),
    "ondergaan": ("verb", "to undergo; to set (sun)", None),
    "ondergeschikt": ("adjective", "subordinate", None),
    "ondergronds": ("adjective", "underground", None),
    "onderhandelen": ("verb", "to negotiate", None),
    "onderhandeling": ("noun", "negotiation", "de"),
    "onderhoud": ("noun", "maintenance", "het"),
    "onderkennen": ("verb", "to recognize, to identify", None),
    "onderling": ("adjective", "mutual", None),
    "onderschatten": ("verb", "to underestimate", None),
    "onderscheiding": ("noun", "distinction; decoration", "de"),
    "ondertekenen": ("verb", "to sign", None),
    "ondervinden": ("verb", "to experience", None),
    "ondervragen": ("verb", "to interrogate", None),
    "onderwerpen": ("verb", "to subject", None),
    "oneindig": ("adjective", "infinite", None),
    "ongelijk": ("noun", "wrong; inequality", "het"),
    "ongelukkig": ("adjective", "unhappy; unfortunate", None),
    "ongewenst": ("adjective", "unwanted", None),
    "onmacht": ("noun", "powerlessness", "de"),
    "onmisbaar": ("adjective", "indispensable", None),
    "onnodig": ("adjective", "unnecessary", None),
    "onnozel": ("adjective", "silly, naive", None),
    "onrustig": ("adjective", "restless", None),
    "ontbijt": ("noun", "breakfast", "het"),
    "onthouden": ("verb", "to remember; to withhold", None),
    "onthullen": ("verb", "to reveal", None),
    "ontkomen": ("verb", "to escape", None),
    "ontlenen": ("verb", "to derive; to borrow", None),
    "ontplooien": ("verb", "to develop; to unfold", None),
    "ontroeren": ("verb", "to move (emotionally)", None),
    "ontspannen": ("verb", "to relax", None),
    "ontspanning": ("noun", "relaxation", "de"),
    "onttrekken": ("verb", "to withdraw; to extract", None),
    "ontwaken": ("verb", "to wake up", None),
    "ontwijken": ("verb", "to evade, to dodge", None),
    "ontwikkeld": ("adjective", "developed; educated", None),
    "ontzettend": ("adjective", "tremendous; terrible", None),
    "onvermijdelijk": ("adjective", "inevitable", None),
    "onverschillig": ("adjective", "indifferent", None),
    "onverwacht": ("adjective", "unexpected", None),
    "onzichtbaar": ("adjective", "invisible", None),
    "onzin": ("noun", "nonsense", "de"),
    "oogst": ("noun", "harvest", "de"),
    "oorsprong": ("noun", "origin", "de"),
    "oorspronkelijk": ("adjective", "original", None),
    "oostelijk": ("adjective", "eastern", None),
    "oosten": ("noun", "east", "het"),
    "opa": ("noun", "grandfather", "de"),
    "opbouw": ("noun", "construction, structure", "de"),
    "opbrengen": ("verb", "to yield; to summon", None),
    "opbrengst": ("noun", "yield, revenue", "de"),
    "opdoen": ("verb", "to gain (experience)", None),
    "opdragen": ("verb", "to dedicate; to assign", None),
    "opduiken": ("verb", "to surface; to turn up", None),
    "openbaren": ("verb", "to reveal", None),
    "openlijk": ("adjective", "openly, publicly", None),
    "openstaan": ("verb", "to be open", None),
    "opereren": ("verb", "to operate", None),
    "opgaan": ("verb", "to rise; to be absorbed", None),
    "opgave": ("noun", "task; statement", "de"),
    "opgeven": ("verb", "to give up; to state", None),
    "opgewekt": ("adjective", "cheerful", None),
    "opgewonden": ("adjective", "excited", None),
    "opgroeien": ("verb", "to grow up", None),
    "ophalen": ("verb", "to pick up; to collect", None),
    "opinie": ("noun", "opinion", "de"),
    "opkomst": ("noun", "rise; turnout", "de"),
    "opleveren": ("verb", "to deliver; to yield", None),
    "oplopen": ("verb", "to increase; to catch (illness)", None),
    "opluchting": ("noun", "relief", "de"),
    "opmaken": ("verb", "to use up; to make up", None),
    "opname": ("noun", "recording; admission", "de"),
    "oppassen": ("verb", "to watch out; to babysit", None),
    "oppervlakkig": ("adjective", "superficial", None),
    "oppervlakte": ("noun", "surface, area", "de"),
    "oppositie": ("noun", "opposition", "de"),
    "oprecht": ("adjective", "sincere", None),
    "opschieten": ("verb", "to hurry up", None),
    "opschrijven": ("verb", "to write down", None),
    "opslaan": ("verb", "to store; to save", None),
    "opsluiten": ("verb", "to lock up", None),
    "opstaan": ("verb", "to stand up; to get up", None),
    "opstelling": ("noun", "lineup; attitude", "de"),
    "optimaal": ("adjective", "optimal", None),
    "opvangen": ("verb", "to catch; to absorb", None),
    "opvoeren": ("verb", "to increase; to perform", None),
    "opvolgen": ("verb", "to succeed; to follow up", None),
    "opvolger": ("noun", "successor", "de"),
    "opwekken": ("verb", "to arouse; to generate", None),
    "opwinding": ("noun", "excitement", "de"),
    "opzet": ("noun", "intention; design", "het"),
    "opzettelijk": ("adjective", "intentional, deliberate", None),
    "opzoeken": ("verb", "to look up; to visit", None),
    "ordening": ("noun", "arrangement, ordering", "de"),
    "order": ("noun", "order", "de"),
    "organisch": ("adjective", "organic", None),
    "organisme": ("noun", "organism", "het"),
    "origineel": ("adjective", "original", None),
    "orkest": ("noun", "orchestra", "het"),
    "ouderdom": ("noun", "old age", "de"),
    "ouderen": ("noun", "elderly people", "de"),
    "ouderlijk": ("adjective", "parental", None),
    "ouderwets": ("adjective", "old-fashioned", None),
    "oudheid": ("noun", "antiquity", "de"),
    "oven": ("noun", "oven", "de"),
    "overblijven": ("verb", "to remain, to be left", None),
    "overbodig": ("adjective", "superfluous", None),
    "overbrengen": ("verb", "to convey; to transfer", None),
    "overdracht": ("noun", "transfer", "de"),
    "overdragen": ("verb", "to transfer; to hand over", None),
    "overdreven": ("adjective", "exaggerated", None),
    "overdrijven": ("verb", "to exaggerate", None),
    "overeenkomen": ("verb", "to agree; to correspond", None),
    "overeenkomst": ("noun", "agreement; similarity", "de"),
    "overeenstemming": ("noun", "agreement, consensus", "de"),
    "overgaan": ("verb", "to go over; to pass", None),
    "overgang": ("noun", "transition", "de"),
    "overgeven": ("verb", "to surrender; to vomit", None),
    "overhandigen": ("verb", "to hand over", None),
    "overheersen": ("verb", "to dominate", None),
    "overhemd": ("noun", "shirt", "het"),
    "overkant": ("noun", "other side", "de"),
    "overkomen": ("verb", "to happen to; to come over", None),
    "overlaten": ("verb", "to leave to", None),
    "overleveren": ("verb", "to hand down", None),
    "overlijden": ("verb", "to pass away, to die", None),
    "overtreding": ("noun", "violation, offense", "de"),
    "overtreffen": ("verb", "to surpass", None),
    "overtuigd": ("adjective", "convinced", None),
    "overvallen": ("verb", "to rob; to overwhelm", None),
    "overvloed": ("noun", "abundance", "de"),
    "overvloedig": ("adjective", "abundant", None),
    "overwegend": ("adjective", "predominantly", None),
    "overzien": ("verb", "to overlook; to survey", None),
    "paal": ("noun", "pole, post", "de"),
    "paars": ("adjective", "purple", None),
    "pakje": ("noun", "package; little suit", "het"),
    "palm": ("noun", "palm", "de"),
    "pand": ("noun", "building, premises", "het"),
    "paradijs": ("noun", "paradise", "het"),
    "paragraaf": ("noun", "paragraph", "de"),
    "parfum": ("noun", "perfume", "het"),
    "park": ("noun", "park", "het"),
    "parkeren": ("verb", "to park", None),
    "parlementair": ("adjective", "parliamentary", None),
    "particulier": ("adjective", "private; individual", None),
    "paspoort": ("noun", "passport", "het"),
    "passagier": ("noun", "passenger", "de"),
    "passief": ("adjective", "passive", None),
    "pastoor": ("noun", "parish priest", "de"),
    "patiënt": ("noun", "patient", "de"),
    "pauze": ("noun", "break, pause", "de"),
    "peil": ("noun", "level", "het"),
    "peinzen": ("verb", "to ponder", None),
    "pensioen": ("noun", "pension", "het"),
    "percentage": ("noun", "percentage", "het"),
    "perfect": ("adjective", "perfect", None),
    "perron": ("noun", "platform (train)", "het"),
    "pers": ("noun", "press", "de"),
    "personage": ("noun", "character (in story)", "het"),
    "personeel": ("noun", "staff, personnel", "het"),
    "perspectief": ("noun", "perspective", "het"),
    "pet": ("noun", "cap", "de"),
    "piano": ("noun", "piano", "de"),
    "piekeren": ("verb", "to worry, to brood", None),
    "pijl": ("noun", "arrow", "de"),
    "pijnlijk": ("adjective", "painful", None),
    "pil": ("noun", "pill", "de"),
    "piloot": ("noun", "pilot", "de"),
    "pistool": ("noun", "pistol", "het"),
    "plafond": ("noun", "ceiling", "het"),
    "plagen": ("verb", "to tease", None),
    "plakken": ("verb", "to stick, to paste", None),
    "planeet": ("noun", "planet", "de"),
    "planning": ("noun", "planning", "de"),
    "plechtig": ("adjective", "solemn", None),
    "pleiten": ("verb", "to plead", None),
    "plezierig": ("adjective", "pleasant, enjoyable", None),
    "plukken": ("verb", "to pick, to pluck", None),
    "podium": ("noun", "stage, podium", "het"),
    "poetsen": ("verb", "to clean, to polish", None),
    "poging": ("noun", "attempt", "de"),
    "politieman": ("noun", "policeman", "de"),
    "pols": ("noun", "wrist; pulse", "de"),
    "poot": ("noun", "paw; leg (furniture)", "de"),
    "portret": ("noun", "portrait", "het"),
    "potentieel": ("adjective", "potential", None),
    "potlood": ("noun", "pencil", "het"),
    "poëzie": ("noun", "poetry", "de"),
    "praatje": ("noun", "chat; rumor", "het"),
    "predikant": ("noun", "preacher, minister", "de"),
    "premier": ("noun", "prime minister", "de"),
    "presenteren": ("verb", "to present", None),
    "prijs": ("noun", "price; prize", "de"),
    "prijzen": ("verb", "to praise; to price", None),
    "prikkel": ("noun", "stimulus", "de"),
    "prikkelen": ("verb", "to stimulate", None),
    "prima": ("adjective", "excellent, fine", None),
    "primair": ("adjective", "primary", None),
    "primitief": ("adjective", "primitive", None),
    "principieel": ("adjective", "on principle", None),
    "proberen": ("verb", "to try", None),
    "problematiek": ("noun", "set of problems", "de"),
    "procent": ("noun", "percent", "het"),
    "producent": ("noun", "producer", "de"),
    "proef": ("noun", "test, experiment", "de"),
    "proeven": ("verb", "to taste", None),
    "profeet": ("noun", "prophet", "de"),
    "profiteren": ("verb", "to benefit", None),
    "progressief": ("adjective", "progressive", None),
    "propaganda": ("noun", "propaganda", "de"),
    "provinciaal": ("adjective", "provincial", None),
    "proza": ("noun", "prose", "het"),
    "psychiater": ("noun", "psychiatrist", "de"),
    "psychisch": ("adjective", "psychological", None),
    "psychologie": ("noun", "psychology", "de"),
    "psychologisch": ("adjective", "psychological", None),
    "psycholoog": ("noun", "psychologist", "de"),
    "publicatie": ("noun", "publication", "de"),
    "publiceren": ("verb", "to publish", None),
    "publiciteit": ("noun", "publicity", "de"),
    "putten": ("verb", "to draw (water); to derive", None),
    "raadsel": ("noun", "riddle, puzzle", "het"),
    "raden": ("verb", "to guess; to advise", None),
    "radicaal": ("adjective", "radical", None),
    "radio": ("noun", "radio", "de"),
    "raket": ("noun", "rocket", "de"),
    "ramp": ("noun", "disaster", "de"),
    "rapport": ("noun", "report; report card", "het"),
    "ras": ("noun", "race; breed", "het"),
    "rationeel": ("adjective", "rational", None),
    "rauw": ("adjective", "raw", None),
    "razen": ("verb", "to rage", None),
    "realistisch": ("adjective", "realistic", None),
    "realiteit": ("noun", "reality", "de"),
    "recept": ("noun", "recipe; prescription", "het"),
    "rechtbank": ("noun", "court", "de"),
    "rechten": ("noun", "rights; law (study)", "de"),
    "rechtspraak": ("noun", "justice, jurisdiction", "de"),
    "rechtvaardigen": ("verb", "to justify", None),
    "reclame": ("noun", "advertising", "de"),
    "redacteur": ("noun", "editor", "de"),
    "redactie": ("noun", "editorial staff", "de"),
    "redenering": ("noun", "reasoning", "de"),
    "reduceren": ("verb", "to reduce", None),
    "regenen": ("verb", "to rain", None),
    "regeren": ("verb", "to govern, to rule", None),
    "registreren": ("verb", "to register", None),
    "reiken": ("verb", "to reach; to hand", None),
    "reiziger": ("noun", "traveler", "de"),
    "rekken": ("verb", "to stretch", None),
    "relevant": ("adjective", "relevant", None),
    "remmen": ("verb", "to brake", None),
    "republiek": ("noun", "republic", "de"),
    "resteren": ("verb", "to remain", None),
    "resulteren": ("verb", "to result", None),
    "reus": ("noun", "giant", "de"),
    "reusachtig": ("adjective", "enormous", None),
    "revolutie": ("noun", "revolution", "de"),
    "reëel": ("adjective", "real, realistic", None),
    "richtlijn": ("noun", "guideline", "de"),
    "ridder": ("noun", "knight", "de"),
    "riem": ("noun", "belt; strap", "de"),
    "rij": ("noun", "row; line", "de"),
    "rijp": ("adjective", "ripe; mature", None),
    "rijzen": ("verb", "to rise", None),
    "rillen": ("verb", "to shiver", None),
    "rimpel": ("noun", "wrinkle", "de"),
    "rit": ("noun", "ride, trip", "de"),
    "ritme": ("noun", "rhythm", "het"),
    "ritueel": ("noun", "ritual", "het"),
    "roeien": ("verb", "to row", None),
    "roeren": ("verb", "to stir; to move", None),
    "roken": ("verb", "to smoke", None),
    "rollen": ("verb", "to roll", None),
    "rommel": ("noun", "mess, junk", "de"),
    "ronde": ("noun", "round", "de"),
    "rondlopen": ("verb", "to walk around", None),
    "rondom": ("adjective", "around, all around", None),
    "roos": ("noun", "rose", "de"),
    "rot": ("adjective", "rotten; lousy", None),
    "rots": ("noun", "rock", "de"),
    "route": ("noun", "route", "de"),
    "roze": ("adjective", "pink", None),
    "ruimen": ("verb", "to clear", None),
    "ruit": ("noun", "window pane; diamond", "de"),
    "ruiter": ("noun", "rider, horseman", "de"),
    "rukken": ("verb", "to tug, to jerk", None),
    "ruw": ("adjective", "rough", None),
    "ruzie": ("noun", "quarrel, argument", "de"),
    "ruïne": ("noun", "ruin", "de"),
}
